### PR TITLE
[generator] Throw PlatformNotSupportException in 32-bit mode for 64-bit-only iOS API. Fixes #4689.

### LINKED ISSUE #4689: dontlink/Debug/iOS 32-bit/device crashes at launch
Stack trace:

```
2018-08-23 01:32:31.684 dont link[1179:2728925] critical: Stacktrace:

2018-08-23 01:32:31.685 dont link[1179:2728925] critical: 
Native stacktrace:

2018-08-23 01:32:31.886 dont link[1179:2728925] critical: 	0   libmonosgen-2.0.dylib               0x06c952bb mono_handle_native_crash + 196
2018-08-23 01:32:31.887 dont link[1179:2728925] critical: 	1   libmonosgen-2.0.dylib               0x06c9f46d mono_sigsegv_signal_handler + 226
2018-08-23 01:32:31.887 dont link[1179:2728925] critical: 	2   libsystem_platform.dylib            0x1e018259 _sigtramp + 24
2018-08-23 01:32:31.887 dont link[1179:2728925] critical: 	3   libXamarin.iOS.dll.dylib            0x0249e500 wrapper_native_to_managed_ObjCRuntime_Runtime_register_assembly_intptr_int_ + 236
2018-08-23 01:32:31.888 dont link[1179:2728925] critical: 	4   libxamarin-debug.dylib              0x06f728ec xamarin_register_assembly + 64
2018-08-23 01:32:31.888 dont link[1179:2728925] critical: 	5   libxamarin-debug.dylib              0x06f74804 _ZL17register_assemblyP13_MonoAssemblyPj + 152
2018-08-23 01:32:31.889 dont link[1179:2728925] critical: 	6   libxamarin-debug.dylib              0x06f7578c xamarin_initialize + 992
2018-08-23 01:32:31.889 dont link[1179:2728925] critical: 	7   libxamarin-debug.dylib              0x06f89758 xamarin_main + 2004
2018-08-23 01:32:31.890 dont link[1179:2728925] critical: 	8   dont link                           0x000a6937 dont link + 563511
2018-08-23 01:32:31.890 dont link[1179:2728925] critical: 	9   libdyld.dylib                       0x1de924eb <redacted> + 2
2018-08-23 01:32:31.890 dont link[1179:2728925] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

```

The executable seems to hang, so there's no crash report.

From http://xamarin-storage/jenkins/xamarin-macios/xcode10/ea4909034b39cad25b0a04e930e410b28b9db674/1969828/device-tests/jenkins-results/tests/index.html (but also reproduced locally).

Current investigations show:

* Only 32-bit crash.
* Only debug configurations crash.
* dontlink from the d15-8 branch does not crash.
* Linking only mscorlib.dll or Xamarin.iOS.dll works.
* Linking only System.dll or System.Xml.dll still crashes.
* The exact stack trace for the crash varies a bit, but sometimes they're nonsensical (functions appear to call functions they're not calling).

This clearly indicates we're running into https://bugzilla.xamarin.com/show_bug.cgi?id=1102, where the compiled code is too big for 32-bit arm.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Throw PlatformNotSupportedException for iOS API that was introduced in iOS 11+
in 32-bit mode, since that API is clearly not available in any 32-bit capable
iOS version.

This makes the 32-bit version of Xamarin.iOS.dll smaller (from 15.282.176
bytes to 14.575.616 bytes, ~700kb smaller - small enough that this makes the
dontlink test work in 32-bit mode again on device).

Fixes https://github.com/xamarin/xamarin-macios/issues/4689.

### CODE REVIEW

File: src/generator.cs [hunk 1]
```diff
@@ -6246,18 +6309,32 @@ public void Generate (Type type)
 						sw.WriteLine ("\t\t[EditorBrowsable (EditorBrowsableState.Advanced)]");
 						sw.WriteLine ("\t\t{0} {1} (NSObjectFlag t) : base (t)", UnifiedAPI ? "protected" : "public", TypeName);
 						sw.WriteLine ("\t\t{");
+						if (is32BitNotSupported) {
+							sw.WriteLine ("\t\t#if ARCH_32");
+							sw.WriteLine ("\t\t\tthrow new PlatformNotSupportedException ();");
```
Comment (spouliot) [inline src/generator.cs]: unlike previous calls there's not description string here

File: src/generator.cs [hunk 2]
```diff
@@ -6246,18 +6309,32 @@ public void Generate (Type type)
...
 						sw.WriteLine ("\t\t}");
 						sw.WriteLine ();
 					}
 					GeneratedCode (sw, 2);
 					sw.WriteLine ("\t\t[EditorBrowsable (EditorBrowsableState.Advanced)]");
 					sw.WriteLine ("\t\t{0} {1} (IntPtr handle) : base (handle)", UnifiedAPI ? "protected internal" : "public", TypeName);
 					sw.WriteLine ("\t\t{");
+					if (is32BitNotSupported) {
+						sw.WriteLine ("\t\t#if ARCH_32");
+						sw.WriteLine ("\t\t\tthrow new PlatformNotSupportedException ();");
```
Comment (spouliot) [inline src/generator.cs]: unlike previous calls there's not description string here

File: src/foundation.cs [hunk 3]
```diff
@@ -13493,7 +13493,6 @@ interface NSUnitTemperature : NSSecureCoding {
 	}
 
 #if !WATCH && !TVOS
-	[Mac (10,8), iOS (11,0), NoWatch, NoTV]
```
Comment (VincentDondain) [inline src/foundation.cs]: Mmh wouldn't that remove the iOS 11 availability attribute on `TrashItem`?

Comment (rolfbjarne) [reply src/foundation.cs]: You're right, I missed that.

**Comment by rolfbjarne** [comment]
> Should:
> 
> ```
> sw.WriteLine ("\t\t#if ARCH_32");
> sw.WriteLine ("\tthrow new PlatformNotSupportedException (\"This API is not supported on this version of iOS\");");
> sw.WriteLine ("\t\t#else");
> ```
> be a function like Print32BitExceptionCode () so we don't have it copy pasted in a number of places?

I thought about it, but since it's not self-contained (it needs a `sw.WriteLine ("#endif")` at a later point) it ends up looking strange.

Also the code isn't exactly the same (some uses `print` to write, some uses `sw`).
