### PR TITLE
[mtouch/mmp] Handle invalid types in BlockProxy attributes better. Fixes #4072.

### LINKED ISSUE #4072: BlockProxy attribute with invalid type will cause MT0000 build error
Test case:

```csharp
class MyUrlSession : NSUrlSession
{
	public MyUrlSession ()
		: base (IntPtr.Zero)
	{
	}
	public override NSUrlSessionDataTask CreateDataTask(NSUrl url, [BlockProxy(typeof(Delegate))] NSUrlSessionResponse completionHandler)
	{
		return base.CreateDataTask(url, completionHandler);
	}
}
```

The type argument to the `[BlockProxy]` attribute is of an unexpected type, and ends up causing a build error like this:

```
MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00012] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:30 
  at Registrar.StaticRegistrar.GetBlockProxyAttributeMethod (Mono.Cecil.MethodDefinition method, System.Int32 parameter) [0x00020] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4121 
  at Registrar.StaticRegistrar.GetBlockWrapperCreator (Registrar.Registrar+ObjCMethod obj_method, System.Int32 parameter) [0x00011] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4065 
  at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb, Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[T] exceptions) [0x0216b] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:3683 
  at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb) [0x00f1e] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:2963 
```

The fix is to delete the `[BlockProxy]` attribute:

```csharp
class MyUrlSession : NSUrlSession
{
	public MyUrlSession ()
		: base (IntPtr.Zero)
	{
	}
	public override NSUrlSessionDataTask CreateDataTask(NSUrl url, NSUrlSessionResponse completionHandler)
	{
		return base.CreateDataTask(url, completionHandler);
	}
}
```

The invalid attribute probably comes from how Visual Studio for Mac ([incorrectly](https://github.com/dotnet/roslyn/issues/5646)) adds the identical `[BlockProxy]` attribute from the base method when implementing the override (i.e. typing `override <selecting the method>`). The injected attribute from the base method won't compile, because the type is an internal type, which means that some customers probably edited the type to make it compile, and thus ending up with an invalid `[BlockProxy]` attribute.

The attribute is needed at runtime: but deleting it is safe, because the Xamarin.iOS/Mac runtime will find and use the correct attribute on the base method instead.

### PR DESCRIPTION
**Pull request by rolfbjarne**
BlockProxy attributes may have types we don't expect, so handle those cases
gracefully by showing a warning when we encounter them:

    testApp.cs(11): warning MT4175: The parameter 'completionHandler' in the method 'Issue4072Session.CreateDataTask(Foundation.NSUrl,Foundation.NSUrlSessionResponse)' has an invalid BlockProxy attribute (the type passed to the attribute does not have a 'Create' method).

instead of an ugly MT0000:

    MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    System.InvalidOperationException: Sequence contains no matching element
      at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00012] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:30
      at Registrar.StaticRegistrar.GetBlockProxyAttributeMethod (Mono.Cecil.MethodDefinition method, System.Int32 parameter) [0x00020] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4121
      at Registrar.StaticRegistrar.GetBlockWrapperCreator (Registrar.Registrar+ObjCMethod obj_method, System.Int32 parameter) [0x00011] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4065
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb, Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[T] exceptions) [0x0216b] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:3683
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb) [0x00f1e] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:2963

Fixes #4072.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@spouliot this might be a `d15-7` SR candidate, since it's technically a regression (code that used to compile doesn't compile anymore).

File: tools/common/StaticRegistrar.cs [hunk 1]
```diff
@@ -4167,11 +4167,15 @@ MethodDefinition GetBlockWrapperCreator (ObjCMethod obj_method, int parameter)
...
+			var param = method.Parameters [parameter];
+			var attrib = GetBlockProxyAttribute (param);
 			if (attrib == null)
 				return null;
 
-			return attrib.Type.Methods.First ((v) => v.Name == "Create");
+			var createMethod = attrib.Type.Methods.FirstOrDefault ((v) => v.Name == "Create");
+			if (createMethod == null)
+				ErrorHelper.Show (ErrorHelper.CreateWarning (App, 4175, method, $"{(string.IsNullOrEmpty (param.Name) ? $"Parameter #{param.Index + 1}" : $"The parameter '{param.Name}'")} in the method '{GetTypeFullName (method.DeclaringType)}.{GetDescriptiveMethodName (method)}' has an invalid BlockProxy attribute (the type passed to the attribute does not have a 'Create' method)."));
+			return createMethod;
```
Comment (spouliot) [inline tools/common/StaticRegistrar.cs]: by returning `null` this looks up the base method signature right ?

File: docs/website/mmp-errors.md [hunk 2]
```diff
@@ -340,6 +340,31 @@ complicated to get it right when doing it manually.
...
+attribute:
+
+```csharp
+public override NSUrlSessionDataTask CreateDataTask (NSUrl url, NSUrlSessionResponse completionHandler)
+{
+}
+```
+
+because the base method has the correct version of the attribute, and the
+Xamarin.Mac runtime will find it there when needed.
```
Comment (spouliot) [inline docs/website/mmp-errors.md]: This sounds a bit vague, even if it does make the warning actionable. Since it's a warning there's a build still ongoing and, if it succeed, what does the warning mean ?

My understanding is that the _incorrect_ attribute is **ignored** (and that's what we warn about) so the one from the base method parameter is used.

File: tools/common/StaticRegistrar.cs (hunk 1 above)
Comment (rolfbjarne) [reply tools/common/StaticRegistrar.cs]: Correct, I've commented the code to make it clearer.

File: docs/website/mmp-errors.md (hunk 2 above)
Comment (rolfbjarne) [reply docs/website/mmp-errors.md]: @spouliot I've modified the text a bit, hopefully it's clearer now.

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/581)
