### PR TITLE
[mtouch] Consider deployment and simulator availability versions for frameworks. Fixes #5753

### LINKED ISSUE #5753: Registrar mtouch argument and managed Http client implementation make the app crash on iPad with iOS 10.3.1
### Steps to Reproduce

1. Create a new Single View iOS app.
2. Add --registrar:static mtouch argument in project settings -> iOS Build screen.
3. Set HttpClient implementation to Managed.
4. Select iPad 5th Generation with iOS 10.3.1 simulator or iPad with iOS 10.3.3.
5. Build and run the app.

### Expected Behavior
App successfully launches and runs. In Debug mode the debugger attaches to the running app.

### Actual Behavior
App tries to load but is unsuccessful: only the launch screen is shown and then crashes.
In Debug mode the debugger is unable to attach to the app.
Also, the problem persists if HtppClient implementation is set back to NSUrlSession (iOS 7+) even after a project cleanup and simulator reset.
This problem does not happen on other iOS versions or on iPhone or if HttpClient implementation is left unchanged or if additional mtouch arguments field is left empty.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.8.2 (build 1)
Installation UUID: 5c192ad2-2240-4ece-8393-4df24255d6a0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.8
	2.1.7
	2.1.4
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.504/Sdks
SDK Versions:
	2.1.504
	2.1.503
	2.1.402
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.15 (Visual Studio Community)
Hash: d60abd198
Branch: 
Build date: 2019-02-01 12:23:30-0500

=== Xamarin.Android ===

Version: 9.1.8.0 (Visual Studio Community)
Android SDK: /Users/flaviup/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1 (API level 16)
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/flaviup/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 8924ea4a

=== Xamarin.iOS ===

Version: 12.2.1.15 (Visual Studio Community)
Hash: d60abd198
Branch: d15-9
Build date: 2019-02-01 12:23:29-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 708020001
Git revision: 13e0e5b7e85ffe742957e6f204bab5c06c644f0e
Build date: 2019-02-27 19:33:14+00
Build branch: release-7.8
Xamarin extensions: 23eaa7c9cdc9a3f55be7bb87b485a790ec82ef25

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Dec 20 21:47:19 PST 2018
    root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Signature Tool 2.1.2
MSBuild Editor 2.1.0
NuGet Package Management Extensions 0.15
StyleCop Support 1.1.0.0
WakaTime 3.0.5
xUnit.NET 2 testing framework support 0.7.5
Mutatio 1.0.2
Prism Template Studio and Developer Toolkit 2.2.0.434
Redth's Addins 1.0.9
Gorilla Player 1.2.2.0
Internet of Things (IoT) development (Preview) 7.5.3
```

### Build Logs

Building FailerApp (Debug|iPhoneSimulator)
Build started 3/11/2019 3:44:43 PM.
__________________________________________________
Project "/Users/flaviup/Projects/FailerApp/FailerApp/FailerApp.csproj" (Build target(s)):

Target _CoreCompileInterfaceDefinitions:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 10.0 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk --compilation-directory /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool /Users/flaviup/Projects/FailerApp/FailerApp/LaunchScreen.storyboard
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 10.0 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk --compilation-directory /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool /Users/flaviup/Projects/FailerApp/FailerApp/Main.storyboard
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 10.0 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk --link /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool/LaunchScreen.storyboardc /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool/Main.storyboardc
      BundleResources Output:
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/Info.plist
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/Info.plist
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib
      OutputManifests Output:
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-manifests/LaunchScreen.storyboardc
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-manifests/Main.storyboardc
        obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-manifests/link
Target _BeforeCoreCompileImageAssets:
    Directory "obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool" doesn't exist. Skipping.
Target _CoreCompileImageAssets:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/actool execution started with arguments: --errors --warnings --notices --output-format xml1 --output-partial-info-plist /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool/partial-info.plist --app-icon AppIcon --compress-pngs --filter-for-device-model iPad6,12 --filter-for-device-os-version 10.3.1 --target-device iphone --target-device ipad --minimum-deployment-target 10.0 --platform iphonesimulator --compile /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool/bundle /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool/cloned-assets/Assets.xcassets
    /Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcon" has an unassigned child.
Done building target "_CoreCompileImageAssets" in project "FailerApp.csproj".
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
    Directory "obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/coremlc" doesn't exist. Skipping.
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because it has no outputs.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because it has no inputs.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because it has no inputs.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe /noconfig /nowarn:2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:__IOS__;__MOBILE__;__UNIFIED__;DEBUG;ENABLE_TEST_CLOUD /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/mscorlib.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Core.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Xml.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll /debug+ /debug:portable /optimize- /out:obj/iPhoneSimulator/Debug/FailerApp.exe /target:exe /utf8output Main.cs AppDelegate.cs ViewController.cs ViewController.designer.cs "/var/folders/c2/ghpn8_h16nx61rn8pbfv5wl80000gn/T/Xamarin.iOS,Version=v1.0.AssemblyAttributes.cs"
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/FailerApp.exe" to "/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/FailerApp.exe".
    FailerApp -> /Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/FailerApp.exe
    Copying file from "/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/FailerApp.pdb" to "/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/FailerApp.pdb".
Target _DetectSigningIdentity:
    Detected signing identity:
      Bundle Id: com.me.FailerApp
      App Id: com.me.FailerApp
Target _CopyResourcesToBundle:
    Creating directory '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/LaunchScreen.storyboardc'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/Info.plist' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/LaunchScreen.storyboardc/Info.plist'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib'
    Creating directory '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/Main.storyboardc'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/Info.plist' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/Main.storyboardc/Info.plist'
    Copying file from '/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib' to '/Users/flaviup/Projects/FailerApp/FailerApp/bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/Main.storyboardc/UIViewController-BYZ-38-t0r.nib'
Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 127.0.0.1
Target _CompileAppManifest:
    Directory "bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app.dSYM" doesn't exist. Skipping.
Target _ParseExtraMtouchArgs:
      NoSymbolStrip Output: true
      NoDSymUtil Output: false
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/response-file.rsp --registrar:static 
    Creating "bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/mtouch.stamp" because "AlwaysCreate" was specified.
Target _CopyAppExtensionsToBundle:
    Directory "bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/PlugIns/_CodeSignature" doesn't exist. Skipping.
    Directory "bin/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/FailerApp.app/../.dSYM" doesn't exist. Skipping.
Target _CollectFrameworks:
    No Frameworks directory found.

Done building project "FailerApp.csproj".

Build succeeded.

/Users/flaviup/Projects/FailerApp/FailerApp/obj/iPhoneSimulator/Debug/device-builds/ipad6.12-10.3.1/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcon" has an unassigned child.
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:09.18

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Build: 0 errors, 1 warning
### Example Project (If Possible)

[FailerApp.zip](https://github.com/xamarin/xamarin-macios/files/2952421/FailerApp.zip)

### PR DESCRIPTION
**Pull request by spouliot**
E.g. `MetalPerformanceShaders` is unusable in 10.3.1 on the simulator so
trying to build with the static registrar cause simlauncher to be rebuilt
with a **strong** (and not _weak_) reference to the framework. This cause
a crash then the application start

```
Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/95679F95-CCE7-4733-8376-35E91E97039C/data/Containers/Bundle/Application/0F665B2D-ADAC-4CA0-BD04-33E968B3F268/FailerApp.app/FailerApp
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders: mach-o, but not built for iOS simulator
```

ref: https://github.com/xamarin/xamarin-macios/issues/5753

### CODE REVIEW

File: tools/common/Assembly.cs [hunk 1]
```diff
@@ -449,8 +449,20 @@ void AddFramework (string file)
 		{
 			if (Driver.GetFrameworks (App).TryGetValue (file, out var framework) && framework.Version > App.SdkVersion)
 				ErrorHelper.Warning (135, "Did not link system framework '{0}' (referenced by assembly '{1}') because it was introduced in {2} {3}, and we're using the {2} {4} SDK.", file, FileName, App.PlatformName, framework.Version, App.SdkVersion);
-			else if (Frameworks.Add (file))
-				Driver.Log (3, "Linking with the framework {0} because it's referenced by a module reference in {1}", file, FileName);
+			else {
+#if MTOUCH
+				var strong = (framework == null) || (App.DeploymentTarget >= (App.IsSimulatorBuild ? framework.VersionAvailableInSimulator ?? framework.Version : framework.Version));
```
Comment (chamons) [inline tools/common/Assembly.cs]: Should we promote this to a property off assembly?

Comment (spouliot) [reply tools/common/Assembly.cs]: I'm a "one, two, many" guy :)
Also I don't see how it can be turned into a property since it's based on `framework`

Comment (chamons) [reply tools/common/Assembly.cs]: That's fine, good point.
