### PR TITLE
[coreimage] Add generator support for CIVector[] and enable it in CIMeshGenerator. Fix #4226

### LINKED ISSUE #4226: Generator does not support NSArray (or arrays) for CoreImage filters
### Steps to Reproduce

1. Uncomment `CIVector []` from `coreimage.cs`
2. Build

### Expected Behavior

Generated getter and setter

### Actual Behavior

```
error BI1018: bgen: Unimplemented CoreImage property type CIVector[]
```

### Environment

```
xamarin-macios/xcode10
```

### Build Logs

```
GEN      [tvos] generated_sources
error BI1018: bgen: Unimplemented CoreImage property type CIVector[]
make[1]: *** [build/tvos/tvos/generated_sources] Error 1
make[1]: *** Waiting for unfinished jobs....
error BI1018: bgen: Unimplemented CoreImage property type CIVector[]
make[1]: *** [build/ios/native/generated_sources] Error 1
error BI1018: bgen: Unimplemented CoreImage property type CIVector[]
make[1]: *** [build/mac/mobile/generated-sources] Error 1
error BI1018: bgen: Unimplemented CoreImage property type CIVector[]
make[1]: *** [build/mac/full/generated-sources] Error 1
make: *** [all-recurse] Error 1
```

### PR DESCRIPTION
**Pull request by spouliot**
https://github.com/xamarin/xamarin-macios/issues/4226

### CODE REVIEW

File: src/generator-filters.cs [hunk 1]
```diff
@@ -247,6 +251,17 @@ void GenerateFilterSetter (string propertyType, string propertyName)
...
 			indent--;
 			break;
+		case "CIVector[]":
+			print ("if (value == null) {");
+			indent++;
+			print ($"SetHandle (\"{propertyName}\", IntPtr.Zero);");
+			indent--;
+			print ("} else {");
+			indent++;
+			print ($"SetHandle (\"{propertyName}\", NSArray.FromNSObjects (value).GetHandle ());");
```
Comment (rolfbjarne) [inline src/generator-filters.cs]: The GC can collect the NSArray before native code gets the handle.
