### PR TITLE
[UIKit] Add Constructor for UIHoverGestureRecognizer

### LINKED ISSUE #15335: Provide a ctor to UIHoverGestureRecognizer that takes Action<UIHoverGestureRecognizer>
### Steps to Reproduce

Most [GestureRecognizers](https://github.com/xamarin/xamarin-macios/blob/1fa43189b5b0392726f97e9b2576dc25b329699e/src/UIKit/UIGestureRecognizer.cs#L162) provide a ctor that will pass the gesture as an action argument.  This is very useful for trying to combat circular references so that the GC can collect everything without having to remove the GC. 

We added our own [ctor](https://github.com/dotnet/maui/blob/d86ee5d603c41d7e9071bf41da11f205d6ca98a1/src/Core/src/Platform/iOS/PlatformTouchGraphicsView.cs#L88) into .NET MAUI  so that we could pass in a static action.  I can't figure out how to make a UIHoverGestureRecognizer not leak using the provided Action because the supplied action will almost always end up capture "this".  

We could even take this further and obsolete all ctor's that only take "Action" thus promoting a more successful path. 

### Expected Behavior

// No circles. No leaks
```C#
new UIHoverGestureRecognizer(OnHover)
static void OnHover(UIHoverGestureRecognizer hoverGesture)
{
  var platformView = hoverGesture.View as PlatformTouchGraphicsView;
```

### Actual Behavior
// Circles. Won't GC
```C#
new UIHoverGestureRecognizer(OnHover)
void OnHover()
{
  this.DoStuff();
```

### Environment

net6.0-ios

### Example Project (If Possible)

This project demonstrates how I can easily make a UITapGestureRecognizer not leak vs leak by using a static method vs a non static method

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/8968858/Archive.zip)

### PR DESCRIPTION
**Pull request by haritha-mohan**
Fixes #15335

### CODE REVIEW

File: src/UIKit/UIGestureRecognizer.cs [hunk 1]
```diff
@@ -319,4 +319,27 @@ public void Activated (UIScreenEdgePanGestureRecognizer sender)
 #endif
 }
 
+// start code for UIHoverGestureRecognizer Constructor
+	public partial class UIHoverGestureRecognizer : UIGestureRecognizer {
+		public UIHoverGestureRecognizer (Action action) : base (action) {}
```
Comment (mandel-macaque) [inline src/UIKit/UIGestureRecognizer.cs:324]: I believe this is not needed since we already expose a constructor in the generated code:
```csharp
	[NoWatch, NoTV, iOS (13,0)]
	[BaseType (typeof (UIGestureRecognizer))]
	[DisableDefaultCtor]
	interface UIHoverGestureRecognizer {

		[DesignatedInitializer]
		[Export ("initWithTarget:action:")]
		NativeHandle Constructor (NSObject target, Selector action);

		[DesignatedInitializer]
		[Wrap ("base (action)")]
		NativeHandle Constructor (Action action);
	}
```
Have your tried removing it? Is it giving you an issue?

File: src/UIKit/UIGestureRecognizer.cs [hunk 2]
```diff
@@ -319,4 +319,27 @@ public void Activated (UIScreenEdgePanGestureRecognizer sender)
...
+			{
+				this.action = action;
+			}
+			
+			[Export ("target:")]
+			[Preserve (Conditional = true)]
+			public void Activated (UIHoverGestureRecognizer sender)
+			{
+				action (sender);
+			}
```
Comment (mandel-macaque) [inline src/UIKit/UIGestureRecognizer.cs:341]: Little trick in the new c# syntax, you can do:
```suggestion
			public void Activated (UIHoverGestureRecognizer sender) => action (sender);
```

**Review by mandel-macaque — APPROVED** [review]
Great work, in theory, there are not changes needed if you don't want them. I wonder, if we add at the top of the file:

#nullable enable

What happens? It might as for some changes, maybe to many for the intent of the PR (but good for you to check). Tests for the other actions are missing, but we should write them. We need to add tests under:

tests/monotouch/UIkit

I think we can look at how to test the execution of the callback, and then use a pattern for it.

**Review by dalexsoto — COMMENTED** [review]
This is great 👍

**Comment by haritha-mohan** [comment]
Will be coming back to fix this issue. After talking to Manuel, we realized it would be better to add generics and clean up the code to make the bug much easier to fix.

**Comment by stephen-hawley** [comment]
:eyes:

File: .gitignore [hunk 3]
```diff
@@ -39,3 +39,7 @@ provision-xcode.csx
 mono_crash.*.json
 *.binlog
 .vscode
+tests/BundledResources/BundledResources.csproj
+tests/EmbeddedResources/EmbeddedResources.csproj
+tests/fsharplibrary/fsharplibrary.fsproj
+external/Touch.Unit
```
Comment (mandel-macaque) [inline .gitignore:45]: No need to add the external repo.

File: tests/monotouch-test/UIKit/GestureRecognizerTest.cs [hunk 4]
```diff
@@ -89,6 +90,32 @@ public void NoStrongCycles ()
...
+
+			// add gesture recognizer to UI view
+			using (UIView view = new UIView ()) {
+				view.AddGestureRecognizer (recognizer);
+				TestRuntime.RunAsync (DateTime.Now.AddSeconds (30), () => {
+					// change state of gesture recognizer to execute callback
+					recognizer.State = UIGestureRecognizerState.Changed;
+					recognizer.State = UIGestureRecognizerState.Ended;
+				}, () => didRun);
+			}
```
Comment (mandel-macaque) [inline tests/monotouch-test/UIKit/GestureRecognizerTest.cs:112]:
```suggestion
			using UIView view = new UIView ();
			view.AddGestureRecognizer (recognizer);
			TestRuntime.RunAsync (DateTime.Now.AddSeconds (30), () => {
				// change state of gesture recognizer to execute callback
				recognizer.State = UIGestureRecognizerState.Changed;
				recognizer.State = UIGestureRecognizerState.Ended;
			}, () => didRun);
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
Tiny small comments. We need @rolfbjarne to verify we are ok with the .gitignore.

File: .gitignore (hunk 3 above)
Comment (mandel-macaque) [inline .gitignore:45]:
```suggestion
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: tests/monotouch-test/UIKit/GestureRecognizerTest.cs [hunk 5]
```diff
@@ -89,6 +90,32 @@ public void NoStrongCycles ()
...
+		[Test]
+		public void GenericCallbackTest ()
+		{
+			var didRun = false;
+			var callbackEvent = new AutoResetEvent (false);
+			var callback = (UITapGestureRecognizer _) => {
+				didRun = true;
+				callbackEvent.Set ();
+			};
+			var recognizer = new UITapGestureRecognizer (callback);
```
Comment (mandel-macaque) [inline tests/monotouch-test/UIKit/GestureRecognizerTest.cs:102]:
```suggestion
			using var recognizer = new UITapGestureRecognizer (callback);
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: .gitignore [hunk 6]
```diff
@@ -39,3 +39,6 @@ provision-xcode.csx
 mono_crash.*.json
 *.binlog
 .vscode
+tests/BundledResources/BundledResources.csproj
+tests/EmbeddedResources/EmbeddedResources.csproj
+tests/fsharplibrary/fsharplibrary.fsproj
```
Comment (rolfbjarne) [inline .gitignore:44]: This change is not related to this PR, so it should be removed.

If needed, it should go in a separate PR, explaining the reason for the change (I'm also a bit puzzled about this change, because these files are already checked into git, so they shouldn't be ignored, nor should this actually change any behavior),

File: tests/.gitignore [hunk 7]
```diff
@@ -34,3 +34,6 @@ logs
 x86
 bcl-test/templates
 *.7z
+BundledResources/Info.plist
+EmbeddedResources/Info.plist
+fsharplibrary/Info.plist
```
Comment (rolfbjarne) [inline tests/.gitignore:39]: Same

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

**Review by tj-devel709 — APPROVED** [review]
After addressing the other issues!

File: tests/.gitignore (hunk 7 above)
Comment (mandel-macaque) [reply tests/.gitignore:39]: This is due to vsmac making changes. I wpuld blame VSMac for modifying files when it should not.

**Review by rolfbjarne — APPROVED** [review]
Looks great!

Except that the compiler complains about the test:

> tests/monotouch-test/UIKit/GestureRecognizerTest.cs(98,8): error CS0815: Cannot assign lambda expression to an implicitly-typed variable

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/2620), so this is good to go!

**Review by mandel-macaque — APPROVED** [review]
