### PR TITLE
[AppKit/UIKit] Adjust a few availability attributes in NS[Mutable]ParagraphStyle. Fixes #19209.

### LINKED ISSUE #19209: Incorrect SupportedOSPlatform attributes on various properties
Similar bug report as here: https://github.com/xamarin/xamarin-macios/issues/19066

### Steps to Reproduce

Use `NSMutableParagraphStyle.TextLists` in a project with MinimumOSVersion < 16.0

### Expected Behavior
No warning

### Actual Behavior
`/Users/tipa/GitHub/diarium/Diarium/Classes/Helper_macios.cs(99,25): warning CA1416: This call site is reachable on: 'iOS' 15.0 and later, 'maccatalyst' 15.0 and later. 'NSParagraphStyle.TextLists' is only supported on: 'ios' 16.0 and later, 'maccatalyst' 16.0 and later, 'tvos' 16.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416) 
`

### Comments

Documented to be available since iOS 7:
https://developer.apple.com/documentation/uikit/nsparagraphstyle/1534193-textlists?language=objc

https://github.com/xamarin/xamarin-macios/blob/343699204a3ff1f591e861e046baa672fc7e6626/src/xkit.cs#L1797-L1799
I haven't tested functionality yet, but at least setting & getting the property does not crash on iOS 15:

```
var xx = new NSMutableParagraphStyle();
xx.TextLists = new[] { new NSTextList(NSTextListMarkerFormats.Circle) };
var yy = xx.TextLists[0];
```

Documented to be available since iOS 9:
https://developer.apple.com/documentation/uikit/nsparagraphstyle/3667463-linebreakstrategy?language=objc

https://github.com/xamarin/xamarin-macios/blob/343699204a3ff1f591e861e046baa672fc7e6626/src/xkit.cs#L1811-L1814

There's probably even more properties for which Apple changed their min API level with the last SDK...

### Environment
.NET 8 RC2

### PR DESCRIPTION
**Pull request by rolfbjarne**
Both headers and documentation agree that:

* The TextLists and LineBreakStrategy properties are available in all OS
  versions we support, so adjust the availability attributes accordingly.

* While the NSLineBreakStrategy enum is supposedly not available in all OS
  versions we support, the NSLineBreakStrategy.PushOut enum value is. This
  doesn't make much sense, so I've made our enum available in all OS versions
  + the PushOut enum value as well. All the other enum values are only
  available in iOS 14+ (according to docs + headers).

Fixes https://github.com/xamarin/xamarin-macios/issues/19209.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

File: src/xkit.cs [hunk 1]
```diff
@@ -1861,7 +1861,7 @@ interface NSMutableParagraphStyle {
 		NSTextTableBlock [] TextBlocks { get; set; }
 #endif
 
-		[iOS (16, 0), TV (16, 0), NoWatch, MacCatalyst (16, 0)]
+		[NoWatch, MacCatalyst (13, 1)]
 		[NoMacCatalyst]
```
Comment (haritha-mohan) [inline src/xkit.cs:1865]: this isn't really a part of this pr's changes, but why do we have conflicting attrs here? based on docs it is available starting from mac cat 13.1+, so seems a bit weird having `[NoMacCatalyst]` here as well?

**Review by tj-devel709 — APPROVED** [review]
Am curious about Haritha's comment, but other than that LGTM

File: src/xkit.cs (hunk 1 above)
Comment (rolfbjarne) [reply src/xkit.cs:1865]: That looks like an old c&p mistake. I'll fix it too.
