### PR TITLE
Fix NLLanguageRecognizer crash

### LINKED ISSUE #6688: NullReferenceException in NLLanguageRecognizer
### Steps to Reproduce

1. Create a string that contain jus one number (ex: "1")
2. Give that as input to `NLLanguageRecognizer.GetDominantLanguage`
3. Crash

### Expected Behavior

No crash

### Actual Behavior

Crash with error:
`System.NullReferenceException`
`Object reference not set to an instance of an object`

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.1.5 (build 9)
Installation UUID: 110a0fc9-6a95-47c9-a92b-5e01aeb2bdd5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.6
	2.2.5
	2.2.2
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.301/Sdks
SDK Versions:
	2.2.301
	2.2.300
	2.2.104
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Community)
Commit: HEAD/d0b48056f
Android SDK: /Users/sofokli1/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/sofokli1/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

Just put the following anywhere and it will crash
`NLLanguageRecognizer.GetDominantLanguage("1");`

### PR DESCRIPTION
**Pull request by sofokli1**
Closes #6688 

The dispose of `nslang` was happening outside of the check if `nslang` is null. This was causing a crash when trying to recognise a string that contains just one number.

### CODE REVIEW

**Comment by chamons** [comment]
build

File: src/NaturalLanguage/NLLanguageRecognizer.cs [hunk 1]
```diff
@@ -34,10 +34,11 @@ public static NLLanguage GetDominantLanguage (string @string)
 			var nsstring = NSString.CreateNative (@string);
 			var nslang = _GetDominantLanguage (nsstring);
 			var lang =  NLLanguage.Undetermined;
-			if (nslang != null)
+			if (nslang != null) {
 				lang = NLLanguageExtensions.GetValue (nslang);
+				nslang.Dispose ();
+			}
```
Comment (mandel-macaque) [inline src/NaturalLanguage/NLLanguageRecognizer.cs]: Change does fix the issue, what about making the code smaller and probably easier to read. GetValue is generated as :

```csharp
public static NLLanguage GetValue (NSString constant)
                {
                        if (constant == null)
                                return NLLanguage.Unevaluated;
                        if (constant.IsEqualTo (NLLanguageUndetermined))
                                return NLLanguage.Undetermined;
                        if (constant.IsEqualTo (NLLanguageAmharic))
                                return NLLanguage.Amharic;
                        if (constant.IsEqualTo (NLLanguageArabic))
                                return NLLanguage.Arabic;
                        if (constant.IsEqualTo (NLLanguageArmenian))
                                return NLLanguage.Armenian;
                        if (constant.IsEqualTo (NLLanguageBengali))
                                return NLLanguage.Bengali;
                        if (constant.IsEqualTo (NLLanguageBulgarian))
                                return NLLanguage.Bulgarian;
                        if (constant.IsEqualTo (NLLanguageBurmese))
                                return NLLanguage.Burmese;
                        if (constant.IsEqualTo (NLLanguageCatalan))
                                return NLLanguage.Catalan;
                        if (constant.IsEqualTo (NLLanguageCherokee))
                                return NLLanguage.Cherokee;
...
                        return NLLanguage.Unevaluated;
}
```
So, we can pass null to GetValue, in that case we could do something like:
```csharp
var lang = NLLanguageExtensions.GetValue (nslang); // if null or not known, returns NLLanguage.Unevaluated
nslang?.Dispose();
```

We remove the need to init the lang to NLLanguage.Undetermined which might not be the correctly expected result  (at least from an objc user perspective) and we remove the if branching.

Could we get a test case added here: https://github.com/xamarin/xamarin-macios/blob/master/tests/monotouch-test/NaturalLanguage/NLLanguageRecognizerTest.cs

PS: THANKS for the PR!!!

**Comment by sofokli1** [comment]
build

File: src/NaturalLanguage/NLLanguageRecognizer.cs (hunk 1 above)
Comment (sofokli1) [reply src/NaturalLanguage/NLLanguageRecognizer.cs]: changes request addressed

**Comment by dalexsoto** [comment]
build

**Comment by spouliot** [comment]
@monojenkins backport to xcode11
