### PR TITLE
[mtouch][mmp] Report invalid debug symbols files. Fixes #3200

### LINKED ISSUE #3200: Incorrect debug symbols should warn (not error) during builds
### Steps to Reproduce

The issue can be seen with the (unmerged) tests from https://github.com/xamarin/xamarin-macios/pull/3079 or bugzilla [61142](https://bugzilla.xamarin.com/show_bug.cgi?id=61142)

### Expected Behavior

A **warning** reporting that the debugging symbols are incorrect (e.g. out of date) and that it might affect how the application can be debugged.

### Actual Behavior

An `MT0009` **error**. Beside the details being non-obvious (to solve) the workarounds are not ideal, e.g. deleting a .pdb from nuget would need to be done overtime it's cloned/refreshed and _maybe_ updated (until fixed)

note: in 15.6 and earlier this was ignored.

### Additional information

The reason for the error comes from fixing https://bugzilla.xamarin.com/show_bug.cgi?id=60277
So this needs to still work after the move to a warning.

### PR DESCRIPTION
**Pull request by spouliot**
Try to read the assembly with symbols and, if that fails, warn and
fallback to loading them without symbols.

This fixes cases were it's not easy to update or delete (e.g. nuget)
bad symbols files - so this cannot be an error without causing a lot
of pain.

However it needs to be reported, otherwise it wont be fixed (by the
publisher) and it can limit the debugability of the application and
the usefulness of the stacktraces.

Finally merge most of the resolver's code between mtouch and mmp so
we don't have to fix such issue twice anymore.

note: this needs to be slightly updated once we get a version of cecil
that can give us a more precise error message.

Also bring Rolf's tests from
https://github.com/xamarin/xamarin-macios/pull/3079

reference:
https://github.com/xamarin/xamarin-macios/issues/3200

### CODE REVIEW

File: tools/common/CoreResolver.cs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+
+				var parameters = CreateDefaultReaderParameters (fileName);
+				try {
+					assembly = ModuleDefinition.ReadModule (fileName, parameters).Assembly;
+				}
+				catch (InvalidOperationException e) {
+					// cecil use the default message so it's not very helpful to detect the root cause
+					if (!e.TargetSite.ToString ().Contains ("Void ReadSymbols(Mono.Cecil.Cil.ISymbolReader)"))
+						throw;
+					ErrorHelper.Show (ErrorHelper.CreateWarning (129, $"Debugging symbol file for '{fileName}' does not match the assembly and is ignored."));
```
Comment (rolfbjarne) [inline tools/common/CoreResolver.cs]: If you show the warning after (successfully) loading the assembly without debug symbols, you won't end up showing the warning if there's something else wrong with the assembly (in which case it would be confusing).

Comment (spouliot) [reply tools/common/CoreResolver.cs]: good point, telling the symbols are bad and then failing to load the assembly is confusing
I'll re-order this

File: tools/common/CoreResolver.cs [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+						fileName = archName;
+				}
+
+				var parameters = CreateDefaultReaderParameters (fileName);
+				try {
+					assembly = ModuleDefinition.ReadModule (fileName, parameters).Assembly;
+				}
+				catch (InvalidOperationException e) {
+					// cecil use the default message so it's not very helpful to detect the root cause
+					if (!e.TargetSite.ToString ().Contains ("Void ReadSymbols(Mono.Cecil.Cil.ISymbolReader)"))
```
Comment (spouliot) [inline tools/common/CoreResolver.cs]: https://github.com/jbevain/cecil/issues/480

**Comment by spouliot** [comment]
known failure -> https://github.com/xamarin/maccore/issues/612 which was fixed while this was building (so it was not picked up)

File: docs/website/mmp-errors.md [hunk 3]
```diff
@@ -104,6 +108,17 @@ A last-straw solution would be to use an older version of Xamarin.Mac, one that
 
 ### <a name="MM0114">MM0114: Hybrid AOT compilation requires all assemblies to be AOT compiled.
 
+### <a name="MT0129"/>MT0129: Debugging symbol file for '*' does not match the assembly and is ignored.
```
Comment (timrisi) [inline docs/website/mmp-errors.md]: Should be MM, not MT

Comment (spouliot) [reply docs/website/mmp-errors.md]: oops, missed that one (but somehow did the MM0009)
