### PR TITLE
[security] Strongly typed key generation

### LINKED ISSUE #3486: Similar to the work on `SecKey.GenerateKeyPair` we need to add a strong dictionary to `SecKey.CreateRandomKey`
### Steps to Reproduce

Here's the Swift code, here's the doc https://developer.apple.com/documentation/security/1823694-seckeycreaterandomkey.

``` Swift
guard
let aclObject = SecAccessControlCreateWithFlags(
    kCFAllocatorDefault,
    kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly,
    [.privateKeyUsage,.touchIDAny],
    nil
    ) else {
    print("could not create ACL error")
    return""
}
        
        
// private key parameters
let privateKeyParams: [String: AnyObject] = [
    kSecAttrAccessControl asString:    aclObject asAnyObject, //protect with touch id
    kSecAttrIsPermanent asString:      trueas AnyObject,
]
        
        
// global parameters for our key generation
let parameters: [String: AnyObject] = [
    kSecAttrTokenID asString:          kSecAttrTokenIDSecureEnclave,
    kSecAttrKeyType asString:          kSecMessECCKeyType,
    kSecAttrKeySizeInBits asString:    kSecMessECCKeySize asAnyObject,
    kSecAttrLabel asString:            kSecMessECCSignLabel asAnyObject,
    kSecPrivateKeyAttrs asString:      privateKeyParams asAnyObject
]
        
        
guard
let eCCPrivKey = SecKeyCreateRandomKey(parameters asCFDictionary, nil) else {
    print("ECC KeyGen Error!")
    return""
}

guard
let eCCPubKey = SecKeyCopyPublicKey(eCCPrivKey) else {
    print("ECC Pub KeyGen Error")
    return""
}
```

We currently don't have a way to do that because we didn't open the keys (they are `[Internal]`).

### Expected Behavior

Similar to https://github.com/xamarin/xamarin-macios/pull/3438 we should have a strong dictionary based on the Apple documentation linked above to set those keys (with strong types).

### Actual Behavior

We can't set the keys.

### PR DESCRIPTION
**Pull request by mdbech**
As discussed in #3350 and on gitter this pull request should resolve #3486. 

I have created a new strongly typed type, `SecKeyGenerationParameters`, and an overloaded method `SecKey.CreateRandomKey`, which enables parameterisation of key generation.

The properties of the `SecKeyGenerationParameters`-type is based on https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/key_generation_attributes

NB! I might be off with the test case, but I found it appropriate to add it. Let me know what needs fixing and I will try to do that tomorrow at work.

### CODE REVIEW

**Comment by spouliot** [comment]
build

File: tests/monotouch-test/Security/CertificateTest.cs [hunk 1]
```diff
@@ -629,5 +629,48 @@ public void GenerateKeyPairTest ()
 				Assert.That (attrs.Count, Is.GreaterThan (0), "private/GetAttributes");
 			}
 		}
+
+		[Test]
+		public void CreateRandomKeyWithParametersTests ()
+		{
+#if IOS || TVOS
+			if (!TestRuntime.CheckXcodeVersion (10, 0)) return;
```
Comment (rolfbjarne) [inline tests/monotouch-test/Security/CertificateTest.cs]: `TestRuntime.CheckXcodeVersion` checks the *Xcode* version, not the OS version :smile: It will do the right OS version check matching the specified Xcode version depending on which platform it's running on (it was implemented precisely to avoid adding these kinds of #ifs all over the place).

There's also `TestRuntime.AssertXcodeVersion`, which will call `Assert.Ignore (...);` if the version check fails, and the test will be ignored.

This means you can replace the three different checks with a single (non-conditional) line like this:

```csharp
TestRuntime.AssertXcodeVersion (8, 0);
```

and that will do the right check according to which platform it's running on (iOS/tvOS 10, macOS 10.12, watchOS 3.0).

**Comment by mdbech** [comment]
@rolfbjarne that should now be fixed. Thanks for the feedback!

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by mdbech** [comment]
Okay looking at https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6373/Test_Report/ there is 4 issues with test case. I have solved the two `CS0128: A local variable or function named 'keyGenerationParameters' is already defined in this scope` errors and the `error CS0121: The call is ambiguous between the following methods or properties` error with https://github.com/xamarin/xamarin-macios/pull/3502/commits/6409579019b61591388cc0f281f2dce36a8b09a6 but I'm unsure how to fix `'SecKeyGenerationParameters' does not contain a definition for 'IsPermanent' and no extension method 'IsPermanent' accepting a first argument of type 'SecKeyGenerationParameters' could be found (are you missing a using directive or an assembly reference?` as I have the following definition for `SecKeyGenerationParameters`:
```c#
[StrongDictionary ("SecKeyGenerationAttributeKeys")]
interface SecKeyGenerationParameters : SecPublicPrivateKeyAttrs
```
And the `SecPublicPrivateKeyAttrs`-interface contains a `IsPermanent`-property.

**Comment by dalexsoto** [comment]
build

**Comment by mdbech** [comment]
Because of this example https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave - look under **Assemble the Attributes**

**Comment by VincentDondain** [comment]
Conversation was brought to Gitter, starting here: https://gitter.im/xamarin/xamarin-macios?at=5a870d0976ced47639ef3101

Conclusion here: https://gitter.im/xamarin/xamarin-macios?at=5a87130f76ced47639ef63b2

_Note: disregard the multiple messages (we had a bug with our Slack/Gitter bridge)._

**Comment by mdbech** [comment]
I have now changed the strong dictionaries such that there isn't any relation between SecPublicPrivateKeyAttributes and SecKeyParameters+SecKeyGenerationParameters. This has introduced some redundancy, but I think it is the better of two evils, instead of introducing more checks to the GenerateKeyPair process.

I also hope that this commit fixes the OSError -4 from the previous commit, as the KeyType was not properly done, which it should be now, as the KeyType is determined in a similar manner to that of the SecRecord-class. However I have been having problems with debug a single unit test in VS2017 for Mac and as such I'm not 100% it will work - sorry.

**Comment by VincentDondain** [comment]
build

**Comment by VincentDondain** [comment]
> This has introduced some redundancy, but I think it is the better of two evils

Not a fan of the redundancy but I stand by my initial comment and also think it is the better of two evils.

`SecKeyCreateRandomKey` uses a different dictionary than `SecKeyGeneratePair` and the initial solution where could pass `kSecAttrAccessControl` to `SecKeyGeneratePair` (because it was added to `SecPublicPrivateKeyAttrs` introduced some issues on the Mac.

I think it's best to guide users into using the right subset of the attributes according to Apple's documentation so we limit the amount of issue they can encounter.

I'd like other team members to give their opinion on the new APIs after https://github.com/xamarin/xamarin-macios/pull/3502/commits/1ce0e9385f9226a31c562beb4dfeb82ba548a52a, please re-review.

**Comment by VincentDondain** [comment]
build

**Comment by VincentDondain** [comment]
Known "ProtocolTest" failures: https://github.com/xamarin/maccore/issues/655

File: src/Security/Items.cs [hunk 2]
```diff
@@ -1733,4 +1733,65 @@ public SecurityException (SecStatusCode code) : base (ToMessage (code))
...
+
+			set {
+				if (value == null)
+					throw new ArgumentNullException (nameof (value));
+				_secAccessControl = value;
+				SetNativeValue (SecAttributeKeys.AccessControlKey, value);
+			}
+		}
+
+		public SecTokenID TokenID {
```
Comment (dalexsoto) [inline src/Security/Items.cs]: I think this should be `TokenId` instead

File: src/Security/Items.cs [hunk 3]
```diff
@@ -1733,4 +1733,65 @@ public SecurityException (SecStatusCode code) : base (ToMessage (code))
 		{
 		}
 	}
+
+	public partial class SecKeyParameters : DictionaryContainer {
+		// For caching, as we can't reverse it easily.
+		SecAccessControl _secAccessControl;
+
+		public SecAccessControl AccessControl {
```
Comment (spouliot) [inline src/Security/Items.cs]: that's missing an availability attribute, it's iOS8 (double check)
so not available in our minimum baseline of iOS 6

File: src/Security/Items.cs [hunk 4]
```diff
@@ -1733,4 +1733,65 @@ public SecurityException (SecStatusCode code) : base (ToMessage (code))
...
+				if (k == null)
+					throw new ArgumentException ("Unknown value for KeyType.");
+				SetStringValue (SecKeyGenerationAttributeKeys.KeyTypeKey, k);
+			}
+		}
+
+		// For caching, as we can't reverse it easily.
+		SecAccessControl _secAccessControl;
+
+		public SecAccessControl AccessControl {
```
Comment (spouliot) [inline src/Security/Items.cs]: same availability

File: src/Security/Items.cs (hunk 2 above)
Comment (spouliot) [inline src/Security/Items.cs]: same availability missing

Comment (spouliot) [reply src/Security/Items.cs]: yes, but let's be consistent with existing usages

File: src/security.cs [hunk 5]
```diff
@@ -389,6 +389,10 @@ interface SecAttributeKeys {
 		[Field ("kSecAttrEffectiveKeySize")]
 		NSString EffectiveKeySizeKey { get; }
 
+		[iOS (8,0), Mac(10,10)]
```
Comment (spouliot) [inline src/security.cs]: that needs to be copied in the publicly exposed API

File: src/security.cs [hunk 6]
```diff
@@ -408,16 +412,95 @@ interface SecAttributeKeys {
...
+		[Mac (10,8)]
+		[Field ("kSecPrivateKeyAttrs")]
+		NSString PrivateKeyAttrsKey { get; }
+
+		[Mac (10,8)]
+		[Field ("kSecPublicKeyAttrs")]
+		NSString PublicKeyAttrsKey { get; }
+
+		[iOS (9,0)]
+		[Mac (10,12)]
```
Comment (spouliot) [inline src/security.cs]: same, must be copied to publicly visible API

**Comment by spouliot** [comment]
@VincentDondain please proceed for the back port to 15.7, thanks!
