### PR TITLE
[AVFoundation] Fix Capitalization Issue in type AVCaptureDeviceFormat

### LINKED ISSUE #16620: [AVFoundation] Capitalization mistake in type AVCaptureDeviceFormat
Actual: videoHDRSupportedVideoHDREnabled
Expected: VideoHDRSupported

### PR DESCRIPTION
**Pull request by haritha-mohan**
Fixes #16620

### CODE REVIEW

File: src/avfoundation.cs [hunk 1]
```diff
@@ -11481,7 +11481,14 @@ interface AVCaptureDeviceFormat {
 
 		[iOS (8,0), NoMac]
 		[Export ("videoHDRSupported")]
+		bool VideoHDRSupportedVideoHDREnabled { [Bind ("isVideoHDRSupported")] get; }
```
Comment (dalexsoto) [inline src/avfoundation.cs:11484]: This seems odd, can you doublecheck history / Apple docs and see if the name of the property was done this way on purpose? @mandel-macaque may also have some history heh

I think it should be something like
```suggestion
		[Export ("videoHDRSupported")]
		bool IsVideoHdrSupported { [Bind ("isVideoHDRSupported")] get; }
```

**Review by dalexsoto — CHANGES_REQUESTED** [review]

**Review by rolfbjarne — APPROVED** [review]
Looks good once Alex's comment is addressed!

File: src/avfoundation.cs [hunk 2]
```diff
@@ -11481,7 +11481,14 @@ interface AVCaptureDeviceFormat {
...
+
+#if !XAMCORE_5_0
+		[iOS (8,0), NoMac]
+		[Obsolete ("Use the 'VideoHDRSupportedVideoHDREnabled' property instead.")]
+		[Wrap ("VideoHDRSupportedVideoHDREnabled", IsVirtual = true)]
```
Comment (tj-devel709) [inline src/avfoundation.cs:11489]: Im sure you would have done this anyways, but just a reminder to change the method name in the Wrap if you do Alex's suggestion :)

File: src/avfoundation.cs [hunk 3]
```diff
@@ -11481,7 +11481,14 @@ interface AVCaptureDeviceFormat {
 
 		[iOS (8,0), NoMac]
 		[Export ("videoHDRSupported")]
+		bool VideoHDRSupported { [Bind ("isVideoHDRSupported")] get; }
```
Comment (mandel-macaque) [inline src/avfoundation.cs:11484]:
```suggestion
		bool IsVideoHdrSupported { [Bind ("isVideoHDRSupported")] get; }
```
The rest of the api uses Hrd instead of HRD see the [gist](https://gist.github.com/7f8a4574716529a18aef210129aac106). The also use the verb "Is"

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

**Review by mandel-macaque — APPROVED** [review]
