### PR TITLE
[WebKit] Fix capitalization mistakes in type DomDocument

### LINKED ISSUE #16574: [WebKit] Capitalization issues on type DomDocument
Actual: applets, links, forms, anchors
Expected: Applets, Links, Forms, Anchors

### PR DESCRIPTION
**Pull request by haritha-mohan**
Fixes #16574

### CODE REVIEW

File: src/webkit.cs [hunk 1]
```diff
@@ -708,23 +708,59 @@ partial interface DomDocument {
 		[Export ("cookie", ArgumentSemantic.Copy)]
 		string Cookie { get; set;  }
 
-		[Export ("body", ArgumentSemantic.Retain)]
+#if !XAMCORE_5_0
+		[Obsolete ("Use the 'Body' property instead.")]
+		[Wrap ("Body", IsVirtual = true)]
```
Comment (tj-devel709) [inline src/webkit.cs:713]: Why do these Wraps have the 'IsVirtual = true'? Are they being overridden in the generator?

**Review by tj-devel709 — APPROVED** [review]
LGTM but wait for others' reviews to merge :)

File: src/webkit.cs [hunk 2]
```diff
@@ -708,23 +708,59 @@ partial interface DomDocument {
...
+		DomHtmlCollection Forms { get;  }
+
+#if !XAMCORE_5_0
+		[Obsolete ("Use the 'Anchors' property instead.")]
+		[Wrap ("Anchors", IsVirtual = true)]
 		DomHtmlCollection anchors { get;  }
+#endif
+
+		[Export ("anchors", ArgumentSemantic.Retain)]
+		DomHtmlCollection Anchors { get;  }
```
Comment (rolfbjarne) [inline src/webkit.cs:763]: This is not a big issue at all (no need to change this PR), but I like diffs that show no removed lines (they're much easier to review). This isn't always possible of course, but once in a while it's possible to reorganize the new code so that the resulting diff is easier to read, and I believe this to be one such case.

This is the old code:

```cs
		[Export ("anchors", ArgumentSemantic.Retain)]
		DomHtmlCollection anchors { get;  }
```

and if you did the change like this:

```cs
		[Export ("anchors", ArgumentSemantic.Retain)]
		DomHtmlCollection Anchors { get;  }

#if !XAMCORE_5_0
		[Obsolete ("Use the 'Anchors' property instead.")]
		[Wrap ("Anchors", IsVirtual = true)]
		DomHtmlCollection anchors { get;  }
#endif
```

I believe the diff would only show added lines, hopefully (I haven't tested this, so I might be wrong!) something like this:

```diff
 		[Export ("anchors", ArgumentSemantic.Retain)]
+		DomHtmlCollection Anchors { get;  }
+ 
+ #if !XAMCORE_5_0
+		[Obsolete ("Use the 'Anchors' property instead.")]
+		[Wrap ("Anchors", IsVirtual = true)]
		DomHtmlCollection anchors { get;  }
+#endif
```

In fact the complication of unnecessary removed lines in the diff is showcased very well in this PR, because if you just look at a subset of the diff:

```diff
-		[Export ("images", ArgumentSemantic.Retain)]
+		[Export ("body", ArgumentSemantic.Retain)]
```

You'll see that something doesn't look right ("Why is the selector changing? That's not what this PR is supposed to do!"). You have to study the diff much harder to realize that effectively no selectors are changing.

**Review by rolfbjarne — APPROVED** [review]

File: src/webkit.cs (hunk 1 above)
Comment (haritha-mohan) [reply src/webkit.cs:713]: I had the same question when I began fixing these bugs. Adding the virtual keyword ensures that the api has no breaking changes when these capitalization issues are fixed.

File: src/webkit.cs (hunk 2 above)
Comment (haritha-mohan) [reply src/webkit.cs:763]: Thank you for suggesting this! Even when I was reviewing the diff it was confusing to have the unnecessary changes in the way. I'll keep this in mind for future changes.
