### PR TITLE
[ObjCRuntime] Change Runtime.GetNSObject<T> to create a new instance if the existing one is of the wrong type. Fixes #13704.

### LINKED ISSUE #13704: All empty NSDictionary instances have the same underlying native handle
Example code:

```csharp
var a = new NSDictionary<NSString, NSObject> ();
var b = new NSDictionary<NSString, NSString> ();
var c = new NSDictionary ();
Console.WriteLine ($"a: 0x{a.Handle:X}");
Console.WriteLine ($"b: 0x{b.Handle:X}");
Console.WriteLine ($"c: 0x{c.Handle:X}");
```

prints the same handle for both instances:

```
a: 0x0x7fff80821080
b: 0x0x7fff80821080
c: 0x0x7fff80821080
```

This is unfortunately a problem.

Say you have a type with two properties:

```csharp
NSDictionary<NSString, NSObject> PropertyA { get; set; }
NSDictionary<NSString, NSString> PropertyB { get; set; }
```

and native code has set them both to an empty NSDictionary, then fetching one will make the other break, because this happens:

```
Unable to cast object of type 'Foundation.NSDictionary`2[[Foundation.NSString, Xamarin.MacCatalyst, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065],[Foundation.NSObject, Xamarin.MacCatalyst, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]]' to type 'Foundation.NSDictionary`2[[Foundation.NSString, Xamarin.MacCatalyst, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065],[Foundation.NSString, Xamarin.MacCatalyst, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]]'
```

The generic versions of `NSArray`, `NSSet` and `NSOrderedSet` probably have the same problem.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Objective-C has an optimization where creating an empty dictionary would
return the same instance every time (probably to a constant empty dictionary).

This causes a problem with how we've bound generic dictionaries, because all
empty dictionaries would have the same native handle, even if we'd bound them
with different managed types.

This surfaces in unfortunate ways when we try to look up a managed instance
given a native handle, we find that we already have a managed instance, but
the managed instance is of the wrong type.

Example code:

    var a = new NSDictionary ();
    var b = new NSDictionary<NSString, NSString> ();
    var c = new NSDictionary<NSString, NSObject> ();
    Console.WriteLine ($"a: 0x{a.Handle:X}");
    Console.WriteLine ($"b: 0x{b.Handle:X}");
    Console.WriteLine ($"c: 0x{c.Handle:X}");

would produce something like:

    a: 0x0x7fff80821080
    b: 0x0x7fff80821080
    c: 0x0x7fff80821080

now for this code:

    Runtime.GetNSObject<NSDictionary<NSString, NSString>> (b.Handle)

it would throw an exception like this:

    Unable to cast object of type 'Foundation.NSDictionary`2[[Foundation.NSString],[Foundation.NSObject]]' to type 'Foundation.NSDictionary`2[[Foundation.NSString],[Foundation.NSString]]'

because we'll have the 'c' object (with type `NSDictionary<NSString, Object>`)
in our dictionary of native handles -> managed instances, and that's not
compatible with the desired return type from GetNSObject
(`NSDictionary<NSString, NSString>`)

This likely happens with all the non-mutable collection types we have a
generic version of (NSArray, NSDictionary, NSOrderedSet, NSSet).

Fixes https://github.com/xamarin/xamarin-macios/issues/16378.
Fixes https://github.com/xamarin/xamarin-macios/issues/13704.

This PR is somewhat simpler to review by ignoring whitespace: https://github.com/xamarin/xamarin-macios/pull/16491/files?w=1

### CODE REVIEW

File: src/ObjCRuntime/Runtime.cs [hunk 1]
```diff
@@ -1437,38 +1437,36 @@ static IntPtr CreateNSObject (IntPtr type_gchandle, IntPtr handle, NSObject.Flag
...
-						// If the instance itself claims it's an instance of the provided (generic argument) type,
-						// then we believe the instance. See bug #20692 for a test case.
-						target_type = typeof(T);
-					}
-				} else {
-					target_type = typeof(NSObject);
+
+			// First check if we got an object of the expected type
+			if (obj is T o)
+				return o;
```
Comment (mattleibow) [inline src/ObjCRuntime/Runtime.cs:1443]: Will this cause issue if for example we have an initial type X and then we try get instance of type Y, but Y : X due to inheritance.

I am thinking `NSDictionary<K, V> : NSDictionary`

Comment (rolfbjarne) [reply src/ObjCRuntime/Runtime.cs:1443]: No, if the first instance is `NSDictionary`, and then you want an `NSDictionary<K, V>`, then this check will fail and we'll create a new managed `NSDictionary<K, V>` instance (previously we'd throw an InvalidCastException for this scenario).

For the reverse case, the first instance is `NSDictionary<K, V>` and you want an `NSDictionary`, you'll get the `NSDictionary<K, V>` instance (it was this way before this PR, and will be after too).

**Review by dalexsoto — APPROVED** [review]

**Comment by Therzok** [comment]
Related? https://github.com/xamarin/xamarin-macios/issues/5325#issuecomment-453250998

**Comment by rolfbjarne** [comment]
@Therzok 

> Related? [#5325 (comment)](https://github.com/xamarin/xamarin-macios/issues/5325#issuecomment-453250998)

Yes, probably.
