### PR TITLE
[UIKit] Fix broken UITrait bindings. Fixes #19410.

### LINKED ISSUE #19410: No Replacement for deprecated TraitCollectionDidChange
I was using [traitcollectiondidchange](https://developer.apple.com/documentation/uikit/uitraitenvironment/1623516-traitcollectiondidchange) to detect changes of the dark/light theme. That method has been deprecated with iOS 17

Screenshot 2023-11-08 at 1 27 24 PM

The suggested alternative by Apple is [registerfortraitchanges](https://developer.apple.com/documentation/uikit/uitraitchangeobservable/4138524-registerfortraitchanges), which can be called on objects that implement `UITraitChangeObservable` (`IUITraitChangeObservable` interface in C#). `UIView` and `UIViewController` seem to implement that interface, but this isn't reflected in the C# bindings - the method RegisterForTraitChanges doesn't exist for `UIView` and `UIViewController`. How can I use this new API in .NET?

Screenshot 2023-11-08 at 1 25 32 PM

### Environment
.NET 8 RC2.2

### PR DESCRIPTION
**Pull request by rolfbjarne**
There are a few issues with the bindings, because the typedef `UITrait` in the headers is defined like this:

```objective-c
typedef Class<UITraitDefinition> UITrait
```

which means: "A Class that implements the UITraitDefinition protocol", and not "The UITraitDefinition" protocol", which is how it was bound.

This means the corresponding bindings are incorrect, so fix them. In some cases it's not possible to fix the API, so new ones had to be implemented in order to maintain backwards compatibility.

Fixes https://github.com/xamarin/xamarin-macios/issues/19410.

### CODE REVIEW

**Review by stephen-hawley — APPROVED** [review]

**Comment by mandel-macaque** [comment]
@rolfbjarne  this has been broken since 2019? Ugh.. I guess we only got the report due to the warning.

**Comment by rolfbjarne** [comment]
> @rolfbjarne this has been broken since 2019? Ugh.. I guess we only got the report due to the warning.

No, this is new APIs in Xcode 15.

Also this is a draft PR, so not ready to review yet :)

File: src/UIKit/UITraitChangeObservable.cs [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+		}
+
+
+#if !XAMCORE_5_0
+		[BindingImpl (BindingImplOptions.Optimizable)]
+#if !NET
+		public IUITraitChangeRegistration RegisterForTraitChanges (Class [] traits, global::System.Action<IUITraitEnvironment, UITraitCollection> handler)
+		{
+			// The manual block code is somewhat annoying to implement, so at least don't do it twice (once for .NET and once for legacy Xamarin) unless we really need to.
+			throw new NotImplementedException ("This API has not been implemented for legacy Xamarin. Please upgrade to .NET");
```
Comment (mandel-macaque) [inline src/UIKit/UITraitChangeObservable.cs:150]: Do we want this translated? Specially when it tells to upgrade.

**Review by mandel-macaque — APPROVED** [review]

File: src/UIKit/UITraitChangeObservable.cs (hunk 1 above)
Comment (rolfbjarne) [reply src/UIKit/UITraitChangeObservable.cs:150]: We don't translate anything else in our platform assemblies, so we'd first have to implement that part (which isn't trivial - we'd even have to figure out how to ship translations), and if we do this, it should be implemented in a separate PR.
