### PR TITLE
Avoid ObjCRuntime. Runtime.GetDelegateForBlock race condition.

### LINKED ISSUE #8431: ObjCRuntime. Runtime.GetDelegateForBlock race condition crash
Looks like race condition in following lines causes app to crash.
That is possible to initialize `block_to_delegate_cache` with multiple instances, so subsequent `locks` do not work. 

https://github.com/xamarin/xamarin-macios/blob/39629ab93b8d723b472a52378615dc5cf03553bd/src/ObjCRuntime/Runtime.cs#L947-L948

### Actual Behavior
App crashes
```
Exception Type:  SIGABRT
Exception Codes: #0 at 0x18566eefc
Crashed Thread:  4

Application Specific Information:
*** Terminating app due to uncaught exception 'SIGABRT', reason: 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'

Xamarin Exception Stack:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
--- End of inner exception stack trace ---
  System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) <0x103ae5690 + 0x00983> 7515 in <91e0283eca55453fa9b161bf2de4edfd#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) <0x103ae24b0 + 0x0002f> 7450 in <91e0283eca55453fa9b161bf2de4edfd#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at ObjCRuntime.Runtime.GetDelegateForBlock (System.IntPtr methodPtr, System.Type type) <0x103a10a10 + 0x00207> in <8f1cf8fa8604454db31e175df104baa7#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at ObjCRuntime.BlockLiteral.GetDelegateForBlock[T] () <0x103a17be0 + 0x0002f> in <8f1cf8fa8604454db31e175df104baa7#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at ObjCRuntime.Trampolines+NIDActionArity1V46..ctor (ObjCRuntime.BlockLiteral* block) <0x103a1c350 + 0x00037> in <8f1cf8fa8604454db31e175df104baa7#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at ObjCRuntime.Trampolines+NIDActionArity1V46.Create (System.IntPtr block) <0x103a1c420 + 0x000b7> in <8f1cf8fa8604454db31e175df104baa7#d36f08c2c51a2a2f7f0de782858c2f99>:0
    at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
    at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x10320b440 + 0x000a7> in <91e0283eca55453fa9b161bf2de4edfd#d36f08c2c51a2a2f7f0de782858c2f99>:0

Thread 4 Crashed:
0   libsystem_kernel.dylib               0x000000018566eefc __pthread_kill + 8
1   libsystem_c.dylib                    0x000000018551ea74 abort + 100
2   <.....>                              0x0000000104de10a4 xamarin_unhandled_exception_handler (runtime.m:1175)
3   <.....>                              0x0000000104cd5760 mono_invoke_unhandled_exception_hook (exception.c:1248)
4   <.....>                              0x0000000104c6b8a4 mono_handle_exception_internal (mini-exceptions.c:2602)
5   <.....>                              0x0000000104c6a3c0 mono_handle_exception (mini-exceptions.c:2917)
6   <.....>                              0x0000000104c60884 mono_arm_throw_exception (exceptions-arm64.c:410)
7   <.....>                              0x00000001033be248 throw_exception + 164
8   <.....>                              0x0000000104d2c560 mono_raise_exception (object.c:7818)
9   <.....>                              0x0000000104de0e80 xamarin_process_managed_exception (runtime.m:2434)
10  <.....>                              0x0000000102b09614 native_to_managed_trampoline_197(objc_object*, objc_selector*, _MonoMethod**, NSURLSession*, NSURLSessionDataTask*, NSURLResponse*, objc_object*, unsigned int) (registrar.m:9943)
11  <.....>                              0x0000000102b09334 -[System_Net_Http_NSUrlSessionHandler_NSUrlSessionHandlerDelegate URLSession:dataTask:didReceiveResponse:completionHandler:] (registrar.m:42751)
12  CFNetwork                            0x0000000188cb7dd0 _CFNetworkHTTPConnectionCacheSetLimit + 195104
13  Foundation                           0x0000000185c549d4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 20
14  Foundation                           0x0000000185b564a8 -[NSBlockOperation main] + 100
15  Foundation                           0x0000000185c56d30 __NSOPERATION_IS_INVOKING_MAIN__ + 20
16  Foundation                           0x0000000185b56124 -[NSOperation start] + 736
17  Foundation                           0x0000000185c5775c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
18  Foundation                           0x0000000185c5721c __NSOQSchedule_f + 180
19  libdispatch.dylib                    0x000000018553639c _dispatch_block_async_invoke2 + 140
20  libdispatch.dylib                    0x0000000185529fd8 _dispatch_client_callout + 16
21  libdispatch.dylib                    0x000000018552c758 _dispatch_continuation_pop + 404
22  libdispatch.dylib                    0x000000018552beb8 _dispatch_async_redirect_invoke + 592
23  libdispatch.dylib                    0x0000000185538bd4 _dispatch_root_queue_drain + 344
24  libdispatch.dylib                    0x0000000185539384 _dispatch_worker_thread2 + 116
25  libsystem_pthread.dylib              0x000000018558f690 _pthread_wqthread + 212
26  libsystem_pthread.dylib              0x00000001855959e8 start_wqthread + 4
```

### PR DESCRIPTION
**Pull request by yaliashkevich**
Fixes #8431

### CODE REVIEW

**Comment by chamons** [comment]
@yaliashkevich - Thanks for the clear issue and PR!

Would you be interested in reworking the PR as @rolfbjarne suggests to reduce memory usage, or should we assign the rework to someone here at Xamarin?

**Comment by yaliashkevich** [comment]
@rolfbjarne, I think that using `lock_obj` for other locks  may potentially increase number of threads (time spent) being blocked while acquiring the lock. Probably it's better to keep things separated by using different lock objects.

File: src/ObjCRuntime/Runtime.cs [hunk 1]
```diff
@@ -944,8 +944,12 @@ static Delegate CreateBlockProxy (MethodInfo method, IntPtr block)
...
-			if (block_to_delegate_cache == null)
-				block_to_delegate_cache = new Dictionary<IntPtrTypeValueTuple, Delegate> ();
+			if (block_to_delegate_cache == null) {
+				lock (lock_obj) {
+					if (block_to_delegate_cache == null)
+						block_to_delegate_cache = new Dictionary<IntPtrTypeValueTuple, Delegate> ();
+				}
+			}
 
 			// We do not care if there is a race condition and we initialize two caches
```
Comment (rolfbjarne) [inline src/ObjCRuntime/Runtime.cs:954]: This comment is not accurate anymore, and should be removed.

Comment (yaliashkevich) [reply src/ObjCRuntime/Runtime.cs:954]: Looks like the comment is about this line, so it is still accurate.
https://github.com/xamarin/xamarin-macios/blob/70ef53f5c5f26ee2d8cff84870f42ec9db6a69e6/src/ObjCRuntime/Runtime.cs#L964

Comment (rolfbjarne) [reply src/ObjCRuntime/Runtime.cs:947]: Interesting how we understood the comment differently :smile:

My take is that the code was referring to the fact that the `block_to_delegate_cache` creation was not synchronized ("we initialize two _caches_"), so that there could end up being multiple instances of the `block_to_delegate_cache` dictionary, and that all but one would eventually end up discarded (and then it turned out that this wasn't safe, as you found out).

However, the comment is still accurate about the fact that we may end up calling `Marshal.GetDelegateForFunctionPointer` multiple times for the same method pointer (which is fine).

**Comment by rolfbjarne** [comment]
build
