### PR TITLE
[Tests] Ensure that tests do not fail due to the locale. Fixes #3445

### LINKED ISSUE #3445: PassTest.BoardingPass : LocalizedName fails on iPad Air 2 device iOS 11.2
### Steps to Reproduce

1. make run-ios-dev64-monotouch-tests using an  iPad Air 2 with iOS 11.2 Build version 15C5092b 

### Expected Behavior

All tests pass.

### Actual Behavior

[FAIL] PassTest.BoardingPass : LocalizedName

### Environment

Failure occurs in

master: https://github.com/xamarin/xamarin-macios/commit/6f59487700ec9af031e2940209bdd4d803cf9286
d15-6: https://github.com/xamarin/xamarin-macios/commit/1c6f300ef26ff1fb06965a8accae473eb5f96ec3

### PR DESCRIPTION
**Pull request by mandel-macaque**
Previous tests would fail if the simulator or device was using a diff locale.

### CODE REVIEW

File: tests/monotouch-test/PassKit/PassTest.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ public void Defaults ()
 				Assert.NotNull (pass.Icon, "Icon");
 #endif
 				Assert.Null (pass.LocalizedDescription, "LocalizedDescription");
-				Assert.That (pass.LocalizedName, Is.EqualTo ("Coupon"), "LocalizedName");
+				Assert.That (string.IsNullOrEmpty (pass.LocalizedName), Is.False, "LocalizedName");
```
Comment (spouliot) [inline tests/monotouch-test/PassKit/PassTest.cs]: minor (no need to change it) but there's a simpler way
```
Assert.NotNull (pass.LocalizedName, "LocalizedName");
```

Comment (mandel-macaque) [reply tests/monotouch-test/PassKit/PassTest.cs]: Yes, but I was thinking, is this ever going to be "" ever? That might seem strange for the API user, and I did not want us doing something wrong, returning "" and end up with issues. (mainly, "I don't want me changing this ever to do something stupid" ;) )
