### PR TITLE
[xtro] Report incorrect 'ArgumentSemantic' enum value usage

### LINKED ISSUE #4018: [xtro] Report incorrect 'ArgumentSemantic' enum value usage
Xtro should report incorrect 'ArgumentSemantic' enum value usage.

E.g: ClassKit in Xcode 9.4 beta 2 had a bunch of:

``` Diff
-@property (nullable, nonatomic) __kindof CLSActivityItem *primaryActivityItem;
+@property (nullable, nonatomic, strong) __kindof CLSActivityItem *primaryActivityItem;
```

It'd be very helpful if Xtro reported those.

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes #4018: [xtro] Report incorrect 'ArgumentSemantic' enum value usage
  (https://github.com/xamarin/xamarin-macios/issues/4018).

### CODE REVIEW

**Comment by VincentDondain** [comment]
Time of `SelectorCheck` with new test:

```
Extrospection.SelectorCheck: Elapsed=00:00:02.0330457
Extrospection.SelectorCheck: Elapsed=00:00:05.7196766
Extrospection.SelectorCheck: Elapsed=00:00:10.8809971
Extrospection.SelectorCheck: Elapsed=00:00:14.4416889
```

(x4 because ran on 4 platforms)

Before:
```
Extrospection.SelectorCheck: Elapsed=00:00:00.5158108
Extrospection.SelectorCheck: Elapsed=00:00:00.8786211
Extrospection.SelectorCheck: Elapsed=00:00:01.0491429
Extrospection.SelectorCheck: Elapsed=00:00:01.2374137
```

Now I realize moving to `LINQ` might not have been such a good idea (will investigate) (:

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 1]
```diff
@@ -4,38 +4,20 @@
...
-
-		// duplicate
-		//	-> the selector is defined more than once for the same type
 
-		HashSet<string> known_selectors = new HashSet<string> ();
-
-		HashSet<string> qualified_selectors = new HashSet<string> ();
-
-		//Dictionary<TypeDefinition,HashSet<string>> type_exports = new Dictionary<TypeDefinition,HashSet<string>> ();
+		HashSet<(string MethodDefinition, Helpers.ArgumentSemantic ArgumentSemantic)> qualified_export_arguments = new HashSet<(string, Helpers.ArgumentSemantic)> ();
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: you're now allocating a tuple for each entry - even if only properties actually needs the extra argument semantics

Comment (spouliot) [reply tests/xtro-sharpie/SelectorCheck.cs]: depending on the numbers it might be cheaper to have a dictionary where you store argument semantics (and only when available) along with the `MethodDefinition`

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 2]
```diff
@@ -51,24 +33,53 @@ public override void VisitManagedMethod (MethodDefinition method)
...
+			// Ignore Copy, UnsafeUnretained and Weak for now
+			if (nativeArgumentSemantic == Helpers.ArgumentSemantic.Copy || nativeArgumentSemantic == Helpers.ArgumentSemantic.UnsafeUnretained || nativeArgumentSemantic == Helpers.ArgumentSemantic.Weak)
+				return;
+
+			var nativeMethodDefinition = decl.QualifiedName;
+
+			var exportArgs = qualified_export_arguments.FirstOrDefault (sel => sel.MethodDefinition.Contains (nativeMethodDefinition));
+
+			if (!string.IsNullOrEmpty (exportArgs.MethodDefinition) && exportArgs.ArgumentSemantic != nativeArgumentSemantic)
+				Log.On (framework).Add ($"!incorrect-argument-semantic! {nativeMethodDefinition} has ArgumentSemantic.{nativeArgumentSemantic.ToUsableString ()} instead of ArgumentSemantic.{exportArgs.ArgumentSemantic.ToUsableString ()}");
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]:
```
!incorrect-argument-semantic! SKUniform::textureValue has ArgumentSemantic.Strong|Retain instead of ArgumentSemantic.None
```
it's a bit confusing when reading (without our bindings sources or xtro sources). 

Either (best) you use the `ArgumentSemantic` for the managed version and the ObjC syntax (for clang/headers); or you mention which one is managed and native.

File: tests/xtro-sharpie/SelectorCheck.cs (hunk 1 above)
Comment (rolfbjarne) [reply tests/xtro-sharpie/SelectorCheck.cs]: Can't this be `Dictionary<string, ArgumentSemantic>`? Or can you have multiple methods with the same name, but different argument semantics?

That would mean any lookup would be a hashed lookup, and not a sequential lookup.

File: tests/xtro-sharpie/SelectorCheck.cs (hunk 2 above)
Comment (VincentDondain) [reply tests/xtro-sharpie/SelectorCheck.cs]: @spouliot `!incorrect-argument-semantic! 'SKUniform::textureValue' (native) has (strong|retain) instead of 'ArgumentSemantic.None'`?

Comment (spouliot) [reply tests/xtro-sharpie/SelectorCheck.cs]: @VincentDondain yes, that would remove the ambiguity :)

**Comment by VincentDondain** [comment]
**UPDATED**

Time of SelectorCheck with **new** test:

```
Extrospection.SelectorCheck: Elapsed=00:00:00.7263742
Extrospection.SelectorCheck: Elapsed=00:00:01.2136911
Extrospection.SelectorCheck: Elapsed=00:00:01.2747602
Extrospection.SelectorCheck: Elapsed=00:00:01.7494063
```
(x4 because ran on 4 platforms)

Before:

```
Extrospection.SelectorCheck: Elapsed=00:00:00.5158108
Extrospection.SelectorCheck: Elapsed=00:00:00.8786211
Extrospection.SelectorCheck: Elapsed=00:00:01.0491429
Extrospection.SelectorCheck: Elapsed=00:00:01.2374137
```

It is now only _slightly slower_ but I think that's acceptable (:

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 3]
```diff
@@ -4,38 +4,21 @@
...
-//             if we have a selector that is not part of the header files
-//
 
 using System;
 using System.Collections.Generic;
 
 using Mono.Cecil;
 
 using Clang.Ast;
+using System.Linq;
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: are you still using any linq ?

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 4]
```diff
@@ -51,24 +34,49 @@ public override void VisitManagedMethod (MethodDefinition method)
...
+
+			// Ignore Copy, UnsafeUnretained and Weak for now
+			if (nativeArgumentSemantic == Helpers.ArgumentSemantic.Copy || nativeArgumentSemantic == Helpers.ArgumentSemantic.UnsafeUnretained || nativeArgumentSemantic == Helpers.ArgumentSemantic.Weak)
+				return;
+
+			var nativeMethodDefinition = decl.QualifiedName;
+
+			bool found = qualified_properties.TryGetValue (nativeMethodDefinition, out var managedArgumentSemantic);
+			if (found && managedArgumentSemantic != nativeArgumentSemantic)
+				Log.On (framework).Add ($"!incorrect-argument-semantic! '{nativeMethodDefinition}' (native) has ({nativeArgumentSemantic.ToUsableString ().ToLower ()}) instead of 'ArgumentSemantic.{managedArgumentSemantic.ToUsableString ()}'");
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: use `ToLowerInvariant`

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 5]
```diff
@@ -97,6 +105,7 @@ public override void VisitObjCMethodDecl (ObjCMethodDecl decl, VisitKind visitKi
 					return;
 				name = "+" + name;
 			}
+
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: minor: noise

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 6]
```diff
@@ -51,24 +34,49 @@ public override void VisitManagedMethod (MethodDefinition method)
...
+			if (!decl.IsAvailable ())
+				return;
+
+			var framework = Helpers.GetFramework (decl);
+			if (framework == null)
+				return;
+
+			var nativeArgumentSemantic = decl.Attributes.ToArgumentSemantic ();
+
+			// Ignore Copy, UnsafeUnretained and Weak for now
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: why ?

File: tests/xtro-sharpie/SelectorCheck.cs [hunk 7]
```diff
@@ -51,24 +34,49 @@ public override void VisitManagedMethod (MethodDefinition method)
 			foreach (var ca in method.CustomAttributes) {
 				switch (ca.Constructor.DeclaringType.Name) {
 				case "ExportAttribute":
-					string selector = ca.ConstructorArguments [0].Value as string;
-					if (!known_selectors.Contains (selector))
-						known_selectors.Add (selector);
+					var methodDefinition = method.GetName ();
+					if (!string.IsNullOrEmpty (methodDefinition)) {
+						var argumentSemantic = Helpers.ArgumentSemantic.None;
```
Comment (spouliot) [inline tests/xtro-sharpie/SelectorCheck.cs]: `None` is not a value - it means the default (pre-ARC it's `Assign`)
The comparison you make later might not be correct.

Comment (spouliot) [reply tests/xtro-sharpie/SelectorCheck.cs]: Here's an example
```
!incorrect-argument-semantic! 'CNContainer::type' (native) has (none) instead of 'ArgumentSemantic.UnsafeUnretained|Assign'
```
and the default (when nothing is specified) is `assign` - that's a false positive.

**Comment by spouliot** [comment]
```
!incorrect-argument-semantic! 'AVRoutePickerView::activeTintColor' (native) has (strong|retain) instead of 'ArgumentSemantic.UnsafeUnretained|Assign'
```

Might just be me but the `instead of` is confusing, since it sounds like the managed version is right - while it's the native one that we can't change. What about:

```
'X' (native) is declared as (Y) but mapped to 'Z' (managed).
```

**Comment by spouliot** [comment]
Not sure if it's worth cleaning up `weak` vs `ArgumentSemantic.UnsafeUnretained|Assign` since it's close and IIRC we don't care. It's nicer (and less confusing) to have matching declarations, but it's noisy to update (for future merges, e.g. xcode10.2 on 15.9).

@rolfbjarne can you look at the xtro results ? thanks!

**Comment by rolfbjarne** [comment]
The results look correct to me from what I can see.

What we really care about is if native code uses 'copy', and our binding don't match (we can end up with invalid pointers). The reverse has a performance hit (if we declare something as 'ArgumentSemantic.Copy', while native doesn't), because we'd copy values when not needed, but _in theory_ it shouldn't cause trouble.

I think we should fix any mismatched 'copy' semantics, and the rest can ignore and/or delay until sometime later to fix.

**Comment by rolfbjarne** [comment]
@VincentDondain correct.

**Comment by spouliot** [comment]
@VincentDondain add a comment `FIXME: only Copy mistakes are reported now` and the related logic. That will tell us how many fixes are needed. You can run it locally (and report the numbers here), no need to push that yet.

Next disable the rule (so it does not report anything) and we can merge it into `master` (along with above changes).

Finally we'll back port the commit to `xcode10.2` (once we create it - and we can do it earlier than Apple) and have it fixed there to avoid merge conflicts (since doing large binding changes in `master`, while `xcode10.2` will be based on `d15-9` will likely be painful). It also means the fixes will become available sooner (than `d16-0`).

**Comment by VincentDondain** [comment]
The result is 142 `!incorrect-argument-semantic!` found.

[report.zip](https://github.com/xamarin/xamarin-macios/files/2625650/report.zip)

**Comment by rolfbjarne** [comment]
build
