### PR TITLE
[mtouch/mmp] Only use stdout from xcrun as the path of the file that was found. Fixes #8147.

### LINKED ISSUE #8147: [tvos] MT0000 running install_name_tool
> 76 tests failed, 74 tests passed.

Many failures, yet some worked :|

Works locally :(

```
01:09:22.1725810 MTOUCH : error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new [/Users/xamarinqa/agent/_work/11/s/tests/xharness/tmp-test-dir/monotouch-test2411/monotouch-test-tvos.csproj]
01:09:22.1729550   System.ComponentModel.Win32Exception (0x80004005): ApplicationName='xcrun: error: unable to read SDK settings for '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' (TaskId:415)
01:09:22.1731870   /Applications/Xcode113.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool (TaskId:415)
01:09:22.1735680 xcrun : error : unable to read SDK settings for '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'', CommandLine='-change /System/Library/PrivateFrameworks/IOSurface.framework/IOSurface /System/Library/Frameworks/IOSurface.framework/IOSurface /Users/xamarinqa/agent/_work/11/s/tests/xharness/tmp-test-dir/monotouch-test2411/obj/iPhone/Debug-tvos/mtouch-cache/arm64/monotouchtest', CurrentDirectory='', Native error= Cannot find the specified file [/Users/xamarinqa/agent/_work/11/s/tests/xharness/tmp-test-dir/monotouch-test2411/monotouch-test-tvos.csproj]
01:09:22.1736760     at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/mcs/class/System/System.Diagnostics/Process.cs:778  (TaskId:415)
01:09:22.1738010     at System.Diagnostics.Process.Start () [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2006  (TaskId:415)
01:09:22.1739200     at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start() (TaskId:415)
01:09:22.1740810     at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2490  (TaskId:415)
01:09:22.1760000     at Xamarin.Bundler.Driver.RunCommand (System.String path, System.String args, System.String[] env, System.Action`1[T] output_received, System.Boolean suppressPrintOnErrors) [0x00122] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Driver.cs:346  (TaskId:415)
01:09:22.1777690     at Xamarin.Bundler.Driver.RunCommand (System.String path, System.Collections.Generic.IList`1[T] args, System.String[] env, System.Action`1[T] output_received, System.Boolean suppressPrintOnErrors) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Driver.cs:307  (TaskId:415)
01:09:22.1779310     at Xamarin.Bundler.Driver.RunCommand (System.String path, System.Collections.Generic.IList`1[T] args) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Driver.cs:295  (TaskId:415)
01:09:22.1780080     at Xamarin.Bundler.Driver.RunXcodeTool (System.String tool, System.Collections.Generic.IList`1[T] arguments) [0x00008] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Driver.cs:897  (TaskId:415)
01:09:22.1781020     at Xamarin.Bundler.Driver.RunInstallNameTool (System.Collections.Generic.IList`1[T] arguments) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/Driver.cs:909  (TaskId:415)
01:09:22.1781790     at Xamarin.Bundler.Target.AdjustDylibs (System.String output) [0x00090] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:1719  (TaskId:415)
01:09:22.1783160     at Xamarin.Bundler.NativeLinkTask.ExecuteAsync () [0x004c0] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/BuildTasks.mtouch.cs:362  (TaskId:415)
01:09:22.1784280     at Xamarin.Bundler.BuildTask.Execute (Xamarin.Bundler.BuildTasks build_tasks) [0x002a9] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/BuildTasks.cs:259  (TaskId:415)
01:09:22.1786560     at Xamarin.Bundler.BuildTask.Execute (Xamarin.Bundler.BuildTasks build_tasks) [0x0038c] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/BuildTasks.cs:274  (TaskId:415)
01:09:22.1787060     at Xamarin.Bundler.BuildTask.Execute (Xamarin.Bundler.BuildTasks build_tasks) [0x00368] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/BuildTasks.cs:270  (TaskId:415)
01:09:22.1788050     at Xamarin.Bundler.BuildTasks+<>c__DisplayClass4_0.<ExecuteBuildTasks>b__0 () [0x0002e] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/BuildTasks.cs:50  (TaskId:415)
```

https://github.com/xamarin/xamarin-macios/commit/ba088b3f97d10f3335ba06e2ced89dd0f05a2e6a

### Expected Behavior

No error - or at least a better one than MT0000

### Actual Behavior

_Random_ MT0000

### Environment

master

### PR DESCRIPTION
**Pull request by rolfbjarne**
xcrun can print stuff to stderr even if it succeeds and prints what it found
to stdout, which means we have to separate stdout and stderr when capturing
xcrun's output.

This also means that we need a few changes to our RunCommand API:

* Add support for capturing stdout and stderr separately by providing
  different callbacks/StringBuilder instances.
* Use overloads instead of default arguments, because with default arguments
  we end up with ambiguous matches in a lot of places with the new overloads.

Fixes https://github.com/xamarin/xamarin-macios/issues/8147.

### CODE REVIEW

File: tools/common/Driver.cs [hunk 1]
```diff
@@ -967,13 +1011,31 @@ static bool XcrunFind (ApplePlatform platform, bool is_simulator, string tool, o
...
+				(v) => {
+					lock (both) {
+						both.AppendLine (v);
+						stderr.AppendLine (v);
+					}
+				});
 
 			if (ret == 0) {
-				path = output.ToString ().Trim ();
+				path = stdout.ToString ().Trim ();
```
Comment (spouliot) [inline tools/common/Driver.cs]: `path` is still not validated
and that it could point to something that does not exists or is not accessible, e.g. permissions
and that we will issue an `MT0000` instead of a proper error with useful diagnostic information

Comment (rolfbjarne) [reply tools/common/Driver.cs]: I can add that in a separate PR, this should really get into our xcode11.4 support branch asap, since it's shipping pretty soon.

**Comment by rolfbjarne** [comment]
The original issue does not show up in the device tests anymore, so disable those now.

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-5-xcode11.4
@monojenkins backport d16-6-xcode11.4
