### PR TITLE
[dotnet] Fix non-bundling of debug files for release builds. Fixes #14085.

### LINKED ISSUE #14085: [net][msbuild] Release builds include `.pdb` inside the app bundle
Debugging symbols `.pdb` files are included inside the `.app` in release mode.

This is a regression from earlier previews.

# Steps

1. `cd tests/dotnet`
2. `make compare`
3. open the gist

## Example

https://gist.github.com/spouliot/2d707626fdc962a76eeafa145af79b64

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/14085.

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

File: tests/dotnet/UnitTests/TestBaseClass.cs [hunk 1]
```diff
@@ -275,5 +275,22 @@ protected void ExecuteWithMagicWordAndAssert (string executable)
...
 		}
+
+		public static StringBuilder AssertExecute (string executable, params string[] arguments)
+		{
+			return AssertExecute (executable, arguments, out _);
+		}
+
+		public static StringBuilder AssertExecute (string executable, string[] arguments, out StringBuilder output)
+		{
+
```
Comment (chamons) [inline tests/dotnet/UnitTests/TestBaseClass.cs:286]: super nit: Extra newline

**Review by chamons — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/581).

**Review by emaf — APPROVED** [review]
