### PR TITLE
[foundation] Fix inlined 'NSUserActivity (IntentsAdditions)' to work if nothing else from Intents is used. Fixes #4894

### LINKED ISSUE #4894: NSUserActivity.SuggestedInvocationPhrase unrecognized selector
### Steps to Reproduce

1. Create a WatchOS app and in the interface controller update the user activity:
``` c#
          var activity = new NSUserActivity("com.atadore.AppleWatchAlexa.watchkitapp.invokeAlexa") {
            Title = "Voice in a Can",
            EligibleForPrediction = true,
            SuggestedInvocationPhrase = "Jarvis"
          };
          UpdateUserActivity(activity);
```
2. Run on a real device running WatchOS 5 (production release)

### Expected Behavior
No error

### Actual Behavior
ERROR SpeechRecognizer InitiateRecognize Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[NSUserActivity setSuggestedInvocationPhrase:]: unrecognized selector sent to instance 0x19cb3f00
```
Native stack trace:
	0   CoreFoundation                      0x1c858bcd <redacted> + 256
	1   libobjc.A.dylib                     0x1bb81851 objc_exception_throw + 38
	2   CoreFoundation                      0x1c7a1f95 <redacted> + 0
	3   CoreFoundation                      0x1c85d415 <redacted> + 1150
	4   CoreFoundation                      0x1c85e8b0 _CF_forwarding_prep_0 + 32
	5   libpinvokes.dylib                   0x0035ce85 xamarin_pinvoke_wrapper_void_objc_msgSend_IntPtr + 22
	6   libXamarin.WatchOS.dll.dylib        0x0233d498 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_IntPtr_intptr_intptr_intptr + 140
	7   libXamarin.WatchOS.dll.dylib        0x0230836c Foundation_NSUserActivity_set_SuggestedInvocationPhrase_string + 128
	8   libAppleWatchAlexaWatchOSAppExtension.dll.dylib 0x00580674 VoiceInACan_AppleShared_WatchOSAppExtension_InterfaceController_DrawAlexaAnimations + 6236
	9   libXamarin.WatchOS.dll.dylib        0x022fbcf8 Foundation_NSActionDispatcher_Apply + 92
	10  libmscorlib.dll.dylib               0x009e6790 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 308
```

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.7 (build 49)
Installation UUID: e2bf6735-5ded-4eb1-b901-9d8099d9d7bb
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/damian/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706070049
Git revision: 0b48ccfb376397678b3bc3653da2c6603d35357d
Build date: 2018-09-20 21:14:23+00
Build branch: release-7.6
Xamarin extensions: b25fd1e2b9a7859aff9536924e8edb6cbfb78637

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

```

### PR DESCRIPTION
**Pull request by spouliot**
The selectors `suggestedInvocationPhrase` and `setSuggestedInvocationPhrase`
needs Intents.framework to be loaded into memory. Otherwise an exception
occurs:

```
Objective-C exception thrown. Name: NSInvalidArgumentException Reason: -[NSUserActivity setSuggestedInvocationPhrase:]: unrecognized selector sent to instance 0x19cb3f00
```

When the linker is enabled there's no clue (e.g. namespaces from
preserved types) that `Intents` is required to call the property.

The fix is to provide an hint that will force the linker to keep a type
(a small enum available in all platforms in this case) which tells
`mtouch` (based on the type's namespace) to instruct the native linker
(Apple's `ld`) to [weak]link the Intents.framework in the application
executable.

Note: other selections from the category works fine.

reference:
https://github.com/xamarin/xamarin-macios/issues/4894

### CODE REVIEW

File: src/foundation.cs [hunk 1]
```diff
@@ -5209,7 +5209,16 @@ partial interface NSUserActivity {
 
 		[Watch (5,0), NoTV, NoMac, iOS (12,0)]
 		[NullAllowed, Export ("suggestedInvocationPhrase")]
-		string SuggestedInvocationPhrase { get; set; }
+		string SuggestedInvocationPhrase {
+			// This _simply_ ensure that the Intents namespace (via the enum) will be present which,
```
Comment (stephen-hawley) [inline src/foundation.cs]: minor: This _simply_ ensures
