### PR TITLE
[generator] Warn if [NullAllowed] is used on methods. Fixes #4416

### LINKED ISSUE #4416: libxammac.dylib missing when performing dllimport call
Hello!

I'm currently attempting to add macOS support to LibVLCSharp (libvlc binding for xamarin). After some issues regarding the packaging/bundling of dylibs, I managed to copy them all in the final .app bundle. My next (and hopefully final) issue to get this working is making the `DllImport` calls work.

### Steps to Reproduce

1. Generate package from https://github.com/mfkl/libvlc-nuget/pull/5 (not on nuget yet)
2. Add it to a Xamarin.Mac project
3. Try loading the dylib at runtime and P/Invoking into it (CLI launch for interesting debug logs).

### Expected Behavior
Can perform P/Invoke calls on a dylib after loading it with `ObjCRuntime.Dlfcn.dlopen`
### Actual Behavior
Calling `dlopen` on them before 
```
 NSApplication.Init();
 NSApplication.Main(args);
```
does a return a not null pointer, but dllimport calls fail with
```
Unhandled Exception:
System.DllNotFoundException: Could not find the runtime library libxammac.dylib
  at ObjCRuntime.Runtime.LookupInternalFunction[T] (System.String name) [0x0010a] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.1.193/src/Xamarin.Mac/ObjCRuntime/Runtime.mac.cs:107
  at ObjCRuntime.Runtime.EnsureInitialized () [0x00030] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.1.193/src/Xamarin.Mac/ObjCRuntime/Runtime.mac.cs:117
  at AppKit.NSApplication.Init () [0x00016] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.1.193/src/Xamarin.Mac/AppKit/NSApplication.cs:56
``` 

I have a dllMap file if that matters
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <dllmap dll="libvlc" target="@executable_path/lib/libvlc.5.dylib"/>
</configuration>
```
### Environment

```
Visual Studio Community 2017 for Mac
Version 7.5.3 (build 7)
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)
```

I could bundle the `libxammac.dylib` in my .app bundle but... that does not feel right at all (and crashes for another reason, anyway). 

Any help or insights greatly appreciated.

### PR DESCRIPTION
**Pull request by spouliot**
The `[NullAllowed]` attribute should not be allowed on methods but it could
break existing binding projects.

Historically it was used on property setters. However using the attribute
on _other_ methods can be misleading, e.g. should it apply to all
parameters, the return value... and its presence/action can be
misinterpreted in code reviews leading to binding bugs.

reference: https://github.com/xamarin/xamarin-macios/issues/5416

### CODE REVIEW

File: src/generator.cs [hunk 1]
```diff
@@ -4096,6 +4096,9 @@ void GenerateArgumentChecks (MethodInfo mi, bool null_allowed_override, Property
 		if (null_allowed_override)
 			return;
 
+		if (AttributeManager.HasAttribute<NullAllowedAttribute> (mi))
+			ErrorHelper.Show (new BindingException (1118, false, $"[NullAllowed] should not be used on methods, like '{mi}', but only on properties, parameters and return values."));
```
Comment (rolfbjarne) [inline src/generator.cs]: Using `ErrorHelper.Warning` makes it clearer that this is a warning.

File: src/generator.cs [hunk 2]
```diff
@@ -4808,7 +4811,10 @@ void GenerateProperty (Type type, PropertyInfo pi, List<string> instance_fields_
 		if (pi.CanWrite){
 			var setter = pi.GetSetMethod ();
 			var ba = GetBindAttribute (setter);
-			bool null_allowed = AttributeManager.HasAttribute<NullAllowedAttribute> (pi) || AttributeManager.HasAttribute<NullAllowedAttribute> (setter);
+			bool null_allowed = AttributeManager.HasAttribute<NullAllowedAttribute> (setter);
+			if (null_allowed)
+				ErrorHelper.Show (new BindingException (1118, false, $"[NullAllowed] should not be used on methods, like '{setter}', but only on properties, parameters and return values."));
```
Comment (rolfbjarne) [inline src/generator.cs]: Same: `ErrorHelper.Warning`

**Comment by dalexsoto** [comment]
I think this should be an error for our bindings, it is easier to spot when rebuilding the world

**Comment by spouliot** [comment]
@dalexsoto it is - since we build with `-warnaserror` :-)

File: src/generator.cs (hunk 1 above)
Comment (spouliot) [reply src/generator.cs]: @rolfbjarne that API does not exist (at least in the generator code base)

Comment (rolfbjarne) [reply src/generator.cs]: It should :/ oh well, maybe some other day.

**Comment by spouliot** [comment]
test failure is a known issue -> 
https://github.com/xamarin/maccore/issues/1345
