### PR TITLE
[Foundation] Implement IEquatable and IComparable for NSOperatingSystemVersion

### LINKED ISSUE #15721: NSOperatingSystemVersion should be IEquatable and IComparable
### Steps to Reproduce

1. Try to compare two NSOperatingSystemVersion instances.

### Expected Behavior

IEquatable and IComparable should exist, maybe operator implementation.

### Actual Behavior

None are available.

### Environment

dotnet 6

### Notes

I know `NSProcessInfo.IsOperatingSystemVersionAtLeastVersion` can be used, but you could theoretically avoid caching the results of this call if the operators are exposed.

### PR DESCRIPTION
**Pull request by haritha-mohan**
Implemented the interfaces for NSOperatingSystemVersion, can now compare instances and check for equality using operators.

Fixes #15721

### CODE REVIEW

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 1]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
 	[SupportedOSPlatform ("macos")]
 	[SupportedOSPlatform ("tvos")]
 #endif
-	// NSProcessInfo.h
-	public struct NSOperatingSystemVersion {
+
+	public struct NSOperatingSystemVersion: IEquatable<NSOperatingSystemVersion>, IComparable{
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:40]: nit: you should have a space before the open brace:
```
IComparable {
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 2]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
 		public nint Major, Minor, PatchVersion;
 		
-		public NSOperatingSystemVersion (nint major, nint minor, nint patchVersion)
+        public NSOperatingSystemVersion (nint majorVersion, nint minorVersion, nint patchVersionArg)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:43]: Probably `patchVersion` is better than `patchVersionArg`

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 3]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+		{
+			Major = majorVersion;
+			Minor = minorVersion;
+			PatchVersion = patchVersionArg;
+		}
+
+        public NSOperatingSystemVersion (nint majorVersion, nint minorVersion)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:50]: This can be done by chaining to the more full constructor:
```
public NSOperatingSystemVersion (nint majorVersion, nint minorVersion)
    : this (majorVersion, minorVersion, 0);
{
}
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 4]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+                } 
+            }
+            else {
+                return majorValue;
+            }
+                
+        }
+
+        public int CompareTo(Object obj) {
+            if (obj == null) return 1;
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:83]: favor `is null` over `== null`

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 5]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+        }
+
 		public override string ToString ()
 		{
 			return Major + "." + Minor + "." + PatchVersion;
 		}
+
+		public bool Equals (NSOperatingSystemVersion other) 
+        {
+            if (other == null)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:96]: same

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 6]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+                return false;
+            
+            if (Major == other.Major &&
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:99]: This can be simplified to:
```
return Major == other.Major && Minor == other.Minor && PatchVersion == other.PatchVersion;
```
if you want to get really 'stuffy' you can do for the entire method:
```
return other is not null && Major == other.Major && Minor == other.Minor && PatchVersion == other.PatchVersion;
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 7]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+                Minor == other.Minor &&
+                PatchVersion == other.PatchVersion) 
+                return true;
+            else
+                return false;
+        }
+
+		public override bool Equals (Object obj)
+        {
+            if (obj == null)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:109]: favor `is null`

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 8]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+        }
+
+        public override int GetHashCode()
+        {
+            return Tuple.Create(Major, Minor, PatchVersion).GetHashCode();
+        }
+
+        public static bool operator == (NSOperatingSystemVersion os1, NSOperatingSystemVersion os2)
+        {
+            if (((object)os1) == null || ((object)os2) == null)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:124]: same on `== null`

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 5 above)
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:96]: Lets add at the top of the file:
```cs
#nullable enable
```
That will force you to make a few changes. On would be to do:
```suggestion
            if (other is null)
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 9]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+                    return minorValue;
+                } 
+            }
+            else {
+                return majorValue;
+            }
+                
+        }
+
+        public int CompareTo(Object obj) {
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:82]: nit, style.
```suggestion
        public int CompareTo (Object obj) {
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 10]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+        public static bool operator == (NSOperatingSystemVersion os1, NSOperatingSystemVersion os2)
+        {
+            if (((object)os1) == null || ((object)os2) == null)
+                return Object.Equals(os1, os2);
+            return os1.Equals(os2);
+        }
+
+        public static bool operator != (NSOperatingSystemVersion os1, NSOperatingSystemVersion os2)
+        {
+            if (((object)os1) == null || ((object)os2) == null)
```
Comment (stephen-hawley) [inline src/Foundation/NSOperatingSystemVersion.cs:131]: same.
Also is there a reason why this isn't `return !(os1 == os2)`?

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 11]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+            else {
+                return majorValue;
+            }
+                
+        }
+
+        public int CompareTo(Object obj) {
+            if (obj == null) return 1;
+            if (obj is NSOperatingSystemVersion other)
+                return CompareTo(other);
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:85]: nit, style.
```suggestion
                return CompareTo (other);
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 12]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+        {
+            if (other == null)
+                return false;
+            
+            if (Major == other.Major && 
+                Minor == other.Minor &&
+                PatchVersion == other.PatchVersion) 
+                return true;
+            else
+                return false;
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:104]: You don't need the if, do you? A simple return does the trick :)

**Review by stephen-hawley — CHANGES_REQUESTED** [review]
Nice PR - most of the changes I'm requesting are style issues. You'll get used to those over time.

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 13]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+        }
+
+		public override bool Equals (Object obj)
+        {
+            if (obj == null)
+                return false;
+            if (obj is NSOperatingSystemVersion versionObj)
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:111]: Does the is work with null? If it does we can remove the first branch

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 14]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
 
+        public NSOperatingSystemVersion (nint majorVersion)
+		{
+			Major = majorVersion;
+			Minor = 0;
+			PatchVersion = 0;
+		}
+
+        public int CompareTo (NSOperatingSystemVersion otherVersion) {
+            int majorValue = Major.CompareTo(otherVersion.Major);
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:65]: nit, style
```suggestion
            int majorValue = Major.CompareTo (otherVersion.Major);
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 15]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+            if (majorValue == 0) {
+                int minorValue = Minor.CompareTo(otherVersion.Minor);
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:67]:
```suggestion
                int minorValue = Minor.CompareTo (otherVersion.Minor);
```

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 11 above)
Comment (mandel-macaque) [reply src/Foundation/NSOperatingSystemVersion.cs:85]: If the is operator works with null, you can remove a branch.

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 1 above)
Comment (tj-devel709) [inline src/Foundation/NSOperatingSystemVersion.cs:40]:
```suggestion
	public struct NSOperatingSystemVersion : IEquatable<NSOperatingSystemVersion>, IComparable{
```
A space before the colon would also be preferable here :)

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 14 above)
Comment (tj-devel709) [inline src/Foundation/NSOperatingSystemVersion.cs:65]:
```suggestion
            var majorValue = Major.CompareTo(otherVersion.Major);
```
we also tend to use var instead of the strong types when possible

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 15 above)
Comment (tj-devel709) [inline src/Foundation/NSOperatingSystemVersion.cs:67]:
```suggestion
                var minorValue = Minor.CompareTo(otherVersion.Minor);
```
same here!

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 16]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+            if (((object)os1) == null || ((object)os2) == null)
+                return Object.Equals(os1, os2);
+            return os1.Equals(os2);
+        }
+
+        public static bool operator != (NSOperatingSystemVersion os1, NSOperatingSystemVersion os2)
+        {
+            if (((object)os1) == null || ((object)os2) == null)
+                return ! Object.Equals(os1, os2);
+            return ! (os1.Equals(os2));
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:133]: Why not call the == operator and negate?

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 17]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+			Minor = 0;
+			PatchVersion = 0;
+		}
+
+        public int CompareTo (NSOperatingSystemVersion otherVersion) {
+            int majorValue = Major.CompareTo(otherVersion.Major);
+            if (majorValue == 0) {
+                int minorValue = Minor.CompareTo(otherVersion.Minor);
+                if (minorValue == 0) {
+                    int patchValue = PatchVersion.CompareTo(otherVersion.PatchVersion);
```
Comment (tj-devel709) [inline src/Foundation/NSOperatingSystemVersion.cs:69]:
```suggestion
                    var patchValue = PatchVersion.CompareTo(otherVersion.PatchVersion);
```

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 18]
```diff
@@ -36,20 +36,102 @@ namespace Foundation  {
...
+            if (obj is NSOperatingSystemVersion versionObj)
+                return Equals(versionObj);
+            else   
+                return false; 
+        }
+
+        public override int GetHashCode()
+        {
+            return Tuple.Create(Major, Minor, PatchVersion).GetHashCode();
+        }
```
Comment (mandel-macaque) [inline src/Foundation/NSOperatingSystemVersion.cs:120]:
```suggestion
        public override int GetHashCode()
                => Tuple.Create(Major, Minor, PatchVersion).GetHashCode();
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
Some small nits and things you could improve a little.

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 14 above)
Comment (tj-devel709) [inline src/Foundation/NSOperatingSystemVersion.cs:65]: Also don't forget to add a space before the opening brackets throughout the file. Looks like you got a lot of them correct but a few more can be fixed!

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 4 above)
Comment (tj-devel709) [reply src/Foundation/NSOperatingSystemVersion.cs:83]:
```suggestion
            if (obj is null) 
                return 1;
```
Also for style there should be a new line in the if statement. (I couldn't use the tab key here so the spacing of my suggestion may get messed up)

File: tests/monotouch-test/Foundation/NSOperatingSystemVersionTest.cs [hunk 19]
```diff
@@ -0,0 +1,126 @@
...
+			}
+		}
+
+		[Test, TestCaseSource("VersionCasesCompare")]
+		public void NSVersionCompare ((NSOperatingSystemVersion v1, NSOperatingSystemVersion v2, int res) sample)
+		{
+			Assert.AreEqual (sample.v1.CompareTo (sample.v2), sample.res);
+		}
+	}
+}
```
Comment (tj-devel709) [inline tests/monotouch-test/Foundation/NSOperatingSystemVersionTest.cs:126]:
```suggestion
}

```
That little red circle means that the file is missing a new line so don't forget to add that in for cs files

**Review by tj-devel709 — COMMENTED** [review]
Looks great so far! I left some nitty style changes that I believe could be improved :)

**Review by dalexsoto — APPROVED** [review]
After Manuel's and Steve's comments are addressed this is great! Congrats!

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 10 above)
Comment (haritha-mohan) [reply src/Foundation/NSOperatingSystemVersion.cs:131]: good point, that makes things easier!

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 3 above)
Comment (chamons) [inline src/Foundation/NSOperatingSystemVersion.cs:50]: Not even a nit: For straight assigns I often prefer to name the variable to a constructor the same as the field, just with different initial capitalization:

```
public NSOperatingSystemVersion (nint major, nint minor)
{
    Major = major;
    Minor = minor;
}
```

**Review by chamons — APPROVED** [review]
Approved once other concerns are resolved.

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 5 above)
Comment (rolfbjarne) [inline src/Foundation/NSOperatingSystemVersion.cs:96]: `NSOperatingSystemVersion` is a struct, which means `other` can never be `null` in this method, so you can remove the null check.

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 8 above)
Comment (rolfbjarne) [inline src/Foundation/NSOperatingSystemVersion.cs:124]: Neither `os1` nor `os2` can ever be null, so you can remove these null checks.

File: src/Foundation/NSOperatingSystemVersion.cs (hunk 10 above)
Comment (rolfbjarne) [inline src/Foundation/NSOperatingSystemVersion.cs:131]: Same here, these null checks are not necessary.

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by stephen-hawley — APPROVED** [review]

File: src/Foundation/NSOperatingSystemVersion.cs [hunk 20]
```diff
@@ -36,20 +37,57 @@ namespace Foundation  {
...
 #endif
-	// NSProcessInfo.h
-	public struct NSOperatingSystemVersion {
+
+	public struct NSOperatingSystemVersion : IEquatable<NSOperatingSystemVersion>, IComparable 
+    {
 		public nint Major, Minor, PatchVersion;
 		
-		public NSOperatingSystemVersion (nint major, nint minor, nint patchVersion)
+        public NSOperatingSystemVersion (nint major, nint minor, nint patchVersion)
```
Comment (rolfbjarne) [inline src/Foundation/NSOperatingSystemVersion.cs:45]: NBD, but this line shows up in the diff even though it seems nothing important changed (I'm guessing it's a whitespace change).

In general we avoid whitespace changes, because it makes diffs harder to read (you end up spending trying to figure out what changed, just to realize nothing did).

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
Just a couple of formatting issues left, otherwise this looks good!

**Review by rolfbjarne — APPROVED** [review]

**Comment by haritha-mohan** [comment]
All tests pass except for one timeout
