### PR TITLE
[Foundation] Avoid LINQ in bindings. Fixes #8773

### LINKED ISSUE #8773: HttpClient.SendAsync with ByteArrayContent hangs and never returns
### Steps to Reproduce

HttpClient hangs an app and stops code execution. The UI thread is not frozen (spinner, sounds, video is there). The HttpClient is a singleton instance with a 30-sec timeout configured but when the issue happens (80% of times), the client never returns, not even after the 30-sec timeout (I tested for 5-10 minutes):

```
private static readonly HttpClient Client = new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
```
The handler is `NSUrlSessionHandler`, this is how it’s originally called:
```
var url = <api_endpoint_here>";
byte[] imageBytes = ...; //  usually 20-30 KB of data, a sample attached
var content = new ByteArrayContent(imageBytes);
content.Headers.ContentType = new MediaTypeHeaderValue("image/jpeg");
var request = new HttpRequestMessage(HttpMethod.Post, url);
request.Content = content;
var response = await Client.SendAsync(request);
// in case of repro, this line is never executed
```

I tried to use ConfigureAwait not to restore the context - same result:
```
var response = await Client.SendAsync(request).ConfigureAwait(false);
// this line is never executed
```

I tried to call ContinueWith - same result:
```
var response = await Client.SendAsync(request).ContinueWith(t=>
	// this line is never executed
);
```

This can be reproduced only in release builds (when the linker is set to SDK Only), if you try to debug or if you build a debug without with linker disabled - it always works. And it’s only for `Xamarin.iOS` (Xamarin.Android works fine). Unfortunately, there is no sample to reproduce the issue but it stable in reproducing in my local environment. 

Initially, I used  `StreamContent(imageSteam)`, but after an assumption, that the stream wasn’t working nicely with the `HttpClient` and decided to reimplement with `ByteArrayContent`. In both cases, the issue is reproducible 80% of the times.

### Environment

```
=== Visual Studio Enterprise 2019 for Mac (Preview) ===

Version 8.7 Preview (8.7 build 522)
Installation UUID: 197b4b8d-2a9a-4fbd-896c-cd74849affd3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000073

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.73 (2020-02/d6f0c25d34d) (64-bit)
	Package version: 612000073

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Versions:
	3.1.300
	3.1.201
	3.1.200
	3.1.102
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.500
	2.1.402
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	3.1.3
	3.1.2
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.6
	2.1.4
	2.1.2
	2.1.1
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.31
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Version: 6.20.0.20 (Visual Studio Enterprise)
Hash: bced85e1a
Branch: d16-7
Build date: 2020-05-04 18:27:38-0400

=== Xamarin.iOS ===

Version: 13.20.0.20 (Visual Studio Enterprise)
Hash: bced85e1a
Branch: d16-7
Build date: 2020-05-04 18:27:38-0400

=== Xamarin Designer ===

Version: 16.7.0.155
Hash: 03858dcd7
Branch: remotes/origin/d16-7
Build date: 2020-04-27 18:53:20 UTC

=== Xamarin.Android ===

Version: 10.3.99.230 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/1c21f5c
Android SDK: /Users/astrakh/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 051408e
Java.Interop: xamarin/java.interop/d16-7@6608c59
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@12f52ac

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/astrakh/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.56
Hash: c4cd6b3
Branch: remotes/origin/d16-7
Build date: 2020-04-30 04:52:44 UTC

=== Android Device Manager ===

Version: 16.6.0.115
Hash: 15b9321
Branch: remotes/origin/d16-7
Build date: 2020-04-30 04:53:06 UTC

=== Build Information ===

Release ID: 807000522
Git revision: e60ad3eae1b5bfc65148c1253baf22bd48a0ce3f
Build date: 2020-05-18 10:11:32-04
Build branch: release-8.7
Xamarin extensions: e60ad3eae1b5bfc65148c1253baf22bd48a0ce3f

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 2.0.1
Xamarin Hot Reload 20190830.17


```

### Sample content

decoded-20200604184330

### PR DESCRIPTION
**Pull request by mandel-macaque**
LINQ was giving issues in a client application with the Link SDK
enabled. The root cause is that we had issues in the LINQ operations
that are used to create the headers for the native request.

We fix this by:

1. Do not modify the managed request headers. Do not modify an object we
   do not own.
2. Remove the use of LINQ

This issue was probelmatic when the client application was setting the
headers that are used by the HttpContent. If headers were not added in
the content, the issues did not happen.

Fixes: https://github.com/xamarin/xamarin-macios/issues/8773

### CODE REVIEW

File: src/Foundation/NSUrlSessionHandler.cs [hunk 1]
```diff
@@ -425,32 +424,39 @@ string GetHeaderSeparator (string name)
 			return value;
 		}
 
+		void AddManagedHeaders (NSMutableDictionary nativeHeaders, IEnumerable<KeyValuePair<string, IEnumerable<string>>> managedHeaders)
+		{
+			foreach (var keyValuePair in managedHeaders) {
+				var key = new NSString (keyValuePair.Key);
+				var value = new NSString (string.Join (GetHeaderSeparator (key), keyValuePair.Value));
+				nativeHeaders.Add (key, value);
```
Comment (dalexsoto) [inline src/Foundation/NSUrlSessionHandler.cs:432]: @mandel-macaque  Just a little nit, I think you can definitely avoid the NSString allocations with something like this

```suggestion
				var keyPtr = NSString.CreateNative (keyValuePair.Key);
				var valuePtr = NSString.CreateNative (string.Join (GetHeaderSeparator (keyValuePair.Key), keyValuePair.Value));
				nativeHeaders.LowlevelSetObject (valuePtr, keyPtr);
				NSString.ReleaseNative (keyPtr);
				NSString.ReleaseNative (valuePtr);
```

File: src/Foundation/NSUrlSessionHandler.cs [hunk 2]
```diff
@@ -425,32 +424,39 @@ string GetHeaderSeparator (string name)
...
 		async Task<NSUrlRequest> CreateRequest (HttpRequestMessage request)
 		{
 			var stream = Stream.Null;
+			var nativeHeaders = new NSMutableDictionary ();
 			// set header cookies if needed from the managed cookie container if we do use Cookies
 			if (session.Configuration.HttpCookieStorage != null) {
 				var cookies = cookieContainer?.GetCookieHeader (request.RequestUri); // as per docs: An HTTP cookie header, with strings representing Cookie instances delimited by semicolons.
 				if (!string.IsNullOrEmpty (cookies))
-					request.Headers.TryAddWithoutValidation (Cookie, cookies); 
+					nativeHeaders.Add (new NSString (Cookie), new NSString (cookies));
```
Comment (dalexsoto) [inline src/Foundation/NSUrlSessionHandler.cs:444]: Same here

```csharp
					var cookiePtr = NSString.CreateNative (Cookie);
					var cookiesPtr = NSString.CreateNative (cookies);
					nativeHeaders.LowlevelSetObject (cookiesPtr, cookiePtr);
					NSString.ReleaseNative (cookiePtr);
					NSString.ReleaseNative (cookiesPtr);
```

File: src/Foundation/NSUrlSessionHandler.cs (hunk 1 above)
Comment (mandel-macaque) [reply src/Foundation/NSUrlSessionHandler.cs:432]: I'll test the change before just in case ;)

Comment (mandel-macaque) [reply src/Foundation/NSUrlSessionHandler.cs:432]: and confirmed :)

File: src/Foundation/NSUrlSessionHandler.cs (hunk 2 above)
Comment (mandel-macaque) [inline src/Foundation/NSUrlSessionHandler.cs:444]:
```suggestion
					var cookiePtr = NSString.CreateNative (Cookie);
					var cookiesPtr = NSString.CreateNative (cookies);
					nativeHeaders.LowlevelSetObject (cookiesPtr, cookiePtr);
					NSString.ReleaseNative (cookiePtr);
					NSString.ReleaseNative (cookiesPtr);
```

File: src/Foundation/NSUrlSessionHandler.cs [hunk 3]
```diff
@@ -425,32 +424,46 @@ string GetHeaderSeparator (string name)
 			return value;
 		}
 
+		void AddManagedHeaders (NSMutableDictionary nativeHeaders, IEnumerable<KeyValuePair<string, IEnumerable<string>>> managedHeaders)
+		{
+			foreach (var keyValuePair in managedHeaders) {
+				var keyPtr = NSString.CreateNative (keyValuePair.Key);
+				var valuePtr = NSString.CreateNative (string.Join (GetHeaderSeparator (keyValuePair.Key), keyValuePair.Value));
```
Comment (Therzok) [inline src/Foundation/NSUrlSessionHandler.cs:431]: This is more of a curiosity than a statement, but would using an `NSMutableString` and appending chunks to it be faster? Could be benchmarked, I think.

**Comment by mandel-macaque** [comment]
@monojenkins backport d16-7
@monojenkins backport d16-8
