### PR TITLE
[Compression] Ensure we use the correct linking flags for older versions. Fixes #4129. (#4169)

### LINKED ISSUE #4129: Can't launch monotouch-test on iOS <9
Repro:

* Run monotouch-test on an older (< iOS 9.0) device (in the `Release (all optimizations)` configuration using xharness)

Crashes at launch with

```
Dyld Error Message:
  Library not loaded: /usr/lib/libcompression.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/04F52304-EF42-4491-BE2B-45BD9062C875/monotouchtest.app/monotouchtest
  Reason: image not found
  Dyld Version: 353.10
```

which makes sense since libcompression.dylib was introduced in iOS 9: https://developer.apple.com/documentation/compression?language=objc

Probable fix: if the deployment target is < iOS 9 / macOS 10.11 / tvOS 9.0 / watchOS 2.0, then use `-weak-lcompression` instead of `-lcompression` here: https://github.com/xamarin/xamarin-macios/blob/238eb94caacb79051eae1e28143dc6999d935d78/tools/common/Assembly.cs#L367-L370

### PR DESCRIPTION
**Pull request by mandel-macaque**
Libcompresison was added after iOs 9.0, TvOS 9.0, Mac 10.11 and Watch
2.0. We want to use weak in those older platforms.

Fixes issue https://github.com/xamarin/xamarin-macios/issues/4129

This is a cherry-pick of https://github.com/xamarin/xamarin-macios/pull/4169

### CODE REVIEW

File: tests/monotouch-test/Compression/CompressionStreamTest.cs [hunk 1]
```diff
@@ -44,13 +44,17 @@ private static bool compare_buffers (byte[] first, byte[] second, int length)
 		[ExpectedException (typeof (ArgumentNullException))]
 		public void Constructor_Null ()
 		{
+			if (!TestRuntime.CheckXcodeVersion (7, 0))
```
Comment (dalexsoto) [inline tests/monotouch-test/Compression/CompressionStreamTest.cs]: All of those new checks are identical maybe you can do something like this

```csharp
[SetUp]
public void SetUp ()
{
	if (!TestRuntime.CheckXcodeVersion (7, 0))
		Assert.Ignore ("Requires iOS 9.0+ or macOS 10.11+");
}
```

**Comment by mandel-macaque** [comment]
@dalexsoto yeah, it was a good idea, too late :/
