### PR TITLE
[naturallanguage] Fix helper API for `NLTagger.GetTag` and cleanup/fix other API. Fixes #4774

### LINKED ISSUE #4774: Cannot return lemmas from iOS 12 NaturalLanguage GetTags
### Steps to Reproduce

1. Run the attached project and note the exception

The app tries parsing a sentence to return the lemmas.

### Expected Behavior

Writes to console a list of words and their lemma.

### Actual Behavior

`NLTag` tries to parse the lemma "the" and fails with an exception. It should return the string constant.

```text
System.NotSupportedException: the has no associated enum value in NLTag on this platform.
  at NaturalLanguage.NLTagExtensions.GetValue (Foundation.NSString constant) [0x001fb] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/NaturalLanguage/NLTag.g.cs:507 
  at NaturalLanguage.NLTagger+<>c.<GetTags>b__16_0 (Foundation.NSString e) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/NaturalLanguage/NLTagger.g.cs:233 
  at System.Array.ConvertAll[TInput,TOutput] (TInput[] array, System.Converter`2[TInput,TOutput] converter) [0x00029] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Array.cs:270 
  at NaturalLanguage.NLTagger.GetTags (Foundation.NSRange range, NaturalLanguage.NLTokenUnit unit, NaturalLanguage.NLTagScheme scheme, NaturalLanguage.NLTaggerOptions options, Foundation.NSValue[]& tokenRanges) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/NaturalLanguage/NLTagger.g.cs:233 
  at NatLang.ViewController.ViewDidLoad () [0x0002a] in /Users/fak/Projects/NatLang/NatLang/ViewController.cs:24 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.99.3.538/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at NatLang.Application.Main (System.String[] args) [0x00001] in /Users/fak/Projects/NatLang/NatLang/Main.cs:12 
```
### Environment

```text
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.1 (build 7)
Installation UUID: 4ba352e1-73e8-4dab-a9db-28012ca05af8
Runtime:
	Mono 5.12.0.305 (2018-02/e0e035e3b14) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000305

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.0-preview2-26406-04
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.300-preview2-008530
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.12.2)
Build 10L232m

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.99.3.658 (Visual Studio Enterprise)
Hash: 1eefd4e3
Branch: 
Build date: 2018-08-21 15:01:53-0400

=== Xamarin.iOS ===

Version: 11.99.3.538 (Visual Studio Enterprise)
Hash: 1eefd4e3
Branch: HEAD
Build date: 2018-08-21 15:01:52-0400

=== Build Information ===

Release ID: 706010007
Git revision: 7c9e755fe667840f2eed42b2e7910ec18ef51b82
Build date: 2018-08-24 02:25:33+00
Build branch: release-7.6-xcode10
Xamarin extensions: 1196f085605a84ce99f390a1aaee0bf257d31a50

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MSBuild Editor 2.0.4
Internet of Things (IoT) development (Preview) 7.5
```

### Example Project (If Possible)

[NatLangLemmaFailure.zip](https://github.com/xamarin/xamarin-macios/files/2361665/NatLangLemmaFailure.zip)

### PR DESCRIPTION
**Pull request by spouliot**
* Move `NLTag` to static class (instead of enum) since it's not used in API, except along NSString. Fixes https://github.com/xamarin/xamarin-macios/issues/4774
* Add new member to `NLLanguage` to avoid `ArgumentNullException` when it has not been evaludated (API returns `null`), see unit tests;
* Add `[Params]` to `NLTagger` constructors so they are easier to use (no need to create the array in source);
* Fix `GetTag` so it returns (`out`) the `NSRange`, it's natively a `NSRangePointer`;
* Fix `GetTag[s]` API with changes to `NLTag` de-enumification;
* Add unit tests

### CODE REVIEW

File: src/NaturalLanguage/Enums.cs [hunk 1]
```diff
@@ -67,6 +67,8 @@ public enum NLTokenizerAttributes : ulong {
 	[iOS (12,0), Mac (10,14, onlyOn64: true), TV (12,0), Watch (5,0)]
 	public enum NLLanguage {
 		[DefaultEnumValue]
+		[Field (null)]
+		Unevaludated,
```
Comment (rolfbjarne) [inline src/NaturalLanguage/Enums.cs]: Typo: `Unevaluated`

Comment (spouliot) [reply src/NaturalLanguage/Enums.cs]: good catch, I wonder why the typo check did not hit it locally ?!?
