### PR TITLE
[tests] Confirm a device/sim support Metal before running MetalPerformanceShaders tests. Fixes #3237

### LINKED ISSUE #3237: [XI] MPSImageHistogramEqualizationTest failure on 9.3.5 device
### Steps to Reproduce

1. Update System to XI, xamarin.ios-11.8.0.9.pkg
2. Checkout 0059e3e5b5519ac96070916453b2f7a8dab26ef0
3. Build and execute monotouch-test on an iOS 9.3.5 device

### Expected Behavior
Tests should pass on device

### Actual Behavior
[FAIL] MPSImageHistogramEqualizationTest.Constructors : System.ArgumentNullException : Value cannot be null.
[FAIL] MPSImageHistogramSpecificationTest.Constructors : System.ArgumentNullException : Value cannot be null.
[FAIL] MPSImageHistogramTest.Constructors : System.ArgumentNullException : Value cannot be null.

### Environment
```
xamarin.ios-11.8.0.9.pkg 
```

### Build Logs

1. Build Log: 
http://xqa.blob.core.windows.net/gist/report-415de76c50e14ab184430a363ca7f01e.txt
2.Test Log: 
http://xqa.blob.core.windows.net/gist/monotouchtest-ios04-51-090c3a0d1d60fbd11401f1d6ca33518e9a31bafab404-51-09-6e29a551645641da992e51adf30d089e.zip

### PR DESCRIPTION
**Pull request by spouliot**
https://github.com/xamarin/xamarin-macios/issues/3237

### CODE REVIEW

File: tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramEqualizationTest.cs [hunk 1]
```diff
@@ -20,17 +20,26 @@ namespace MonoTouchFixtures.MetalPerformanceShaders
...
+		[TestFixtureSetUp]
+		public void Metal ()
 		{
 #if !MONOMAC
-			TestRuntime.AssertDevice ();
-			TestRuntime.AssertXcodeVersion (7, 0);
+			TestRuntime.AssertXcodeVersion (7,0);
 #else
-			TestRuntime.AssertXcodeVersion (9, 0);
+			TestRuntime.AssertXcodeVersion (9,0);
```
Comment (rolfbjarne) [inline tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramEqualizationTest.cs]: Whitespace changes 😄 (same changes in all files)

BTW did VSM do this change? I find it a strange change to do

Comment (spouliot) [reply tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramEqualizationTest.cs]: no (or likely not). The `Metal` setup method was copied from other unit tests and it just _looks like_ whitespace changes in the diff.

**Comment by spouliot** [comment]
known issue (csc/roslyn NRE) -> https://github.com/xamarin/maccore/issues/618
