### PR TITLE
[msbuild] Emit binding resources to the EmbeddedResource item group instead of ManifestResourceWithNoCulture. Fixes #3876.

### LINKED ISSUE #3876: [msbuild] warning MSB9004: ManifestResourceWithNoCulture item type is deprecated.
### Steps to Reproduce

1. Create new project "Bindings Library (iOS)"
2. Add Native Reference to some ios framework (e.g. "Test.framework")
3. Try build

### Expected Behavior
Build with no warns

### Actual Behavior
Build with warning:
[skip]Microsoft.Common.CurrentVersion.targets(3214,5): warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.

### Possible reason
msbuild file Xamarin.iOS.ObjCBinding.CSharp.targets ( https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets ) contains rule for PrepareNativeReferences task which use deprecated syntax

### Environment
```
=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: e6bf2be1-b435-4d47-b39c-e45bc71bf6c3
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes this warning:

    warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.

There is a slight difference with regards to the warning message: the Type
metadata is set to 'Non-Resx' instead of 'Resx' (because these resources
aren't resx files).

Fixes https://github.com/xamarin/xamarin-macios/issues/3876.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Test failures are unrelated

* don't link/dotnet: https://github.com/xamarin/xamarin-macios/pull/9527
* monotouch-test/watchOS 32-bit: https://github.com/xamarin/maccore/issues/581

File: tests/mmptest/src/BindingProjectTests.cs [hunk 1]
```diff
@@ -155,6 +155,8 @@ public void ShouldBuildWithoutErrors_AndLinkCorrectFramework (BindingProjectType
 
 				Assert.False (logs.Item1.Contains ("CS1685"), "Binding should not contains CS1685 multiple definition warning:\n" + logs.Item1);
 
+				Assert.False (logs.Item1.Contains ("MSB9004"), "Binding should not contains MSB9004 warning:\n" + logs.Item1);
```
Comment (mandel-macaque) [inline tests/mmptest/src/BindingProjectTests.cs:158]: I know we all use english. But if we have a bot configured to spanish and we land translations, we are going to have issues :/ 

Nothing really to be changed in this PR, but I've got the feeling this is going to hit us in the future.

Comment (chamons) [reply tests/mmptest/src/BindingProjectTests.cs:158]: We have about a million of these in mmp/msbuild ios-msbuild tests.

If nothing else, we can use environmental variables to force language to test this (and hopefully translation as well).
