### PR TITLE
[Foundation] Implement the properties inherited from HttpClientHandler in NSUrlSessionHandler. Fixes #13579.

### LINKED ISSUE #13579: [dotnet] NSUrlSessionHandler and .NET 6 methods called from HttpClientHandler
The methods implemented in this block seem to have couple of issues:

https://github.com/xamarin/xamarin-macios/blob/69015b3cecbb2c7f94c4cbafb37c3c5aa091f166/src/Foundation/NSUrlSessionHandler.cs#L535-L613

Firstly, the `Supports*` properties are not supposed to throw. They are discoverability properties to see if other members would throw. In the current implementation they should likely return `false`. 

In case of `AutomaticDecompression` / `SupportsAutomaticDecompression` it may make sense to lie since the underlying handler probably does the automatic decompression. Note that some libraries may get broken no matter how it is implemented. I remember some of our ActiveSync / EWS code depended on the automatic decompression mechanism removing the `Content-Encoding` header if the automatic decompression is performed. I am not sure how the `NSUrlSessionHandler` behaves here.

Xamarin.Android also [lies](https://github.com/xamarin/xamarin-android/blob/05dd813db4516ecd6767c97a6ed0fba630256b89/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L125) about `ServerCertificateCustomValidationCallback`. It doesn't throw and silently ignores it. It would be nice to have this unifed across platforms. It would be even nicer if the callback was actually implemented but that's separate issue. Old PRs/issues have the implementation already but it was not accepted at the time due to size issues caused by the `X509Certificate` dependency. That's no longer an issue on .NET 6 since the dependency exists anyway.

### PR DESCRIPTION
**Pull request by rolfbjarne**
I've tried to describe the decision for each member in the code.

Fixes https://github.com/xamarin/xamarin-macios/issues/13579.

### CODE REVIEW

File: src/Foundation/NSUrlSessionHandler.cs [hunk 1]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
+		// We're ignoring this property, just like Xamarin.Android does:
+		// https://github.com/xamarin/xamarin-android/blob/09e8cb5c07ea6c39383185a3f90e53186749b802/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L158
+		public bool CheckCertificateRevocationList { get; set; } = false;
 
-		public X509CertificateCollection ClientCertificates {
-			get => throw new PlatformNotSupportedException ();
-		}
+		// We're ignoring this property, just like Xamarin.Android does:
+		// https://github.com/xamarin/xamarin-android/blob/09e8cb5c07ea6c39383185a3f90e53186749b802/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L150
+		public X509CertificateCollection ClientCertificates { get { return null; } }
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:554]: I think this violates the nullability contract. We don't think we'd ever expect getting a null here.
https://github.com/dotnet/runtime/blob/103fb847f66f53557b0e3179599365b65de02ce4/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L255-L256
It does look like it could throw if options aren't manual:
https://github.com/dotnet/runtime/blob/103fb847f66f53557b0e3179599365b65de02ce4/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L252

File: src/Foundation/NSUrlSessionHandler.cs [hunk 2]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
-		}
+		// We're ignoring this property, just like Xamarin.Android does:
+		// https://github.com/xamarin/xamarin-android/blob/09e8cb5c07ea6c39383185a3f90e53186749b802/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L167
+		public IDictionary<string, object> Properties { get { return null; } }
 
+		// We dont support any custom proxies, and don't let anybody wonder why their proxy isn't
+		// being used if they try to assign one (in any case we also return false from 'SupportsProxy').
 		public IWebProxy Proxy {
-			get => throw new PlatformNotSupportedException ();
+			get => null;
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:594]: Null violation?

File: src/Foundation/NSUrlSessionHandler.cs [hunk 3]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
 			set => throw new PlatformNotSupportedException ();
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:595]: If you're going to throw on the setter, I'm not sure there's much point in returning null on the proxy?
Perhaps also consider using `[UnsupportedOSPlatform("ios")]` to warn people not to use it?

File: src/Foundation/NSUrlSessionHandler.cs [hunk 4]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
+		// There's no way to turn off automatic decompression, so yes, we support it
 		public bool SupportsAutomaticDecompression {
-			get => throw new PlatformNotSupportedException ();
+			get => true;
 		}
 
+		// We don't support using custom proxies, but NSUrlSession will automatically use any proxies configured in the OS.
 		public bool SupportsProxy {
-			get => throw new PlatformNotSupportedException ();
+			get => false;
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:617]: With this returning false, is it ok to throw in both getter and setter of the Proxy property?

File: src/Foundation/NSUrlSessionHandler.cs [hunk 5]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
 		}
 
+		// We support the AllowAutoRedirect property, but we don't support changing the MaxAutomaticRedirections value.
 		public bool SupportsRedirectConfiguration {
-			get => throw new PlatformNotSupportedException ();
+			get => true;
 		}
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:623]: My impression was it isn't supported to _configure_ the redirection?

File: src/Foundation/NSUrlSessionHandler.cs [hunk 6]
```diff
@@ -536,84 +536,97 @@ protected override async Task<HttpResponseMessage> SendAsync (HttpRequestMessage
...
 
+		// NSUrlSession will automatically use any proxies configured in the OS (so always return true in the getter).
+		// There doesn't seem to be a way to turn this off, so ignore any attempts to set a different value in the setter.
 		public bool UseProxy {
-			get => throw new PlatformNotSupportedException ();
-			set => throw new PlatformNotSupportedException ();
+			get => true;
+			set { }
 		}
```
Comment (dotMorten) [inline src/Foundation/NSUrlSessionHandler.cs:630]: Isn't this misleading, as this would be referring to the Proxy property of the handler, not the system?

**Review by dotMorten — COMMENTED** [review]
Would it also be good to add `[UnsupportedOSPlatform("iOS")]` to the properties that throws or doesn't do anything, so if you do code against the specific NSUrlSessionHandler, you're at least being told by the compiler that this won't work for you?

File: src/Foundation/NSUrlSessionHandler.cs (hunk 2 above)
Comment (filipnavara) [reply src/Foundation/NSUrlSessionHandler.cs:594]: It should be nullable (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=net-6.0).

File: src/Foundation/NSUrlSessionHandler.cs (hunk 6 above)
Comment (rolfbjarne) [reply src/Foundation/NSUrlSessionHandler.cs:630]: What would your suggestion be to do here instead?

File: src/Foundation/NSUrlSessionHandler.cs (hunk 4 above)
Comment (rolfbjarne) [reply src/Foundation/NSUrlSessionHandler.cs:617]: Maybe, assuming everybody using Proxy checks SupportsProxy first.

This whole PR is a balance between what's technically correct (throw PNSE pretty much everywhere), vs practicality (to make us work with existing code).

File: src/Foundation/NSUrlSessionHandler.cs (hunk 5 above)
Comment (dotMorten) [reply src/Foundation/NSUrlSessionHandler.cs:623]: My thoughts: I would use this property to guard against the use of those unsupported / throwing properties. So I'd say it is safer to return false.

File: src/Foundation/NSUrlSessionHandler.cs (hunk 6 above)
Comment (dotMorten) [reply src/Foundation/NSUrlSessionHandler.cs:630]: Return false?

**Review by mandel-macaque — APPROVED** [review]
Approving to get it to not crash anything, I will later take the time to implement those properties that can be implemented.

**Review by dalexsoto — APPROVED** [review]
Agreed with Manuel here, we can get this going to avoid crashing and we'll take the time to fix it correctly just anyone make sure we have an actual issue for this when we land this PR.

**Comment by rolfbjarne** [comment]
> just anyone make sure we have an actual issue for this when we land this PR.

https://github.com/xamarin/xamarin-macios/issues/14632
