### PR TITLE
[XHarness] Ensure that the correct values are shown on the test reports. Fixes #5639

### LINKED ISSUE #5639: Ignoring tests via .ignore file doesn't increase Ignored count in nunit summary output
### Steps to Reproduce

1. Add some ignored tests to e.g. tests/bcl-test/BCLTests/common-SystemIOCompressionTests.ignore
2. Run the System.IO.Compression tests
3. Check nunit summary output

### Expected Behavior

The `Ignored` value shows when tests are ignored.

### Actual Behavior

Tests ignored: `Tests run: 24 Passed: 4 Inconclusive: 0 Failed: 0 Ignored: 0`
No tests ignored: `Tests run: 24 Passed: 24 Inconclusive: 0 Failed: 0 Ignored: 0`

As you can see only the `Passed` value changed.

### PR DESCRIPTION
**Pull request by mandel-macaque**
The results reported in the xharness run do not add up. Total tests
should include the number of skipped tests. This change ensures that the
tests results correctly add up.

Example nunit fixed tests: [NUnit] Mono SystemIOCompressionTests (total should
be 24, passed 4, ignored 20).
Example xunit fixed tests: [xUnit] Mono SystemDataXunit (total should be
1061, passed 1054, ignored 7).

Fixes https://github.com/xamarin/xamarin-macios/issues/5639

### CODE REVIEW

File: tests/bcl-test/BCLTests/templates/iOSApp/ViewController.cs [hunk 1]
```diff
@@ -120,7 +120,7 @@ public async override void ViewDidLoad ()
 				logger.Info ($"Xml result can be found {resultsFilePath}");
 			}
 			
-			logger.Info ($"Tests run: {runner.TotalTests} Passed: {runner.PassedTests} Inconclusive: {runner.InconclusiveTests} Failed: {runner.FailedTests} Ignored: {runner.SkippedTests}");
+			logger.Info ($"Tests run: {runner.TotalTests} Passed: {runner.PassedTests} Inconclusive: {runner.InconclusiveTests} Failed: {runner.FailedTests} Ignored: {runner.FilteredTests}");
```
Comment (spouliot) [inline tests/bcl-test/BCLTests/templates/iOSApp/ViewController.cs]: not clear inside PR but does `FilteredTests` contains both what you filter (categories) and what's ignored, e.g. `[Ignore]` ?

Comment (mandel-macaque) [reply tests/bcl-test/BCLTests/templates/iOSApp/ViewController.cs]: Yes, it does. The other update was needed because the total number did not include the correct value when skipped.

**Comment by mandel-macaque** [comment]
All those look like a bot issue, I'll retriever the build, don't want to land anything that does not pass tests.

**Comment by mandel-macaque** [comment]
build

**Comment by mandel-macaque** [comment]
Crashes are unrelated to the changes, else all the NUnit and xUnit tests would have failed.
