### PR TITLE
[runtime] Allow `IntPtr` for native objects in the dynamic registrar. Fixes #15708

### LINKED ISSUE #15708: Dynamic registrar aborts for signatures with `IntPtr` instead of an `NSObject` subclass
> This seems like a corner-case: the dynamic registrar gets the signature from native code, which says that the method returns an id, and then we've bound it as an IntPtr, and the dynamic registrar doesn't know how to return a native id given a managed IntPtr. Looking at the code I'm not sure it ever worked (fwiw it works fine if native code does not define the signature).
https://github.com/xamarin/xamarin-macios/issues/15677#issuecomment-1219197616

### Steps to Reproduce

1. See https://github.com/xamarin/xamarin-macios/issues/15677
2. Build for simulator -> crash
3. Enable the static registrar -> works

### Expected Behavior

The same application code should work, identically, for both the static and dynamic registrar.

### Actual Behavior

The dynamic registrar aborts.

`Xamarin.iOS: Don't know how to marshal a return value of type 'System.IntPtr'. Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new`

This means using `IntPtr` cannot be a workaround without requiring the static registrar, which has a large build time impact for the simulator.

### Environment

* xamarin-macios `main`
* Xcode 14 beta 5
* iOS 16 beta 5/6

### PR DESCRIPTION
**Pull request by spouliot**
Allow code like this

```csharp
[DllImport(Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSendSuper")
static extern IntPtr IntPtr_objc_msgSendSuper(IntPtr receiver, IntPtr selector);

[DllImport(Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSendSuper")]
static extern void void_objc_msgSendSuper(IntPtr receiver, IntPtr selector, IntPtr arg);

[Export("selectedTextRange")]
public new IntPtr SelectedTextRange
{
    get { return IntPtr_objc_msgSendSuper(SuperHandle, Selector.GetHandle("selectedTextRange")); }
    set => void_objc_msgSendSuper(SuperHandle, Selector.GetHandle("setSelectedTextRange:"), value);
}
```

to work on the dynamic registrar since it already work with the static one.
This allows the simulators (which defaults to dynamic) to share the same code which is useful for implementing a workaround for related issue #15677.

### CODE REVIEW

File: runtime/trampolines.m [hunk 1]
```diff
@@ -201,7 +201,13 @@
 					}
 				}
 			} else {
-				xamarin_assertion_message ("Don't know how to marshal a return value of type '%s.%s'. Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new\n", mono_class_get_namespace (r_klass), mono_class_get_name (r_klass)); 
+				char *fullname = xamarin_class_get_full_name (r_klass, exception_gchandle);
+				if (!strcmp (fullname, "System.IntPtr")) {
+					returnValue =  *(void **) mono_object_unbox (retval);
+				} else {
+					xamarin_assertion_message ("Don't know how to marshal a return value of type '%s.%s'. Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new\n", mono_class_get_namespace (r_klass), mono_class_get_name (r_klass));
```
Comment (stephen-hawley) [inline runtime/trampolines.m:208]: Since you have the `fullname`, why not change the assertion message to:
`xamarin_assertion_message ("Don't know how to marshal a return value of type '%s', Please Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new\n", full name);`

On a side note, I wonder if this won't be immediately stale with the .NET 6 transition to `NativeHandle` instead of `IntPtr`.

**Review by stephen-hawley — CHANGES_REQUESTED** [review]

File: runtime/trampolines.m (hunk 1 above)
Comment (spouliot) [reply runtime/trampolines.m:208]: Both good points @stephen-hawley I'll address them shortly. Thanks!

File: runtime/trampolines.m [hunk 2]
```diff
@@ -201,7 +201,17 @@
 					}
 				}
 			} else {
-				xamarin_assertion_message ("Don't know how to marshal a return value of type '%s.%s'. Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new\n", mono_class_get_namespace (r_klass), mono_class_get_name (r_klass)); 
+				char *fullname = xamarin_class_get_full_name (r_klass, exception_gchandle);
+#if DOTNET
+				if (!strcmp (fullname, "System.IntPtr") || !strcmp (fullname, "ObjCRuntime.NativeHandle")) {
+#else
+				if (!strcmp (fullname, "System.IntPtr")) {
```
Comment (rolfbjarne) [inline runtime/trampolines.m:208]: There  are two functions that are much faster and simpler: `xamarin_is_class_intptr` and `xamarin_is_class_nativehandle`, no need to compute a full type name nor compare strings.

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

File: runtime/trampolines.m [hunk 3]
```diff
@@ -201,7 +201,17 @@
 					}
 				}
 			} else {
-				xamarin_assertion_message ("Don't know how to marshal a return value of type '%s.%s'. Please file a bug with a test case at https://github.com/xamarin/xamarin-macios/issues/new\n", mono_class_get_namespace (r_klass), mono_class_get_name (r_klass)); 
+				char *fullname = xamarin_class_get_full_name (r_klass, exception_gchandle);
```
Comment (stephen-hawley) [inline runtime/trampolines.m:204]: last little bit - since `fullname` is only used in the error and @rolfbjarne implies that it's more costly than the `xamarin_is_class_` tests, how about moving the allocation and deallocation into the `else` clause so that the price only gets paid in the failing case.

**Review by stephen-hawley — CHANGES_REQUESTED** [review]

File: runtime/trampolines.m (hunk 3 above)
Comment (spouliot) [reply runtime/trampolines.m]: I reverted the assertion to the original code as it did not need (extra) allocation, inside the caller, and still produced the same output.

**Review by stephen-hawley — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/581, https://github.com/xamarin/maccore/issues/2558)
