### PR TITLE
[AVKit] Add bindings for AVCaptureEventInteraction

### LINKED ISSUE #20295: `AVCaptureEvent` and `AVCaptureEventInteraction` haven't been bound
### Steps to Reproduce

Try to compile the following code:
```
var singleActionHandler = new AVCaptureEventInteraction(
    captureEvent => Console.WriteLine("any event: " + captureEvent)
);

var multipleActionHandler = new AVCaptureEventInteraction(
    primaryEvent => Console.Write("primary event: " + primaryEvent),
    secondaryEvent => Console.Write("secondary event: " + secondaryEvent)
);

View!.AddInteraction(singleActionHandler);
View!.AddInteraction(multipleActionHandler);
```

### Expected Behavior

The code should compile and function correctly at runtime.

### Actual Behavior

The code doesn't compile, because `AVCaptureEvent` and `AVCaptureEventInteraction` haven't been bound:

> error CS0246: The type or namespace name 'AVCaptureEventInteraction' could not be found (are you missing a using directive or an assembly reference?)

### Environment

<details>
<summary>Version information</summary>

```
.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.a7f084b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.202/

.NET workloads installed:
 [ios]
   Installation Source: SDK 8.0.200
   Manifest Version:    17.2.8043/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8043/WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: SDK 8.0.200
   Manifest Version:    34.0.85/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.android/34.0.85/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.3
  Architecture: arm64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  7.0.313 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found
```

</details>

### PR DESCRIPTION
**Pull request by rpendleton**
Resolves #20295

### CODE REVIEW

**Comment by rpendleton** [comment]
@microsoft-github-policy-service agree company="Verisk Analytics, Inc."

File: src/avkit.cs [hunk 1]
```diff
@@ -1099,4 +1100,36 @@ interface AVPlaybackSpeed {
...
+	[DisableDefaultCtor]
+	interface AVCaptureEvent
+	{
+		[Export("phase")]
+		AVCaptureEventPhase Phase { get; }
+	}
+
+	[iOS (17, 2), NoMac, NoMacCatalyst, NoTV, NoWatch]
+	[Native]
+	public enum AVCaptureEventPhase : ulong {
```
Comment (rpendleton) [inline src/avkit.cs:1115]: I noticed there's a file at `src/AVKit/Enums.cs`, but there are just as many enums in `src/avkit.cs`.  I wasn't sure which file I should use, so I just put the enum here. I can move it to the enum file if that's preferred though.

File: src/avkit.cs [hunk 2]
```diff
@@ -1099,4 +1100,36 @@ interface AVPlaybackSpeed {
...
+	[iOS (17, 2), NoMac, NoMacCatalyst, NoTV, NoWatch]
+	[BaseType(typeof(NSObject))]
+	[DisableDefaultCtor]
+	interface AVCaptureEventInteraction : UIInteraction
+	{
+		[Export ("initWithEventHandler:")]
+		NativeHandle Constructor (Action<AVCaptureEvent> handler);
+
+		[Export ("initWithPrimaryEventHandler:secondaryEventHandler:")]
+		NativeHandle Constructor (Action<AVCaptureEvent> primaryHandler, Action<AVCaptureEvent> secondaryHandler);
```
Comment (rpendleton) [inline src/avkit.cs:1130]: I noticed some places use C# `delegates` for callbacks, and others just use `Actions`. I wasn't sure which is preferred so I went with actions, but I can change these to delegates if that's preferred.

Comment (rolfbjarne) [reply src/avkit.cs:1130]: The problem with `Action/Func` is that it's not possible to give them names of the parameters, so they have to be pretty much self-explanatory. This means that we typically use delegates when we need to give names to the parameters in order to document what they're doing. In this case, it seems that a delegate is appropriate, since it's not obvious from only the parameter types what each does.

File: src/avkit.cs (hunk 1 above)
Comment (rolfbjarne) [reply src/avkit.cs:1115]: The split is just for historical reasons, in `avkit.cs` is fine.

File: src/avkit.cs (hunk 2 above)
Comment (rpendleton) [reply src/avkit.cs:1130]: In this case, the difference is that the first constructor results in both "primary" and "secondary" events being passed to a single callback, whereas the second constructor splits those events between two callbacks. (Primary and secondary basically just maps to volume down and volume up.)

I was originally planning on using a single delegate such as:
```csharp
delegate void AVCaptureEventHandler(AVCaptureEvent captureEvent);
```

It sounds like maybe you're suggesting three delegates though, as opposed to relying on only constructor parameter names? If so, we could do something like the following. (And perhaps with a better name for the first one.)
```csharp
delegate void AVCaptureEventHandler(AVCaptureEvent captureEvent);
delegate void AVCapturePrimaryEventHandler(AVCaptureEvent primaryEvent);
delegate void AVCaptureSecondaryEventHandler(AVCaptureEvent secondaryEvent);
```

For what it's worth, these are the original methods from the AVKit headers:
```objective-c
- (instancetype)initWithEventHandler:(void (^)(AVCaptureEvent *event))handler

- (instancetype)initWithPrimaryEventHandler:(void (^)(AVCaptureEvent *event))primaryHandler
                      secondaryEventHandler:(void (^)(AVCaptureEvent *event))secondaryHandler
```

Comment (rolfbjarne) [reply src/avkit.cs:1128]: Ah, never mind, it was too early in the morning when I commented, so I misunderstood the code a bit.

Delegates with a single argument are typically fine as Func/Action, and this doesn't look like an exception.

**Review by mandel-macaque — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Thanks for your contribution!
