### PR TITLE
[ObjCRuntime] Fix the DisposableObject.Owns property to return the correct value. Fixes #13646.

### LINKED ISSUE #13646: Audio File Corruption Caused By DisposableObject.Owns
AudioFiles filled with compressed data through the Audio Toolbox AudioConverter are currently being corrupted. Looking into it a bit, it appears that AudioFileClose is not being called on disposed because DisposableObject.Owns is always returning false. Looking at DisposableObject it seems possible that the property is not returning its backing variable that is being set through the constructor. This causes issues with child classes such as AudioFile and AudioConverter that check Owns before calling their clean up methods. In the case of AudioFile, it corrupts any audio file that needs to add PacketTableInfo (most compressed audio files) as the final call to AudioFileClose upon Dispose is never made, thus resulting in a number of vital pieces of information getting left out and corrupt unplayable files are created. 

This can be observed in the https://github.com/xamarin/ios-samples AudioConverterFileConverter Example using the AAC codec.

The issue can be worked around by making a call to AudioFileClose manually and supplying the AudioFile handle before disposing.

```
//included in your class
[DllImport(Constants.AudioToolboxLibrary)]
extern static OSStatus AudioFileClose(AudioFileID handle);

//included after conversion is complete before dispose methods are called
AudioFileClose(destinationFile.Handle);
```

### Steps to Reproduce

To reproduce the DisposableObject issue:

1. Create a class that inherits from DisposableObject
2. Pass true for the owns parameter in the constructor
3. Check the Owns property and see that it returns false

To reproduce the resulting audio file corruption:

1. Create an AudioFile
2. Using AudioConverter.FillComplexBuffer, fill the audio file with AAC data
3. Supply PacketTableInfo
4. Dispose of the audio file.

This can be observed by running the AudioConverterFileConverter Example in the Xamarin iOS Samples solution and attempting to convert to AAC.

### Expected Behavior
DisposableObject.Owns should return the value passed into the constructor allowing the AudioFile to save its data on dispose.

### Actual Behavior
DisposableObject.Owns always returns false. The audio file created as a result is corrupt.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.16 (build 2)
Installation UUID: e5def398-d2c8-4745-ab5f-d1ce1213562d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2 (19585)
Build 13C90

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/cmonson/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.0.1
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Wed Oct 13 17:33:01 PDT 2021
    root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 x86_64
```

### Example Project (If Possible)

https://github.com/xamarin/ios-samples
AudioConverterFileConverter Example using the AAC codec

### PR DESCRIPTION
**Pull request by rolfbjarne**
Ops...

Also add tests to avoid more oopses.

Fixes https://github.com/xamarin/xamarin-macios/issues/13646.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

File: tests/monotouch-test/AudioToolbox/AudioConverterTest.cs [hunk 1]
```diff
@@ -0,0 +1,294 @@
...
+			// retrieve the leadingFrames and trailingFrames information from the converter,
+			AudioConverterPrimeInfo primeInfo = converter.PrimeInfo;
+
+			// we have some priming information to write out to the destination file
+			// The total number of packets in the file times the frames per packet (or counting each packet's
+			// frames individually for a variable frames per packet format) minus mPrimingFrames, minus
+			// mRemainderFrames, should equal mNumberValidFrames.
+
+			AudioFilePacketTableInfo? pti_n = destinationFile.PacketTableInfo;
+			if (pti_n == null)
```
Comment (tj-devel709) [inline tests/monotouch-test/AudioToolbox/AudioConverterTest.cs:247]:
```suggestion
			if (pti_n is null)
```
Maybe

**Review by tj-devel709 — APPROVED** [review]

**Comment by rolfbjarne** [comment]
Test failures are unrelated (https://github.com/xamarin/maccore/issues/2414).
