### PR TITLE
[AppKit] Make sure NSButtons are treated as toggled objects after setting a field. Fixes #17635.

### LINKED ISSUE #17635: NSButton.CreateButton allows garbage collection of delegate
### Steps to Reproduce

This is with a net7-macos target.

1. Use NSButton.CreateButton (or CreateRadioButton, CreateCheckBox, etc) with an Action parameter
2. Don't reference the Action directly (e.g. use a lambda)
3. Wait for/trigger garbage collection
4. Try and click the button

### Expected Behavior

The delegate should be called on click

### Actual Behavior

After garbage collection, the delegate stops being called on click

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: 4a7daa4f-b0aa-47a3-ae1d-ee9e5a0c1783

Runtime
.NET 6.0.9 (64-bit)
Architecture: Arm64

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:17 UTC

Roslyn (Language Service)
5.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	7.0.100-preview.7.22377.5
	6.0.403
	6.0.400
	6.0.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	7.0.100-preview.7.22377.5
	6.0.403
	6.0.302
	3.1.425
	3.1.422
	3.1.421

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	7.0.0-preview.7.22375.6
	6.0.11
	6.0.8
	6.0.7

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	7.0.0-preview.7.22375.6
	6.0.11
	6.0.7
	6.0.17
	3.1.31
	3.1.28
	3.1.27

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.2 (21534)
Build 14C18

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:26 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:47:26 UTC

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:44:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:15:52 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
```

</details>

### Example Project (If Possible)

[DelegateBug.zip](https://github.com/xamarin/xamarin-macios/files/10843851/DelegateBug.zip)
See ViewController.cs. Console output stops working after GC.Collect.

### PR DESCRIPTION
**Pull request by rolfbjarne**
If a wrapper type has a custom field (with a non-default value), we need to
mark the instance as dirty, to make it participate in the toggle-ref
machinery, and not get collected as long as the corresponding native instance
is around (otherwise the GC will collect the value in the field).

Fixes https://github.com/xamarin/xamarin-macios/issues/17635.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

File: src/AppKit/NSButton.cs [hunk 1]
```diff
@@ -37,7 +37,14 @@
 namespace AppKit {
 
 	public partial class NSButton {
-		NSActionDispatcher? dispatcher;
+		NSObject? dispatcher;
```
Comment (haritha-mohan) [inline src/AppKit/NSButton.cs:40]: I've noticed this pattern in a few other pr's too, but why is there a separate dispatcher NSObject? Looking at the [docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/set) it makes sense to use this pattern if you want to keep the property variable private and use it for private-backing, but in this case what is the benefit to doing this rather than just using the auto-implemented property?

**Review by haritha-mohan — APPROVED** [review]

File: src/AppKit/NSButton.cs (hunk 1 above)
Comment (rolfbjarne) [reply src/AppKit/NSButton.cs:40]: > in this case what is the benefit to doing this rather than just using the auto-implemented property

In this case the purpose of the property setter is have a side effect: call MarkDirty. That's not possible for auto-implemented properties.

**Review by stephen-hawley — APPROVED** [review]
