### PR TITLE
[StoreKit] Bind AppStore.requestReview. Fixes #21410.

### LINKED ISSUE #10659: Use .NET-specific min OS versions to build native code for .NET
It looks like we're going to drop support for a few older OS versions.

In particular the new min OS versions are going to be:

* iOS: 10 (https://github.com/dotnet/runtime/issues/44654)
* tvOS 10 (https://github.com/dotnet/runtime/issues/44654)
* macOS: 10.13 (https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#macos)

We have to update our code accordingly to handle this (instead of using the min OS versions defined for legacy Xamarin)

### LINKED ISSUE #21410: SKStoreReviewController is deprecated in iOS 18, and replacement is not accesible in MAUI.
Moved from https://github.com/dotnet/maui/issues/25169

### Description

Hello,

with iOS 18 it seems that Apple deprecated SKStoreReviewController. Now every plugin and call made from SKStoreReviewController are not working. There is a replacement with AppStore.requestReview(in: scene). But from MAUI it is inaccessible. 

https://developer.apple.com/documentation/storekit/appstore/3954432-requestreview/

### Steps to Reproduce

Create an application
on ios18 invoke
```
if (UIApplication
                            .SharedApplication?
                            .ConnectedScenes?
                            .ToArray<UIScene>()?
                            .FirstOrDefault(x => x.ActivationState == UISceneActivationState.ForegroundActive) is UIWindowScene windowScene)
                    {
                        SKStoreReviewController.RequestReview(windowScene);
                        return Task.CompletedTask;
                    }
```
see that application hangs.

same code on iOS 17.5 works, create a review popup or just passes quietly.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18+

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rolfbjarne**
The existing Objective-C class to request an App Store review (SKStoreReviewController) is deprecated in Xcode 16+, and it doesn't even work on the corresponding OS versions.

The replacement API is Swift-only, but luckily it's a very simple API (just a static method), so it's possible to bind it manually.

This required a few other changes/improvements:

* Add support for Swift code in our runtime.

* Just to keep the changes to a minimum, bump the min OS version for legacy code to match the .NET min OS versions. This is because our build logic uses the legacy min versions when compiling native code (a more involved fix would be to update all the build logic to build native code to use the .NET min OS versions, but that's not the point of this PR, so I took the easy route). Fixes #10659.

I've tested the method locally, and it seems to work fine, but I've still marked
it as experimental for now. There are no unit tests because calling the method will
put up a dialog, which won't work correctly in unit tests.

Fixes https://github.com/xamarin/xamarin-macios/issues/21410.
Fixes https://github.com/xamarin/xamarin-macios/issues/10659.

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

File: runtime/swift-functions.swift [hunk 1]
```diff
@@ -0,0 +1,29 @@
+#if os(macOS)
+import AppKit
+#endif
+import Foundation
+import StoreKit
+#if !os(macOS)
+import UIKit
+#endif
+
```
Comment (stephen-hawley) [inline runtime/swift-functions.swift:9]: I don't know that this matters a lot, but you can simplify this a little bit with a type alias for the platform UI type:

```swift
#if os(macOS)
typealias PlatformScene = NSViewController
#elseif !os(tvOS)
typealias PlatformScene = UIWindowScene
#endif
@objc(XamarinSwiftFunctions)
public class XamarinSwiftFunctions : NSObject {

    @MainActor
    @objc(requestReview:)
    @available(macOS 13, iOS 16, macCatalyst 16, *)
    public static func StoreKit_RequestReview(scene: PlatformScene)
    {
        AppStore.requestReview(in: scene)
    }
}

Comment (stephen-hawley) [reply runtime/swift-functions.swift:9]: You can also use `#if canImport(UIKit)` instead of a specific platform check around `import` statements.

**Review by stephen-hawley — APPROVED** [review]

File: runtime/swift-functions.swift (hunk 1 above)
Comment (rolfbjarne) [reply runtime/swift-functions.swift:9]: I created a new PR for these changes: #21452.
