### PR TITLE
[scenekit] Correctly bind SCNHitTestOptions's SearchMode

### LINKED ISSUE #4031: SCNHitTestOptions SearchMode bound incorrectly
`SCNHitTestOptions.SearchMode` has two problems:

1. It isn't settable
2. It's incorrectly named **Option**SearchMode (should just be `SearchMode`)

(also the key is incorrectly named **Option**SearchModeKey (should just be `SearchModeKey`))

### Steps to Reproduce

1. Create `SCNHitTestOptions`
2. Try to set the `SearchMode`

### Expected Behavior

I should be able to set `SearchMode` to one of the enum values.

### Actual Behavior

There is no settable property.

Work around with

```csharp
NSDictionary.FromObjectsAndKeys (new NSObject[] { NSNumber.FromInt64 ((long)SCNHitTestSearchMode.All), NSNumber.FromBoolean (true) },
                                                 new NSObject[] { SCNHitTest.OptionSearchModeKey, SCNHitTest.BackFaceCullingKey });
```

### Environment

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 1222)
Installation UUID: 4ba352e1-73e8-4dab-a9db-28012ca05af8
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.0-preview2-26406-04
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.300-preview2-008530/Sdks
SDK Versions:
	2.1.300-preview2-008530
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.1.173 (Visual Studio Enterprise)

=== Xamarin.Android ===

Version: 8.3.0.18 (Visual Studio Enterprise)
Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 11.10.1.174 (Visual Studio Enterprise)
Hash: f4933226
Branch: d15-7
Build date: 2018-04-18 02:19:00-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705001222
Git revision: 48907c13172f883a9a64ea79b87bfc3f2d6bc146
Build date: 2018-04-20 18:20:07-04
Xamarin addins: 93dd8547539f9bdd2b69598711c4661d53ece262
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Tue Dec 19 10:52:05 PST 2017
    root:xnu-4570.47.16~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MSBuild Editor 2.0.3
Internet of Things (IoT) development (Preview) 7.1

```

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes #4031: SCNHitTestOptions SearchMode bound incorrectly
(https://github.com/xamarin/xamarin-macios/issues/4031)

### CODE REVIEW

File: src/SceneKit/SCNCompat.cs [hunk 1]
```diff
@@ -111,4 +111,16 @@ static public void AddAnimation (this ISCNAnimatable self, SCNAnimation animatio
...
 	}
 #endif
+
+#if !XAMCORE_4_0
+	[Watch (3,0)]
+	public partial class SCNHitTestOptions {
+		[Obsolete ("Use 'SearchMode' instead.")]
+		public SCNHitTestSearchMode? OptionSearchMode {
+			get {
+				return (SCNHitTestSearchMode?) GetLongValue (SCNHitTest.SearchModeKey);
```
Comment (spouliot) [inline src/SceneKit/SCNCompat.cs]: minor: it would be better to `return SeachMode;` here - in case the generated code change (e.g. extra validation) over time.

**Comment by VincentDondain** [comment]
Known issue: watchOS simulator timed out -> https://github.com/xamarin/maccore/issues/648
