### PR TITLE
Fix #9996 and #15622

### LINKED ISSUE #9996: Carplay - ios 14 Broken feature. CPListImageRowItem can't be used in CPListSection
In the carplay framework, it's impossible to use the new CPListImageRowItem from ios 14 with the current version of xamarin-ios-14.2.0.12.

In the Apple ios api, the init function for CPListSection is (NSArray<id<CPListTemplateItem>> *)items; 
Both CPListItem and CPListImageRowItem implements CPListTemplateItem via CPSelectableListItem, but the Xamarin API doesn't allow CPListTemplateItem in the constructor.

### Actual Behavior
In Xamarin, CPListSection constructor is takes a CPListItem [] items, but CPListImageRowItem doesn't inherit from this interface. 
Both CPListItem and CPListImageRowItem have the CPSelectableListItem interface. 
We can't create a CPListSection with CPListImageRowItem

### Expected Behavior
We should be able to create CPListSection with CPListTemplateItem. The binding should probably be change to make
CPListSection constructor take an array of CPListTemplateItem instead of CPListItem

### Workaround

https://github.com/xamarin/xamarin-macios/issues/9996#issuecomment-1182188805

### PR DESCRIPTION
**Pull request by janwiebe-jump**
As discussed in #9996 the CPListSection constructors are not fully correct, since the CPListImageRowItem can't be added to it, which is possible in the native iOS SDK.
This PR fixes that. With that, also #15622 seems to be fixed.

### CODE REVIEW

File: src/carplay.cs [hunk 1]
```diff
@@ -573,10 +573,10 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
 	interface CPListSection : NSSecureCoding {
 
 		[Export ("initWithItems:header:sectionIndexTitle:")]
-		NativeHandle Constructor (CPListItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
+		NativeHandle Constructor (ICPListTemplateItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
```
Comment (mandel-macaque) [inline src/carplay.cs:576]: The changes are correct but I believe they are a breaking change which means that we have to provide a path (even when the constructor was wrong). We need to do the following:
```suggestion
#if !XAMCORE_5_0
  		[Export ("initWithItems:header:sectionIndexTitle:")]
  		[Obsolete ("Use  'CPListSection (ICPListTemplateItem [], string, string)' constructor instead.")]
  		NativeHandle Constructor (CPListItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
#endif
		[Export ("initWithItems:header:sectionIndexTitle:")]
		NativeHandle Constructor (ICPListTemplateItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
```

Comment (mandel-macaque) [reply src/carplay.cs:576]: @dalexsoto  there was a way to allow to methods to have the same selector, right? I don't want to make this change more complicated that it is.

File: src/carplay.cs [hunk 2]
```diff
@@ -573,10 +573,10 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
...
 
 		[Export ("initWithItems:")]
-		NativeHandle Constructor (CPListItem [] items);
+		NativeHandle Constructor (ICPListTemplateItem [] items);
```
Comment (mandel-macaque) [inline src/carplay.cs:579]: Same as the above comment.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
I believe we need to Obsolete and leave the old ones while providing a path for users to upgrade rather that break the API. Nevertheless I have triggered the build to confirm the API will be broken.

**Comment by mandel-macaque** [comment]
@janwiebe-jump Thanks for the fix! I have some small concerts which I left in the review.

**Comment by janwiebe-jump** [comment]
Thanks @mandel-macaque , good catch indeed. 
I re-added the old constructors, and added the Obsolete attribute.
Next to that, I also added the `Items[]` property (besides the existing) to conform to the iOS api.

File: src/carplay.cs [hunk 3]
```diff
@@ -573,11 +573,19 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
 	interface CPListSection : NSSecureCoding {
 
 		[Export ("initWithItems:header:sectionIndexTitle:")]
+		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [], string, string)' constructor instead.")]
 		NativeHandle Constructor (CPListItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
```
Comment (mandel-macaque) [inline src/carplay.cs:577]: Lets wrap the wrong API in !XAMCORE_5_0 so that we can remove it the next time we have breaking changes.
```suggestion
#if !XAMCORE_5_0
		[Export ("initWithItems:header:sectionIndexTitle:")]
		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [], string, string)' constructor instead.")]
		NativeHandle Constructor (CPListItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
#endif
```

File: src/carplay.cs [hunk 4]
```diff
@@ -573,11 +573,19 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
...
 
 		[Export ("initWithItems:")]
+		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [])' constructor instead.")]
 		NativeHandle Constructor (CPListItem [] items);
```
Comment (mandel-macaque) [inline src/carplay.cs:581]: Same:
```suggestion
#if !XAMCORE_5_0
		[Export ("initWithItems:")]
		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [])' constructor instead.")]
		NativeHandle Constructor (CPListItem [] items);
#endif
```

File: src/carplay.cs [hunk 5]
```diff
@@ -589,8 +597,12 @@ interface CPListSection : NSSecureCoding {
 		string SectionIndexTitle { get; }
 
 		[Export ("items", ArgumentSemantic.Copy)]
+		[Obsolete ("Use 'Items : ICPListTemplateItem []' instead.")]
 		CPListItem [] Items { get; }
```
Comment (mandel-macaque) [inline src/carplay.cs:601]: Same:
```suggestion
#if !XAMCORE_5_0
		[Export ("items", ArgumentSemantic.Copy)]
		[Obsolete ("Use 'Items : ICPListTemplateItem []' instead.")]
		CPListItem [] Items { get; }
#endif
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
We still need to wrap the old api with a #if so that next time we have the chance to break APIs we do not expose something wrong :)

**Review by mandel-macaque — APPROVED** [review]
Lets see what the tests got to see. But the changes look good to me.

**Comment by janwiebe-jump** [comment]
Hmm, the `Items` property

> Lets see what the tests got to see. But the changes look good to me.

Thanks. I am curious how the duplicate `Items[]` works out

**Comment by mandel-macaque** [comment]
@janwiebe-jump I suspect is going to fail, but it an easy fix (ugly, but doable). I'll keep an eye as according tot he failures I might propose a code change.

File: src/carplay.cs [hunk 6]
```diff
@@ -588,8 +600,14 @@ interface CPListSection : NSSecureCoding {
...
 		string SectionIndexTitle { get; }
 
+#if !XAMCORE_5_0
 		[Export ("items", ArgumentSemantic.Copy)]
+		[Obsolete ("Use 'Items : ICPListTemplateItem []' instead.")]
 		CPListItem [] Items { get; }
+#endif
+
+		[Export ("items", ArgumentSemantic.Copy)]
+		ICPListTemplateItem [] Items { get; }
```
Comment (mandel-macaque) [inline src/carplay.cs:610]: As I expected, having two properties with the same name results in an error:
```
carplay.cs(610,26): error CS0102: The type 'CPListSection' already contains a definition for 'Items'
```
The following should fix the issue:
```suggestion
#if !XAMCORE_5_0
		[Sealed]
		[Export ("items", ArgumentSemantic.Copy)]
		[Obsolete ("Use 'Items2 : ICPListTemplateItem []' instead.")]
		CPListItem [] Items { get; }
#eendif

		[Export ("items", ArgumentSemantic.Copy)]
#if !XAMCORE_5_0
		ICPListTemplateItem [] Items2 { get; }
#else
		ICPListTemplateItem [] Items { get; }
#endif
```
That means we have Items2 but in the future it will be Items.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/carplay.cs [hunk 7]
```diff
@@ -572,11 +572,23 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
 	[DisableDefaultCtor]
 	interface CPListSection : NSSecureCoding {
 
+#if !XAMCORE_5_0
 		[Export ("initWithItems:header:sectionIndexTitle:")]
+		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [], string, string)' constructor instead.")]
```
Comment (dalexsoto) [inline src/carplay.cs:577]:
```suggestion
		[Obsolete ("Use '.ctor (ICPListTemplateItem [], string, string)' constructor instead.")]
```

File: src/carplay.cs [hunk 8]
```diff
@@ -572,11 +572,23 @@ interface CPListItem : CPSelectableListItem, NSSecureCoding {
...
 		NativeHandle Constructor (CPListItem [] items, [NullAllowed] string header, [NullAllowed] string sectionIndexTitle);
+#endif
 
+#if !XAMCORE_5_0
 		[Export ("initWithItems:")]
+		[Obsolete ("Use 'CPListSection (ICPListTemplateItem [])' constructor instead.")]
```
Comment (dalexsoto) [inline src/carplay.cs:583]:
```suggestion
		[Obsolete ("Use '.ctor (ICPListTemplateItem [])' constructor instead.")]
```

File: src/carplay.cs [hunk 9]
```diff
@@ -588,8 +600,19 @@ interface CPListSection : NSSecureCoding {
 		[NullAllowed, Export ("sectionIndexTitle")]
 		string SectionIndexTitle { get; }
 
+#if !XAMCORE_5_0
+		[Sealed]
 		[Export ("items", ArgumentSemantic.Copy)]
+		[Obsolete ("Use 'Items2 : ICPListTemplateItem []' instead.")]
 		CPListItem [] Items { get; }
+#eendif
```
Comment (dalexsoto) [inline src/carplay.cs:608]:
```suggestion
#endif
```

**Review by dalexsoto — CHANGES_REQUESTED** [review]

**Comment by janwiebe-jump** [comment]
The build is failing, is there anything I can do to fix it?

**Comment by tj-devel709** [comment]
@janwiebe-jump 
Seems that the build is failing due to:
```
/Library/Frameworks/Xamarin.iOS.framework/Versions/15.13.0.27/src/Xamarin.iOS/build/dotnet/ios/generated-sources/CarPlay/CPListSection.g.cs(157): error MT4119: Could not register the selector 'initWithItems:header:sectionIndexTitle:' of the member 'CarPlay.CPListSection..ctor' because the selector is already registered on the member '.ctor'.
		
/Library/Frameworks/Xamarin.iOS.framework/Versions/15.13.0.27/src/Xamarin.iOS/build/dotnet/ios/generated-sources/CarPlay/CPListSection.g.cs(184): error MT4119: Could not register the selector 'initWithItems:' of the member 'CarPlay.CPListSection..ctor' because the selector is already registered on the member '.ctor'.
```

**Comment by chamons** [comment]
I suspect that error is due to double exporting the ctor selectors. Let me take a look.

**Comment by chamons** [comment]
I believe I have corrected the PR. It at least compiles for me. I will check tomorrow.

**Comment by janwiebe-jump** [comment]
Hi all, thanks for your reviews and input.
I would like to know what is next to get this merged and released.
It blocks the release of our app. Is there anything I can do?
Thanks!

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
Looks like our CI is having a hard time :(

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
It doesn't compile:

```
build/dotnet/ios/generated-sources/CarPlay/CPListSection.g.cs(387,42): error CS8115: A throw expression is not allowed in this context.
build/dotnet/ios/generated-sources/CarPlay/CPListSection.g.cs(387,48): error CS0039: Cannot convert type 'System.InvalidOperationException' to 'Foundation.NSArray' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion
make[1]: *** [build/dotnet/ios/32/Microsoft.iOS.dll] Error 1
```

**Comment by rolfbjarne** [comment]
Thanks a lot for your help!

**Comment by janwiebe-jump** [comment]
Hi @rolfbjarne,
Thanks a lot, also for your ant the team's assistance!
Will this also be released as a xamarin-ios version that I can use in my Xamarin iOS (Forms) app? We can't yet move to MAUI / .NET 6, due to a lot of dependencies, so I would strongly prefer a xamarin-ios.pkg version with this fix included, so we can release our CarPlay app.
Thanks so much!

**Comment by rolfbjarne** [comment]
@janwiebe-jump yes, this will be released in a xamarin-ios.pkg (when we release support for Xcode 14, the packages will contain your fix)
