### PR TITLE
[UIKit] Fix properties in UIConfigurationColorTransformer Type

### LINKED ISSUE #16665: [UIKit] Change properties to be internal in type UIConfigurationColorTransformer
_PreferredTint and _MonochromeTint properties are exposed but should be internal.

### PR DESCRIPTION
**Pull request by haritha-mohan**
Changing properties to be internal
Fixes #16665

### CODE REVIEW

File: src/uikit.cs [hunk 1]
```diff
@@ -23956,11 +23956,35 @@ interface UIConfigurationColorTransformer {
...
 
+#if !XAMCORE_5_0
+		[Internal]
+		[Field ("UIConfigurationColorTransformerPreferredTint")]
+		IntPtr _InternalPreferredTint { get; }
+
+		[Obsolete ("Use the '_PreferredTint' property instead.")]
+		[Wrap ("_InternalPreferredTint")]
 		[Field ("UIConfigurationColorTransformerPreferredTint")]
 		IntPtr _PreferredTint { get; }
```
Comment (rolfbjarne) [inline src/uikit.cs:23967]: This is a bit of a special case compared to the other fixes you've done.

These fields are supposed to be internal, and then manually exposed (without the underscore) here:

https://github.com/xamarin/xamarin-macios/blob/3b839e15514826b3bd6d61b953eb684c0c897116/src/UIKit/UIConfigurationColorTransformer.cs#L20-L39

but it seems the initial implementation forgot to make these fields internal (but still added the non-underscored public version).

That means the fix is to:

1. Make them internal in XAMCORE_5_0
2. Add an Obsolete attribute (in !XAMCORE_5_0) pointing to the non-underscore version (which already exists - see the code I linked to above).

In particular there's no need to add a new and correct implementation, because that already exists.

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]
