### PR TITLE
[UIKit] Sprinkle NullAllowed on UIImage according to Apple's headers. Fixes #9597.

### LINKED ISSUE #9597: Incorrect suggestion by Visual Studio / ReSharper to remove null check
### Steps to Reproduce

1. Use Visual Studio with ReSharper (in my case VS 2019 on Windows and R# 2020.2.1)
2. Paste the code snippet below

```c#
public Size GetImageSize(string filePath)
{
    var image = UIImage.FromFile(filePath);
    return image != null ? new Size(image.Size.Width, image.Size.Height) : Size.Zero;
}
```

### Expected Behavior
No warning shown.

### Actual Behavior
The IDE / ReSharper shows a warning about a superfluous null check. This is incorrect since `UIImage.FromFile()` can indeed return `null` which is also mentioned in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiimage.fromfile) and by IntelliSense.
grafik

This is probably only one false positive. Please check if the C# bindings in Xamarin.iOS can be improved to prevent such warnings and help tools like ReSharper.

### Environment

```
Microsoft Visual Studio Professional 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   16.7.532.28833
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2020.1.3   Build 201.0.20200515.122017
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/9597.

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

File: src/uikit.cs [hunk 1]
```diff
@@ -7360,7 +7369,7 @@ interface UIImage : NSSecureCoding
 		[iOS (8,0)]
 		[Export ("imageAsset")]
 		[ThreadSafe]
-		UIImageAsset ImageAsset { get; }
+		UIImageAsset ImageAsset { [NullAllowed] get; }
```
Comment (mandel-macaque) [inline src/uikit.cs:7372]: Question here, not need to change. Why on the getter and not in the property. In case we add a setter in the future, we won't need to edit anything else.

Comment (rolfbjarne) [reply src/uikit.cs:7372]: There's no reason really, that's just how I ended up doing it. Presumably it would work just as well on the property.

**Review by dalexsoto — APPROVED** [review]

**Review by spouliot — APPROVED** [review]
Sprinkle is the right term :)

```
xtro-sharpie poupou$ git grep "missing-null-allowed" . | uniq | wc -l
    3335
```

and manual bindings requires an manual audit too...

**Review by whitneyschmidt — APPROVED** [review]
