### PR TITLE
[tests] Created Test to find Getters that throw Exceptions directly.

### LINKED ISSUE #16669: Cecil tests to verify that we don't throw exceptions in property getters
Ref: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN

In particular:

> ❌ AVOID throwing exceptions from property getters.

The idea is to add a cecil tests that verifies that we don't throw exceptions (this can probably just check for the `throw` IL code in the IL for the method) in property getters.

There will probably be a few cases where exceptions are acceptable/expected/we can't change (yet), so a skip mechanism would be needed.

### PR DESCRIPTION
**Pull request by dustin-wojciechowski**
Examines IL for Property Getters for throw opcode. Adapted from Haritha's Capitalization Test. Looking for some feedback about what I'm missing, code style, etc.

Wasn't quite sure how we wanted to do a skip. Easy way would be string match, but there's over 5,000 properties that currently throw (mostly PlatformNotSupportedExceptions). Here's what an excerpt of what console output looks like:

Console output:
 Exceptions found in Getters:
[VNDocumentCameraScan, Title]
[VNDocumentCameraViewController, WeakDelegate]

... and so on.

I would also have to think how to check for getters that call other methods that throw exceptions.

Fixes #16669

### CODE REVIEW

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		[TestCaseSource (typeof (Helper), nameof (Helper.NetPlatformAssemblies))]
+		[Test]
+		public void TestForAssembliesWithGetterExceptions (string assemblyPath)
+		{
+			Dictionary<string, string> propertiesWithGetterExceptions = new ();
+
+			if (assemblyCache.TryGetValue (assemblyPath, out var cache)) {
+				foreach (TypeDefinition type in cache.MainModule.Types) {
+					foreach (PropertyDefinition property in type.Properties) {
+						if (!IsMemberObsolete (property) && VerifyIfGetterThrowsException (property.GetMethod))
```
Comment (haritha-mohan) [inline tests/cecil-tests/GetterExceptionTest.cs:64]: not sure if this is necessary, but not all properties have getters/setters, so sometimes it's good to double check it exists before passing it as an argument

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+		}
+
+		bool VerifyIfGetterThrowsException (MethodDefinition methodDefinition)
+		{
+			if (methodDefinition is null || methodDefinition.Body is null)
+				return false;
+
+			foreach (var inst in methodDefinition.Body.Instructions) {
+				if (inst.OpCode == OpCodes.Throw) {
+					return true;
```
Comment (haritha-mohan) [inline tests/cecil-tests/GetterExceptionTest.cs:48]:
```suggestion
					return inst.OpCode == OpCodes.Throw;
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+using NUnit.Framework;
+using System.Linq;
+using Mono.Cecil.Cil;
+using Xamarin.Utils;
+using Xamarin.Tests;
+
+namespace Cecil.Tests {
+	[TestFixture]
+	public class GetterExceptionTest {
+		Dictionary<string, AssemblyDefinition> assemblyCache = new ();
```
Comment (haritha-mohan) [inline tests/cecil-tests/GetterExceptionTest.cs:13]:
```suggestion
		Dictionary<string, AssemblyDefinition> assemblyCache = new Dictionary<string, AssemblyDefinition> ();
```

Comment (dustin-wojciechowski) [reply tests/cecil-tests/GetterExceptionTest.cs:13]: Using new this way is new (pun not intended) to C# 9.0: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#:~:text=20%3B%20third%3A%2030-,Beginning,-with%20C%23%209.0. 

It's a way to avoid using the var keyword (which can be a touchy topic lol). If it doesn't fit the code style for the team though, I can use var or keep the verbosity.

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+			return false;
+		}
+
+		[TestCaseSource (typeof (Helper), nameof (Helper.NetPlatformAssemblies))]
+		[Test]
+		public void TestForAssembliesWithGetterExceptions (string assemblyPath)
+		{
+			Dictionary<string, string> propertiesWithGetterExceptions = new ();
+
+			if (assemblyCache.TryGetValue (assemblyPath, out var cache)) {
```
Comment (rolfbjarne) [inline tests/cecil-tests/GetterExceptionTest.cs:61]: I don't think you need the cache of assemblies for this test (Haritha's test was more complex and there was a use for it), you can just call `Helper.GetAssembly (assemblyPath)` directly.

**Review by rolfbjarne — CHANGES_REQUESTED** [review]
I think throwing PlatformNotSupportedException is OK in a property getter, so if you could ignore those (in VerifyIfGetterThrowsException), we'll see then what's left.

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+
+			return member.CustomAttributes.Any ((m) =>
+					m.AttributeType.Name == "ObsoleteAttribute" ||
+					m.AttributeType.Name == "AdviceAttribute" ||
+					m.AttributeType.Name == "ObsoletedOSPlatformAttribute");
+		}
+
+		bool VerifyIfGetterThrowsException (MethodDefinition methodDefinition)
+		{
+			if (methodDefinition is null || methodDefinition.Body is null)
```
Comment (tj-devel709) [inline tests/cecil-tests/GetterExceptionTest.cs:43]:
```suggestion
			if (methodDefinition?.Body is null)
```
A little more concise :)

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+				return false;
+
+			foreach (var inst in methodDefinition.Body.Instructions) {
+				if (inst.OpCode == OpCodes.Throw) {
+					return true;
+				}
```
Comment (tj-devel709) [inline tests/cecil-tests/GetterExceptionTest.cs:49]:
```suggestion
				if (inst.OpCode == OpCodes.Throw)
					return true;
```
really nitpicky but could remove these

**Review by tj-devel709 — COMMENTED** [review]
Looks great! I just have a few style suggestions!

**Comment by dustin-wojciechowski** [comment]
In tests, three exceptions came up when run against the Implementation Assemblies:

"AudioQueueException",
"ModelNotImplementedException",
"You_Should_Not_Call_base_In_This_Method"

I was unsure which exceptions we should skip and what we need to address. I put these in the skip section to ensure that the tests passed. 

Was not sure if that should be captured in a different issue or to try and fix them in this PR, it comes to about 36 instances of exceptions in getters, with all but three being ModelNotImplementedExceptions.

File: src/uikit.cs [hunk 7]
```diff
@@ -12970,9 +12970,9 @@ interface UIStringAttributeKey {
 		[iOS (7, 0)]
 		[Internal, Field ("NSDocumentTypeDocumentAttribute")]
 		NSString NSDocumentTypeDocumentAttribute { get; }
-	//
```
Comment (dustin-wojciechowski) [inline src/uikit.cs:12973]: Not sure how this edit came about :(

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+			if (methodDefinition?.Body is null)
+				return false;
+
+			foreach (Instruction? inst in methodDefinition.Body.Instructions) {
+				if (inst.OpCode == OpCodes.Newobj) {
+					string? baseType = ((inst.Operand as MemberReference)
+						?.DeclaringType as TypeDefinition)
+						?.BaseType.Name;
+
+					if (baseType != null && baseType.Equals ("Exception")) {
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:43]:
```suggestion
					if (baseType is not null && baseType.Equals ("Exception")) {
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+						string? exceptionType = (inst.Operand as MemberReference)?.DeclaringType.Name;
+						if (exceptionType != null && !exceptionsToSkip.Contains (exceptionType)) {
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:45]:
```suggestion
						if (exceptionType is not null && !exceptionsToSkip.Contains (exceptionType)) {
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+		}
+
+		[TestCaseSource (typeof (Helper), nameof (Helper.NetPlatformImplementationAssemblies))]
+		[Test]
+		public void TestForAssembliesWithGetterExceptions (string assemblyPath)
+		{
+			Dictionary<string, string> propertiesWithGetterExceptions = new ();
+			AssemblyDefinition assembly = Helper.GetAssembly (assemblyPath);
+
+			if (assembly != null) {
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:63]:
```suggestion
			if (assembly is not null) {
```
You can invert the if, since Assert will stop the execution (throws an exception, then it gets caught by the test runner).

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+		}
+
+		bool VerifyIfGetterThrowsException (MethodDefinition methodDefinition, out string exceptionMessage)
+		{
+			exceptionMessage = string.Empty;
+			if (methodDefinition?.Body is null)
+				return false;
+
+			foreach (Instruction? inst in methodDefinition.Body.Instructions) {
+				if (inst.OpCode == OpCodes.Newobj) {
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:38]:
```suggestion
				if (inst.OpCode == OpCodes.Newobj) {
```
You are declaring inst as nullable, becase you are not using ? inst.OpCode can throw a NRE.

File: src/uikit.cs (hunk 7 above)
Comment (mandel-macaque) [reply src/uikit.cs:12973]: That is the auto format tool :)

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+using Xamarin.Tests;
+
+namespace Cecil.Tests {
+	[TestFixture]
+	public class GetterExceptionTest {
+		readonly HashSet<string> exceptionsToSkip = new ()
+		{
+			"AudioQueueException",
+			"ModelNotImplementedException",
+			"You_Should_Not_Call_base_In_This_Method"
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:17]: Add a "," and the end, that way the next diff will be smaller. 
```suggestion
			"You_Should_Not_Call_base_In_This_Method",
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 13]
```diff
@@ -0,0 +1,81 @@
...
+		bool IsMemberObsolete (ICustomAttributeProvider member)
+		{
+			if (member is null || !member.HasCustomAttributes)
+				return false;
+
+			return member.CustomAttributes.Any ((m) =>
+					m.AttributeType.Name == "ObsoleteAttribute" ||
+					m.AttributeType.Name == "AdviceAttribute" ||
+					m.AttributeType.Name == "ObsoletedOSPlatformAttribute");
+		}
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:29]: I believe we can write everything in a single line, member?.CustomAttributes?.Any() == true should do the trick. If member is null and custom attrs are null, null != true. Any will only be executed if CustomAttrs is not null.
```suggestion
		bool IsMemberObsolete (ICustomAttributeProvider member)
		    => member?.CustomAttributes?.Any ((m) =>
					m.AttributeType.Name == "ObsoleteAttribute" ||
					m.AttributeType.Name == "AdviceAttribute" ||
					m.AttributeType.Name == "ObsoletedOSPlatformAttribute") == true; // can be null or false. And null != true
```

File: src/uikit.cs (hunk 7 above)
Comment (dalexsoto) [reply src/uikit.cs:12973]: No worries this is the result of a missmatch, there is another PR in progress https://github.com/xamarin/xamarin-macios/pull/16971 that fixes this

File: tests/cecil-tests/GetterExceptionTest.cs (hunk 11 above)
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:38]: Maybe we could do something nice with the is operator in this case:
```suggestion
				if (inst?.OpCode == OpCodes.Newobj && inst.Operand is MemberReference reference) {
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
Few comments. I believe that if you add #nullable enable in the test class you'll get a few warnings that will need to be cleaned.

File: src/uikit.cs (hunk 7 above)
Comment (rolfbjarne) [reply src/uikit.cs]: This has been fixed now.

File: tests/cecil-tests/GetterExceptionTest.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (rolfbjarne) [reply tests/cecil-tests/GetterExceptionTest.cs:43]: This doesn't seem to catch classes that aren't direct descendants of System.Exception (the base type of System.ArgumentOutOfRangeException is System.ArgumentException, not System.Exception).

I think you need to iterate over all the base types checking if any of them are System.Exception.

File: tests/cecil-tests/GetterExceptionTest.cs (hunk 13 above)
Comment (mandel-macaque) [reply tests/cecil-tests/GetterExceptionTest.cs]:
```csharp
"ObsoletedOSPlatformAttribute") == true;
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 14]
```diff
@@ -0,0 +1,66 @@
+using System;
+using Mono.Cecil;
+using System.Collections.Generic;
+using NUnit.Framework;
+using System.Linq;
+using Mono.Cecil.Cil;
+using Xamarin.Utils;
+using Xamarin.Tests;
+
```
Comment (mandel-macaque) [inline tests/cecil-tests/GetterExceptionTest.cs:9]:
```suggestion
#nullable enable
```

**Review by mandel-macaque — APPROVED** [review]

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+					}
+				}
+			}
+
+			return false;
+		}
+
+		[TestCaseSource (typeof (Helper), nameof (Helper.NetPlatformImplementationAssemblies))]
+		[Test]
+		public void TestForAssembliesWithGetterExceptions (string assemblyPath)
```
Comment (rolfbjarne) [inline tests/cecil-tests/GetterExceptionTest.cs:49]: The Helper API changed a little bit (https://github.com/xamarin/xamarin-macios/commit/081505b173d011d583bb2d7b3c54afcaf8ae59ae), so now it should be something like:

```suggestion
		[TestCaseSource (typeof (Helper), nameof (Helper.NetPlatformImplementationAssemblyDefinitions))]
		[Test]
		public void TestForAssembliesWithGetterExceptions (AssemblyInfo info)
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 16]
```diff
@@ -0,0 +1,67 @@
...
+		{
+			Dictionary<string, string> propertiesWithGetterExceptions = new ();
+			AssemblyDefinition assembly = Helper.GetAssembly (assemblyPath);
```
Comment (rolfbjarne) [inline tests/cecil-tests/GetterExceptionTest.cs:52]: And:

```suggestion
			AssemblyDefinition assembly = info.Assembly;
```

File: tests/cecil-tests/GetterExceptionTest.cs [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+		bool VerifyIfGetterThrowsException (MethodDefinition methodDefinition, out string exceptionMessage)
+		{
+			exceptionMessage = string.Empty;
+			if (!methodDefinition.HasBody)
+				return false;
+
+			foreach (Instruction? inst in methodDefinition.Body.Instructions) {
+				if (inst?.OpCode == OpCodes.Newobj && inst?.Operand is MemberReference reference) {
+					TypeReference? baseType = (reference.DeclaringType as TypeDefinition)?.BaseType;
+					if (baseType is not null && baseType.Is ("System", "Exception") &&
```
Comment (rolfbjarne) [inline tests/cecil-tests/GetterExceptionTest.cs:36]: This doesn't catch exceptions that aren't direct subclasses of System.Exception (for instance System.ArgumentNullException, whose base type is System.ArgumentException, and not System.Exception).

You'd need to implement a recursive function like this (except checking for System.Exception instead of Foundation.NSObject): https://github.com/xamarin/xamarin-macios/blob/fc487c2f5904dd1e0c6da8b7376a75234c902f8a/tests/cecil-tests/ConstructorTest.cs#L191-L200

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

**Comment by dustin-wojciechowski** [comment]
Added recursive check. Did notice that the test did not find any new exceptions, but I'll go through the codebase and see if I can find an example to prove it wrong.

**Review by rolfbjarne — APPROVED** [review]
