### PR TITLE
[mtouch] Unify code to detect and handle frameworks that aren't supported in the simulator. Fixes #4422.

### LINKED ISSUE #4422: Build fails with "no type or protocol named 'MTKViewDelegate'" after adding mtouch argument --registrar:static
### Steps to Reproduce

1. I'm trying to add the mtouch argument `--registrar:static` to my native iOS xamarin project but it results in the build errors from below. I would like to add the argument because it solves another build error after I've added the [Xamarin.Firebase.iOS.Analytics nuget package](https://github.com/xamarin/GoogleApisForiOSComponents/tree/master/Firebase.Analytics/component) to the project. The build is only failing for the simulator, builds for devices are fine.

### Expected Behavior

The build succeeds without any problems.

### Actual Behavior

The build fails with errors like 
```
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6579,53): error G9EBEE159: no type or protocol named 'MTKViewDelegate'
    @interface MetalKit_Rx_MTKViewDelegateRx : NSObject<MTKViewDelegate> {
                                                        ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6585,25): error G5EC502AB: expected a type
    -(void) drawInMTKView:(MTKView *)p0;
                                   ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6586,19): error G5EC502AB: expected a type
    -(void) mtkView:(MTKView *)p0 drawableSizeWillChange:(CGSize)p1;
                             ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m(27402,99): error GC871EEFB: unknown type name 'MTKView'
    static void native_to_managed_trampoline_494 (id self, SEL _cmd, MonoMethod **managed_method_ptr, MTKView * p0, uint32_t token_ref)
                                                                                                      ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m(27449,99): error GC871EEFB: unknown type name 'MTKView'
    static void native_to_managed_trampoline_495 (id self, SEL _cmd, MonoMethod **managed_method_ptr, MTKView * p0, CGSize p1, uint32_t token_ref)
```

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: d36b125f-2ca5-46ea-b457-c9cb84803a65
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/tobiasbuchholz/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.0 rc2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.5
```

### Build Logs

[Build Logs Gist](https://gist.github.com/TobiasBuchholz/76ba0e18544851ad198b89dbd5b6f1f8)

### Example Project (If Possible)

Since the project is for work I can't share it unfortunately. I've tried to create a sample project with the same packages but for this project the build succeeds without any problems.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Unify the code to detect frameworks that aren't supported in the simulator (we
had switches in two places, now this data is stored per framework).

Also remove some of the Metal frameworks for some of the platforms from these
lists (since they're now available in the simulator in some cases), which
fixes #4422.

It also seems CoreAudioKit is now available in the simulator (it wasn't in the
first Xcode 7 beta, but apparently added in a later beta. This made our
exclusion incorrect, but we never noticed).

https://github.com/xamarin/xamarin-macios/issues/4422

### CODE REVIEW

File: tools/common/Frameworks.cs [hunk 1]
```diff
@@ -267,9 +269,9 @@ public static Frameworks GetiOSFrameworks (Application app)
 
 				{ "ARKit", "ARKit", 11 },
 				{ "CoreNFC", "CoreNFC", 11 },
-				{ "DeviceCheck", "DeviceCheck", 11 },
+				{ "DeviceCheck", "DeviceCheck", new Version (11, 0), new Version (int.MaxValue, int.MaxValue) /* no headers provided for simulator */ },
```
Comment (spouliot) [inline tools/common/Frameworks.cs]: let's create a constant to ease readability (and avoid unrequited extra instances), e.g.

```
// used when headers for a framework is not provided for the simulator
static Version NotAvailableInSimulator = new Version (int.MaxValue, int.MaxValue)'
```

Comment (spouliot) [reply tools/common/Frameworks.cs]: Also this file is now included in tests so that new constant can be used to create a canary test - one that will tell us if/when a framework becomes available in a newer version of Xcode.

Another good one (it happened before) would be to detect the others framework are present, like we expect them (e.g. if one gets removed by mistake).

Comment (rolfbjarne) [reply tools/common/Frameworks.cs]: > let's create a constant to ease readability (and avoid unrequited extra instances)

Fixed.

> Also this file is now included in tests so that new constant can be used to create a canary test - one that will tell us if/when a framework becomes available in a newer version of Xcode.
> 
> Another good one (it happened before) would be to detect the others framework are present, like we expect them (e.g. if one gets removed by mistake).

I think this can be done in a separate PR.
