### PR TITLE
[appkit] Make NSCell and NSControl 'Formatter' accept null

### LINKED ISSUE #6032: NSTextField.Formatter missing null-allowed
### Steps to Reproduce

1.  Set `NSTextField`'s `Formatter` to `NSNumberFormatter`
2. Set `NSTextField`'s `Formatter` to null.
3. Observe ArgumentNullException

### Expected Behavior
No Exception

### Actual Behavior
ArgumentNullException

### Environment
any

```
```

### Example Project (If Possible)

Swift seems to have nullable here. No special annotation on objc.
https://developer.apple.com/documentation/appkit/nscontrol/1428887-formatter
image

### PR DESCRIPTION
**Pull request by VincentDondain**
- Fixes #6032: NSTextField.Formatter missing null-allowed
  (https://github.com/xamarin/xamarin-macios/issues/6032)
- Swift seems to have nullable [here](https://developer.apple.com/documentation/appkit/nscontrol/1428887-formatter).

### CODE REVIEW

File: src/appkit.cs [hunk 1]
```diff
@@ -4795,7 +4795,7 @@ partial interface NSControl {
 		[Export ("font")]
 		NSFont Font { get; set; }
 
-		[Export ("formatter", ArgumentSemantic.Retain)]
+		[Export ("formatter", ArgumentSemantic.Retain), NullAllowed]
 		NSObject Formatter { get; set; }
```
Comment (spouliot) [inline src/appkit.cs]: According to the latest doc (did not check headers) it's an `NSFormatter` or a subclass (`__kindof`) so, to avoid forgetting it, maybe
```csharp
#if XAMCORE_4_0
NSFormatter Formatter { get; set; }
#else
NSObject Formatter { get; set; }
#endif
```

**Comment by VincentDondain** [comment]
Known issue: https://github.com/xamarin/maccore/issues/1595
