### PR TITLE
[Foundation] Fix capitalization mistake in type NSBundle

### LINKED ISSUE #16486: [Foundation] Capitalization mistake in type NSBundle
Property name incorrectly capitalized.

Actual: _AllBundles
Expected: AllBundles

### PR DESCRIPTION
**Pull request by haritha-mohan**
Fixes #16486

### CODE REVIEW

File: src/foundation.cs [hunk 1]
```diff
@@ -9832,9 +9832,22 @@ partial interface NSBundle {
 		[Export ("bundleWithIdentifier:")][Static]
 		NSBundle FromIdentifier (string str);
 
+#if !XAMCORE_5_0
+		[Internal]
 		[Export ("allBundles")][Static]
+		NSArray _InternalAllBundles { get; }
+
+		[Obsolete ("Use the 'allBundles' property instead.")]
```
Comment (rolfbjarne) [inline src/foundation.cs:9840]: We use the C# name in obsolete messages:

```suggestion
		[Obsolete ("Use the 'AllBundles' property instead.")]
```

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
