### PR TITLE
[runtime] Always release blocks on the main thread. Fixes #4130.

### LINKED ISSUE #4130: Reproducible native crash bug with WKWebView in latest Xamarin.iOS
(Coming from Bugzilla we were at a loss where to post this and wrongly submitted this bug report to the Xamarin forums first, sorry about that).

Loading a WKWebView with a HTML string twice using a WKNavigationDelegate that overrides DecidePolicy crashes Xamarin.

### Steps to Reproduce

Create a new project with this UIVIewController
```
    public class TestController : UIViewController
    {
        class Navigator : WKNavigationDelegate
        {
            public override void DecidePolicy(WKWebView webView, WKNavigationAction navigationAction, Action<WKNavigationActionPolicy> decisionHandler)
            {
		decisionHandler(WKNavigationActionPolicy.Cancel);
	    }
        }

        WKWebView page;

        void AddPage()
        {
            page?.RemoveFromSuperview();
            page = new WKWebView(new CGRect(0, 0, 400, 400), new WKWebViewConfiguration());
            page.NavigationDelegate = new Navigator();
            page.LoadHtmlString("", new NSUrl(NSBundle.MainBundle.ResourceUrl + ""));

            View.AddSubview(page);

            Console.WriteLine("OK");
        }

        public override void ViewDidLoad()
        {
            UIButton button = new UIButton(new CGRect(200, 500, 0, 0));

            button.SetTitle("Add page", UIControlState.Normal);
            button.SizeToFit();
            button.TouchUpInside += (sender, e) => AddPage();

            View.AddSubview(button);
        }
    }
```
Pressing the button should add an empty webview to the view controller and print "OK" to stdout. This works the first time, but waiting a second and pressing the button again will add the page, print "OK" and then either simply hang or crash the application Sometimes you might get away with more presses, but ultimately it does crash.

### Expected Behavior

App shouldn't crash

### Actual Behavior

App crash

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/4130.

### CODE REVIEW

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/1/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/1//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/1/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/1/jenkins-results/apicomparison/index.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/1/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/2/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/2//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/2/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/2/jenkins-results/apicomparison/index.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/2/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by andrewdschmidt** [comment]
What's the timetable on this fix? Currently dealing with an app that's in-production that is encountering #4130 and what to be able to fix that as soon as possible.

**Comment by rolfbjarne** [comment]
@andrewdschmidt it will take some time to get this released, but there's a package from this PR with the fix if you want to try it: [xamarin.ios-11.13.0.19.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/2/package/xamarin.ios-11.13.0.19.pkg)

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/3/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/3//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/1973673f779fb2d795c4f726a2a2ce025e1f6e12/3/jenkins-results/api-diff/index.html)
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/1973673f779fb2d795c4f726a2a2ce025e1f6e12/3/jenkins-results/apicomparison/index.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/1973673f779fb2d795c4f726a2a2ce025e1f6e12/3/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/4/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/4//console)
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/c1fc21255655643f949eb635865ad5d63522b628/4/jenkins-results/api-diff/index.html)
ℹ️ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/c1fc21255655643f949eb635865ad5d63522b628/4/jenkins-results/apicomparison/index.html) (please review changes)
ℹ️ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/c1fc21255655643f949eb635865ad5d63522b628/4/jenkins-results/generator-diff/index.html) (please review changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by xamarin-release-manager** [comment]
✅ [Jenkins job](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/5/display/redirect) (on internal Jenkins) succeeded

✅ [Build succeeded](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/5//console)
🔥 [Failed to publish results](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/5//console) 🔥
🔥 [Failed to publish results](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/5//console) 🔥
✅ [API Diff (from stable)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/4fd5e4001144ca3a2b991f2e77c9783963db1851/5/jenkins-results/api-diff/index.html)
🔥 [Failed to publish results](http://xamarin-jenkins.guest.corp.microsoft.com:8080/job/macios/job/PR-4312/5//console) 🔥
✅ [API Diff (from PR only)](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/4fd5e4001144ca3a2b991f2e77c9783963db1851/5/jenkins-results/apicomparison/index.html) (no change)
✅ [Generator Diff](http://xamarin-storage/jenkins/xamarin-macios/PR-4312/4fd5e4001144ca3a2b991f2e77c9783963db1851/5/jenkins-results/generator-diff/index.html) (only version changes)
ℹ️ Test run skipped: Not running tests here because they're run on public Jenkins.

**Comment by rolfbjarne** [comment]
@xamarin/macios please re-review, there were many significant changes to this PR.

File: runtime/runtime.m [hunk 1]
```diff
@@ -2118,6 +2118,16 @@ -(void) xamarinSetGCHandle: (int) gc_handle;
 	return res;
 }
 
+void
+xamarin_release_block_on_main_thread (void *obj)
+{
+	if ([NSThread isMainThread]) {
```
Comment (spouliot) [inline runtime/runtime.m]: I was wondering about why mixing ObjC and C/GDC but learned that `dispatch_get_main_queue ()` is iOS 8+ only :(

File: runtime/runtime.m [hunk 2]
```diff
@@ -2118,6 +2118,16 @@ -(void) xamarinSetGCHandle: (int) gc_handle;
...
+		_Block_release (obj);
+	} else {
+		dispatch_async_f (dispatch_get_main_queue (), obj, (dispatch_function_t) _Block_release);
```
Comment (spouliot) [inline runtime/runtime.m]: which breaks here 💥 
:(

Comment (spouliot) [reply runtime/runtime.m]: Nice :) I wondered how you could get the value before then.  

note: worth a comment in the source (cuz I'll forget)

My original idea was to avoid ObjC with something like
```
dispatch_queue_t main = dispatch_get_main_queue ();
if (dispatch_get_current_queue () == main) {
    _Block_release (obj);
} else {
    dispatch_async_f (main, obj, (dispatch_function_t) _Block_release);
}
```
but `dispatch_get_current_queue ()` being deprecated I guess it makes this code require a mix of ObjC and C/GDC code.

Comment (rolfbjarne) [reply runtime/runtime.m]: Yes, I agree it looks strange, but all google could come up with about how to check for the main thread was `[NSThread isMainThread]`.

There's ObjC API to schedule things on the main thread, but it seemed (I didn't actually test it though) that it would use more memory (for instance `[NSObject performSelectorOnMainThread:withObject:waitUntilDone:]`, but it requires an NSObject instance). `NSRunLoop` isn't thread-safe so you end up with a chicken-and-egg problem.

**Comment by grenadier117** [comment]
> @andrewdschmidt it will take some time to get this released, but there's a package from this PR with the fix if you want to try it: [xamarin.ios-11.13.0.19.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4312/7bccbe59aac219eb5b9ef3eb1481115d5c667d95/2/package/xamarin.ios-11.13.0.19.pkg)

with 12.0.0.15 released, will this be included in Xamarin.iOS 12 anytime soon? We use WKWebview in our production app but can't target iOS 12 because the 11.13.0.19 patch isn't in the 12 release yet.
Thank you!
