### PR TITLE
[Foundation] Add nullability to NSFormatter. Fixes #16924

### LINKED ISSUE #16924: NSFormatter nullability is wrong.
As per the documentation, the methods do allow the out parameters to be null:

```
This method is invoked each time the user presses a key while the cell has the keyboard focus—it lets you verify and edit the cell text as the user types it.
In a subclass implementation, evaluate partialString according to the context, edit the text if necessary, and return by reference any edited string in newString. Return YES if partialString is acceptable and NO if partialString is unacceptable. If you return NO and newString is nil, the cell displays partialString minus the last character typed. If you return NO, you can also return by indirection an NSString object (in error) that explains the reason why the validation failed; the delegate (if any) of the NSControl object managing the cell can then respond to the failure in control:didFailToValidatePartialString:errorDescription:. The selection range will always be set to the end of the text if replacement occurs.

```
Docs: https://developer.apple.com/documentation/foundation/nsformatter/1417993-ispartialstringvalid?language=objc

### PR DESCRIPTION
**Pull request by mandel-macaque**

### CODE REVIEW

File: src/foundation.cs [hunk 1]
```diff
@@ -2499,10 +2499,10 @@ interface NSFormatter : NSCoding, NSCopying {
 		bool GetObjectValue (out NSObject obj, string str, out NSString error);
 
 		[Export ("isPartialStringValid:newEditingString:errorDescription:")]
-		bool IsPartialStringValid (string partialString, out string newString, out NSString error);
+		bool IsPartialStringValid (string partialString, [NullAllowed] out string newString, [NullAllowed] out NSString error);
 
 		[Export ("isPartialStringValid:proposedSelectedRange:originalString:originalSelectedRange:errorDescription:")]
-		bool IsPartialStringValid (ref string partialString, out NSRange proposedSelRange, string origString, NSRange origSelRange, out string error);
+		bool IsPartialStringValid ([NullAllowed] ref string partialString, out NSRange proposedSelRange, string origString, NSRange origSelRange, [NullAllowed] out string error);
```
Comment (rolfbjarne) [inline src/foundation.cs:2505]: The first parameter is explicitly `_Nonnull` in the documentation:

https://developer.apple.com/documentation/foundation/nsformatter/1415263-ispartialstringvalid

**Review by rolfbjarne — CHANGES_REQUESTED** [review]

File: src/foundation.cs (hunk 1 above)
Comment (mandel-macaque) [reply src/foundation.cs:2505]: I missed that one, the out are null. Sorry

Comment (mandel-macaque) [inline src/foundation.cs:2505]:
```suggestion
		bool IsPartialStringValid (ref string partialString, out NSRange proposedSelRange, string origString, NSRange origSelRange, [NullAllowed] out string error);
```

**Review by rolfbjarne — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]
