### PR TITLE
[registar] Search the entire interface hierarchy for protocols. Fixes #6493.

### LINKED ISSUE #6493: NSURLsessionDelegate issues
### Steps to Reproduce

1.  Create a class that derives from NSURLProtocol and NSURLSession delegate interfaces:
Ex:     public partial class TestUrlProtocol : NSUrlProtocol, INSUrlSessionDelegate, INSUrlSessionTaskDelegate, INSUrlSessionDataDelegate

2.  In StartLoading, create the URLSessionTask and resume the task
3.  Add delegate methods to handle challenge and redirection

### Expected Behavior
This needs to build / run and handle NTLM /certificate challenges
### Actual Behavior

First issue: 
Gives a warning for the below delegate:
 **Warning MT4174: Unable to locate the block to delegate conversion method for the method TestSampleApp.TestUrlProtocol.WillPerformHttpRedirection's parameter #5. (MT4174)  Warning 

MT4174: Unable to locate the block to delegate conversion method for the method TestSampleApp.TestUrlProtocol.DidReceiveChallenge's parameter #4. (MT4174)** 

**And when running this will crash with below error:

Unhandled managed exception: The runtime function get_block_wrapper_creator has been linked away. (ObjCRuntime.RuntimeException)
Crash is pointing at DidReceiveChallenge call.**

### Environment

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.1.3 (build 19)
Installation UUID: 5bba6d13-ac9c-4c7c-b27c-1f9467a37562
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Enterprise)
Commit: HEAD/d0b48056f
Android SDK: /Users/mbhattathiri/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mbhattathiri/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801030019
Git revision: 2d04b0145da8aa946d2cc9898fe2a59484e4f3f4
Build date: 2019-06-26 15:34:25+00
Build branch: release-8.1
Xamarin extensions: de240bddd6d1f96bfb1e7d11ce7ac5398956fe1d

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by rolfbjarne**
When we're searching for metadata for marshalling blocks, we must search the
entire interface hierarchy for protocols that implement optional members.

Fixes https://github.com/xamarin/xamarin-macios/issues/6493.

### CODE REVIEW

File: src/ObjCRuntime/Registrar.cs [hunk 1]
```diff
@@ -159,6 +160,44 @@ internal class ObjCType {
...
+			// class T : NSObject, IProtocol2 {}
+			// [Protocol]
+			// interface IP1 {}
+			// [Protocol]
+			// interface IP2 : IP1 {}
+			// This property will contain both IP1 and IP2. The Protocols property only contains IP2.
+			public IEnumerable<ObjCType> AllProtocols {
+				get {
+					if (Protocols == null || Protocols.Length == 0)
+						return null;
```
Comment (stephen-hawley) [inline src/ObjCRuntime/Registrar.cs]: How important is the null return vs returning an empty`IEnumerable`?
It strikes me that you could also do:
```
bool protocolsRetrieved = false;
HashSet<ObjCType> all_protocols = new HashSet<ObjCType>();
public IEnumerable<ObjCType> AllProtocols {
    if (protocolsRetrieved)
        return all_protocols;
    if (Protocols != null && Protocols.Length > 0) {
        // code to fetch all the protocols here
    }
    protocolsRetrieved = true;
    return all_protocols;
}

Then you don't need the null tests on this type ever.

Comment (rolfbjarne) [reply src/ObjCRuntime/Registrar.cs]: @stephen-hawley because an empty `IEnumerable` uses more memory than null, and this is something that 99.9% of the time will be null (or empty).

**Comment by rolfbjarne** [comment]
@monojenkins backport d16-3
@monojenkins backport xcode11
