### PR TITLE
[NativeAOT] Improve the transformation of [Preserve(AllMembers = true)]

### LINKED ISSUE #19505: [NativeAOT] Fix AOT analysis warning IL3050
This issue is a follow-up to #19043

When building apps with NativeAOT, the ILC prints an AOT analysis warning IL3050: _<Module>..cctor(): Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling._

The problem is caused by the `[DynamicDependency]` attributes we generate in the `ApplyPreserveAttributeBase` custom linker step when we're transforming `[Preserve(AllMembers = true)]`. There are two cases in which we get this warning:
- the `[Preserve(AllMembers = true)]` is applied to an enum
- the class with the attribute contains a nested enum

We transform the attribute by generating a `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(T))]` attribute on the module cctor. This will pull all members of `T`, but also all members of its base types. In the case of enums, this unfortunately includes the `GetValues(Type)` static method which is annotated with `RequiresDynamicCode`.

I see some potential solutions, each of them has a different trade-off:
- Do not preserve nested types
    - We change the `DynamicDependency` attribute from `All` to `All ^ PublicNestedTypes ^ NonPublicNestedTypes` for classes and to `PublicFields` for enums. This doesn't seem to be a problem in the xamarin-macios codebase (all tests are passing locally with this change), but it will be a breaking change.
- Deprecate `[Preserve]`
    - We remove all nested enums that cause this problem (`NSObject_Disposer -> NSObject -> Flags, XamarinGCHandleFlags`) and make `[Preserve]` attribute obsolete. We would still keep the custom linker steps that transform Preserve into DynamicDependency, but customers won't get this warning unless they have nested enums in their classes. On our end, we would need to remove all uses of `[Preserve]` especially in tests (~1200 uses) and in MAUI. The Preserve attributes are baked into bgen-generated binding libraries which could be a problem.
- Suppress the warning
    - I think it can be argued that nobody expects `Enum.GetValues(Type)` method to be preserved when the `[Preserve]` attribute is applied to an enum. We might want to simply suppress `IL3050` on the module initializer that we generate. I'm not a fan of this solution since we can't suppress just the warning for `GetValues` and we could miss some other warning with the same ID.

What other solutions should we consider?

/cc @rolfbjarne @ivanpovazan @vitek-karas

### Steps to Reproduce

1. Build the MySingleView test app with NativeAOT:
```
dotnet publish -f net8.0-ios -r ios-arm64 \
    -p:PublishAot=true -p:PublishAotUsingRuntimepack=true \
    -p:EnableTrimAnalyzer=true -p:TrimmerSingleWarn=false \
    tests/dotnet/MySingleView/
```
2. Inspect warnings

### Expected Behavior
There are no build warnings.

### Actual Behavior
ILC prints this warning:
```
ILC : AOT analysis warning IL3050: <Module>..cctor(): Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. It might not be possible to create an array of the enum type at runtime. Use the GetValues<TEnum> overload or the GetValuesAsUnderlyingType method instead. [/.../xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj]
```

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #19505 

We transform `[Preserve(AllMembers = true)]` into `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(T))]`. There is difference between which members are preserved in these two cases. The `DynamicallyAccessedMemberTypes.All` preserves many more, especially nested types and their members. This manifested with the `IL3050` AOT analysis warning we got from ILC when building any app:
1. `NSObject_Disposer` has `[Preserve(AllMembers = true)]`
2. `NSObject_Disposer` is a subclass of NSObject
3. `NSObject` has nested enums `Flags` and `XamarinGCHandleFlags`
4. the base class `Enum` has a public static method `GetValues(Type)`
5. the `GetValues` method is annotated with `RequiresDynamicCode` and ILC produces a warning because even though it isn't used anywhere in the codebase, it could be used via reflection

I changed two things when transforming Preserve:
- For enums, we only need to preserve public fields. We especially want to avoid `PublicMethods` since that would preserve public methods in the base class which includes the `GetValues(Type)` method.
- For other types, I list explicitly the member types that should be preserved instead of using `All`.
    - The code is verbose, but in the end, I chose the explicit list instead of `All ^ PublicNestedTypes ^ NonPublicNestedTypes` since that would automatically include any new flag added to the enum in the future.

### CODE REVIEW

File: tools/dotnet-linker/ApplyPreserveAttributeBase.cs [hunk 1]
```diff
@@ -259,9 +270,11 @@ void AddDynamicDependencyAttribute (TypeDefinition type, bool allMembers)
...
 
 			var moduleConstructor = GetOrCreateModuleConstructor (type.GetModule ());
-			var members = allMembers
-				? DynamicallyAccessedMemberTypes.All
-				: DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors;
+			var members = (type, allMembers) switch {
+				( { IsEnum: true }, _) => DynamicallyAccessedMemberTypes.PublicFields,
+				(_, false) => DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors,
+				(_, true) => allMemberTypes,
+			};
```
Comment (akoeplinger) [inline tools/dotnet-linker/ApplyPreserveAttributeBase.cs:277]: nit: I find the pattern matching switch kinda hard to read compared to splitting it up a bit:

```csharp
var members = allMembers
	? allMemberTypes
	: DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors;

// only preserve fields for enums
if (type.IsEnum)
	members = DynamicallyAccessedMemberTypes.PublicFields
```
