### PR TITLE
[tests] Add introspection tests to ensure there are native linking instructions for all frameworks. Fixes #3976

### LINKED ISSUE #3976: "-framework NetworkExtension" not added by users of that API in XM
### Steps to Reproduce

1. Create new XM project and add this code somewhere `NEVpnManager manager = NEVpnManager.SharedManager` 
2. Build
3. Note lack of -framework NetworkExtension anywhere in mmp's clang invocation

### Expected Behavior

Just like other frameworks reference the framework 

### Actual Behavior

No reference. This causes app store rejection - https://forums.xamarin.com/discussion/comment/328499

### Environment

Stable

### Build Logs
https://gist.github.com/chamons/713b9c70026b2d851355833e9fedd75d

> VS bug [#627721](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/627721)

### PR DESCRIPTION
**Pull request by spouliot**
or a good, documented (in test code) reason for not needing it.

https://github.com/xamarin/xamarin-macios/issues/3976

### CODE REVIEW

**Comment by spouliot** [comment]
`23:04:58  error: cannot find interface declaration for 'NSExtensionContext', superclass of 'PHProjectExtensionContext'` leading to `make[2]: *** [Xamarin.Mac.registrar.full.i386.a] Error 1`
might be an issue with changes to `Frameworks.cs` wrt 32 bits

File: tests/introspection/ApiFrameworkTest.cs [hunk 1]
```diff
@@ -0,0 +1,120 @@
+﻿#if XAMCORE_2_0
```
Comment (rolfbjarne) [inline tests/introspection/ApiFrameworkTest.cs]: `__UNIFIED__` looks nicer :smile:

**Comment by spouliot** [comment]
@chamons @rolfbjarne a final look please before I merge and back port to `xcode10`, thanks!
