### PR TITLE
[Foundation] Ensure we do raise 401 on NTLM when no creds are present. Fixes #3742

### LINKED ISSUE #3742: NSUrlSessionHandler does not return HTTP 401 when using NTLM and no credentials are supplied
Using the [`NSUrlSessionHandler`](https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSUrlSessionHandler.cs) as `HttpMessageHandler` of the `System.Net.Http.HttpClient` causes `await GetAsync` and `await PostAsync` to not return when the requested resource requires NTLM authentication and no credentials are supplied.

The problem only occurs with NTLM and the [`NSUrlSessionHandler`](https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSUrlSessionHandler.cs):

 * If NTLM is disabled on the IIS (and only Kerberos is used), the call returns with HTTP 401 as expected (if no [Apple SSO configuration profile](https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW44) is installed on the iOS device).
* If the `System.Net.Http.HttpClientHandler` is used as `HttpMessageHandler`, the call returns with HTTP 401 as expected.

### Steps to Reproduce

1. Create a Xamarin.iOS project and add the `System.Net.Http` NuGet package.
3. Create a new `HttpClient` and use the `NSUrlSessionHandler` as `HttpMessageHandler`.
4. Call `GetAsync` to a resource on an IIS that uses NTLM for authentication.
```csharp
HttpClient httpClient = new HttpClient(new NSUrlSessionHandler());

// the GetAsync will not return and cause
// a System.Threading.Tasks.TaskCanceledException after ~2 mins
var response = await httpClient.GetAsync("https://some-url-with-ntlm");
var message = await response.Content.ReadAsStringAsync();
```

### Expected Behavior

The call
```csharp
var response = await httpClient.GetAsync("https://some-url-with-ntlm");
```
returns and `response.StatusCode` is equal to `HttpStatusCode.Unauthorized`, as no credentials are supplied and IIS requires NTLM for authentication.

### Actual Behavior

The call
```csharp
var response = await httpClient.GetAsync("https://some-url-with-ntlm");
```
does not return and throws a `System.Threading.Tasks.TaskCanceledException` after about two minutes:
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00020] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:179 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cf9013b38a4e4129bd64785080dd2844>:0 
  at System.Net.Http.NSUrlSessionHandler+<SendAsync>d__29.MoveNext () [0x001be] in /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:202 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:176 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <cf9013b38a4e4129bd64785080dd2844>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__48.MoveNext () [0x00080] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:276 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:176 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <cf9013b38a4e4129bd64785080dd2844>:0 
  at NtlmRequestTimeout.MainViewController+<DoHttpGet>d__2.MoveNext () [0x0004a] in C:\Users\...\NtlmRequestTimeout\NtlmRequestTimeout\MainViewController.cs:50

```

### Environment

```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.0
VisualStudio.15.Release/15.6.0+27428.1
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Visual C++ 2017   00369-90252-57073-AA038
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-90252-57073-AA038
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40214.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clean Solution   1.4.20
Cleans up the solution for the next time you open it. Closes open documents and collapses folders automatically when a solution is being closed. 

CodeMaid   10.4.53
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.27326.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.9.0.749 (9b0fce36d)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.0.20 (1c6f300)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

[NtlmRequestTimeout.zip](https://github.com/xamarin/xamarin-macios/files/1810214/NtlmRequestTimeout.zip)

### PR DESCRIPTION
**Pull request by mandel-macaque**
The code was not executing the completionHandler in those case were the
user did not provide the creds. We should try to get the creds and use
them or call the cb with the proposed creds.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Quite hard bug fix to test due to the extra setup you need to do. We should talk with @GouriKumari or other QA members to create nice server apps to test this kind of things.

File: src/Foundation/NSUrlSessionHandler.cs [hunk 1]
```diff
@@ -380,15 +380,16 @@ public override void DidReceiveChallenge (NSUrlSession session, NSUrlSessionTask
...
 						var credentialsToUse = sessionHandler.Credentials as NetworkCredential;
 						if (credentialsToUse == null) {
 							var uri = inflight.Request.RequestUri;
 							credentialsToUse = sessionHandler.Credentials.GetCredential (uri, "NTLM");
 						}
-						var credential = new NSUrlCredential (credentialsToUse.UserName, credentialsToUse.Password, NSUrlCredentialPersistence.ForSession);
-						completionHandler (NSUrlSessionAuthChallengeDisposition.UseCredential, credential);
+						credential = new NSUrlCredential (credentialsToUse.UserName, credentialsToUse.Password, NSUrlCredentialPersistence.ForSession);
 					}
+					completionHandler (NSUrlSessionAuthChallengeDisposition.UseCredential, credential ?? challenge.ProposedCredential);
```
Comment (spouliot) [inline src/Foundation/NSUrlSessionHandler.cs]: It seems weird using `.UseCredential` without credentials - please double check docs

Still the current code is hits `return` without calling the `completionHandler` so that's more than likely wrong...

Could it be possible the return statement should be moved into the `if (sessionHandler.Credentials != null) {` condition ?

That would solve both inconsistency, since `completionHandler` would be called (it's not now) and asked to `.PerformDefaultHandling` with the challenge proposed credentials.

**Comment by mandel-macaque** [comment]
@GouriKumari this is the fix we need to test for issue #3742

**Comment by mandel-macaque** [comment]
Following a talk with @spouliot I have made the following changes:

1. Reduce the number of if statements, we can use a single one with an &&
2. Reduce the number of exit points in the method, we use an else. Returns in the middle of the code are error prone.
3. Moved to use NSURLSessionAuthChallengePerformDefaultHandling when the credentials are null. As per the documentation the credential is ignored using NSURLSessionAuthChallengePerformDefaultHandling:
    - NSURLSessionAuthChallengeUseCredential: Use the specified credential, which may be nil.
    - NSURLSessionAuthChallengePerformDefaultHandling: Use the default handling for the challenge as though this delegate method were not implemented. The provided credential parameter is ignored.

**Comment by mandel-macaque** [comment]
AFIAK QA will provide a server we can test against for this fix @GouriKumari can you let use know when is ready for the reviewers to take a look. Thx!

**Comment by GouriKumari** [comment]
I could reproduce the issue with d15-7,  https://gist.github.com/GouriKumari/2268dafe38ad2d712d17632222ed99c6. Can someone confirm the error Log. I would like to know where I can find the build to verify this issue.

##Test Env:
Xamarin.iOS
Version: 11.10.0.50 (Visual Studio Community)
Hash: eb1d7875
Branch: d15-7
Build date: 2018-03-27 23:00:22-0400

**Comment by mandel-macaque** [comment]
@GouriKumari I new lane has been created for this PR here: https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-xamarin-macios-pr-3794

**Comment by spouliot** [comment]
@mandel-macaque wrench was misconfigured
@GouriKumari  I updated the config and kicked a new build

**Comment by GouriKumari** [comment]
Verified with xamarin.ios-11.11.0.82.pkg and NSURLSessionHandler is returning 401 authorization error on NTLM.

##Logs:
Build Log: https://gist.github.com/GouriKumari/b2db9d8c5f05a32260fc66f68147f5a5
ApplicationOutput: https://gist.github.com/GouriKumari/021181839339462be20bc06abaa14214

**Comment by spouliot** [comment]
@GouriKumari thanks!
@mandel-macaque please backport to 15.7
