### PR TITLE
[dotnet/msbuild] Run install_name_tool to fix the id for dylibs. Fixes #13999.

### LINKED ISSUE #13999: Dylibs acquired from NuGet no longer have install_name_tool run on them
### Steps to Reproduce

1. Build the attached project
2. Run `otool -L bin/Debug/net6.0-macos/osx-x64/dyliblinkissue.app/Contents/MacOS/dyliblinkissue`

### Expected Behavior

The SQLite library is linked with fixed path to `@rpath/libe_sqlite3.dylib`.

### Actual Behavior

The original dylib name is used:
```
./bin/e_sqlite3/mac/x86_64/libe_sqlite3.dylib (compatibility version 0.0.0, current version 0.0.0)
```

This is regression from the shipping SDKs (~preview 11).

### Environment

.NET 6.0.200 SDK nightly, macOS Workload 12.1.300-preview.14.101 acquired using `dotnet workload install macos`.

### Example Project (If Possible)

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/7974536/Archive.zip)

The project is empty project created by `dotnet new macos` with added PackageReference to .csproj:
```
  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.7" PrivateAssets="None" />
  </ItemGroup>
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/13999.

### CODE REVIEW

**Review by chamons — APPROVED** [review]

File: tools/common/MachO.cs [hunk 1]
```diff
@@ -783,6 +783,29 @@ internal void Read (BinaryReader reader)
...
+					var dlc = new DylibIdCommand ();
+					dlc.cmd = reader.ReadUInt32 ();
+					dlc.cmdsize = reader.ReadUInt32 ();
+					/*var nameofs = */ reader.ReadUInt32 ();
+					dlc.timestamp = reader.ReadUInt32 ();
+					dlc.current_version = reader.ReadUInt32 ();
+					dlc.compatibility_version = reader.ReadUInt32 ();
+					var namelength = dlc.cmdsize - 6 * 4;
+					var namechars = reader.ReadBytes ((int) namelength);
+					// strip off any null characters at the end.
```
Comment (mandel-macaque) [inline tools/common/MachO.cs:797]: Would GetString.Trim deal with this? Di we need to do it by hand?

**Review by dalexsoto — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]

**Review by emaf — APPROVED** [review]
