### PR TITLE
[Foundation] Improve/fix NSRegularExpression and NSDataDetector bindings. Fixes #5881.

### LINKED ISSUE #5881: iOS:Foundation: GetMatches has incorrect result type
### Steps to Reproduce

1. Execute example (below) on latest iOS

### Expected Behavior

NSRegularExpression [apple doc](https://developer.apple.com/documentation/foundation/nsregularexpression/1412446-matchesinstring)

```objc
- (NSArray<NSTextCheckingResult *> *)matchesInString:(NSString *)string 
                                             options:(NSMatchingOptions)options 
                                               range:(NSRange)range;
```

Result: NSTextCheckingResult[]

### Actual Behavior
[ms doc](https://docs.microsoft.com/en-us/dotnet/api/foundation.nsregularexpression.getmatches?view=xamarin-ios-sdk-12)

```cs
[Foundation.Export("matchesInString:options:range:")]
public virtual Foundation.NSString[] GetMatches (Foundation.NSString str, Foundation.NSMatchingOptions options, Foundation.NSRange range);
```

Result: NSString[]

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.0.2 (build 23)
Installation UUID: 718c9426-9b34-4dad-a550-66605f1e5527
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.1.0-preview1-26216-03
	2.0.5
	2.0.0
	1.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.300-preview1-008174
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2 (14490.120)
Build 10E125

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Enterprise)
Android SDK: /Users/yauhenipakala/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/yauhenipakala/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800020023
Git revision: c576bb008dfe54cdcf596237e09564ebd2da4343
Build date: 2019-04-06 10:06:46+00
Build branch: master
Xamarin extensions: 2c996830618e7cb8e8be97984d643eb86f122e8d

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

```cs
var text = "some text http://google.com text text";

var types = (NSTextCheckingTypes)NSTextCheckingType.Link;
var range = new NSRange(0, text.Length);
var detector = NSDataDetector.Create(types, out NSError error);

NSString[] matches = detector.GetMatches(new NSString(text), 0, range);
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
* NSDataDetector

    * Add constructor found in header. No idea where the commented-out
      constructor came from, it's not in the header, so I removed it.
    * Add overloads that take NSTextCheckingType in addition to
      NSTextCheckingTypes. Apple's API take NSTextCheckingTypes, but all the
      documentation and samples say that you're supposed to pass one or more
      or'ed NSTextCheckingType values, so support that as well without casting
      between enums.

* NSRegularExpression

    * GetMatches had the wrong return type, so add a GetMatches2 that does it
      right. Also add a test to make sure it's really right.
    * Bind 'regularExpressionWithPattern:options:error:' with a static method.
      There's a corresponding constructor, but constructors returning out
      NSError parameters isn't the nicest API (when the NSError is important),
      so add the static method as well.
    * Add a missing [NullAllowed] on FindFirstMatch's return value.

* NSRegularExpressionOptions

    * Add missing enum value.

Fixes https://github.com/xamarin/xamarin-macios/issues/5881.

### CODE REVIEW

File: src/foundation.cs [hunk 1]
```diff
@@ -4579,21 +4590,37 @@ interface NSRegularExpression : NSCopying, NSSecureCoding {
...
 		[Export ("matchesInString:options:range:")]
 		NSString [] GetMatches (NSString str, NSMatchingOptions options, NSRange range);
+#endif
+
+		[Export ("matchesInString:options:range:")]
+#if XAMCORE_4_0
+		NSTextCheckingResult [] GetMatches (NSString str, NSMatchingOptions options, NSRange range);
+#else
+		[Sealed]
+		NSTextCheckingResult [] GetMatches2 (NSString str, NSMatchingOptions options, NSRange range);
```
Comment (Therzok) [inline src/foundation.cs]: Not exported?
