### PR TITLE
[mtouch] Fix caching issues. Fix #7514

### LINKED ISSUE #7514: Updated Frameworks not being updated in final app package without rebuild
### Steps to Reproduce

1. Create an iOS project
2. Install SkiaSharp 1.68.0
3. Write some code that does something with SkiaSharp and call one of the dispose methods
4. [Re]build and deploy
5. Upgrade SkiaSharp to 1.68.1
6. Build (not rebuild) and deploy
7. Observe a entry point not found exception
8. REBUILD and deploy
8. Observe NO exception

I have been getting quite a few reports of people upgrading to a new version of SkiaSharp and then reporting that there are missing entry points. This is because I added new entries to the new version. The reason this is happening is that the process of update-NuGet-and-then-just-build is not triggering the bits to repackage the native bits into the package. A rebuild fixes this.

An example issue: https://github.com/mono/SkiaSharp/issues/968

### Expected Behavior

No exception

### Actual Behavior

EntryPointNotFoundException

### Environment

Recent versions (not sure how far it goes back)

### PR DESCRIPTION
**Pull request by spouliot**
The nice, repeatable test case from #7514 pointed out two issues

1. `cache.cs` ignored some changes

It looks like something changed (at some point) and the first _ignored_
line was the `@x.rsp` our response file - which should not be ignored.

This solved the build issue where updating the nuget should have
triggered a rebuild because
> /Users/poupou/.nuget/packages/skiasharp/1.68.0/lib/Xamarin.iOS/SkiaSharp.dll
and
> /Users/poupou/.nuget/packages/skiasharp/1.68.1/lib/Xamarin.iOS/SkiaSharp.dll
are different assemblies (but the same response file).

2. `copyfile` could fail silently

Copying the framework could fail (error 260) and the failure was never
reported so the build succeeded - but without updating (completely) the
framework.

The exact reason it fails is unknown :( but we can recover from it by
deleting the target and copying (everything) back to the expected
(target) location.

Build logs will now indicate when this fails and will try to recover
before reporting a build error. Best case it works :) worse case we'll
be aware something is wrong (which is better than ignoring)

ref: https://github.com/xamarin/xamarin-macios/issues/7514

### CODE REVIEW

File: tools/common/FileCopier.cs [hunk 1]
```diff
@@ -102,6 +113,12 @@ static CopyFileResult CopyFileCallback (CopyFileWhat what, CopyFileStep stage, I
 				if (!IsUptodate (source, target)) {
 					if (stage == CopyFileStep.Finish)
 						Log (1, "Copied {0} to {1}", source, target);
+					else if (stage == CopyFileStep.Err) {
+						// don't call `strerror` because the most common `260` returns `Unknown error : 260`
```
Comment (rolfbjarne) [inline tools/common/FileCopier.cs]: I wonder if setting `SetLastError = true` on the P/Invoke would make it return a different error?

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.setlasterror?view=netframework-4.8

Comment (spouliot) [reply tools/common/FileCopier.cs]: worth trying!

Comment (spouliot) [reply tools/common/FileCopier.cs]: It's already present on `copyfile`
```csharp
[DllImport ("/usr/lib/libSystem.dylib", SetLastError = true)]
static extern int copyfile (string @from, string @to, IntPtr state, CopyFileFlags flags);
```
but the callback happens during the call... 

> Indicates whether the callee calls the SetLastError Windows API function before returning from the attributed method.

so `SetLastError` is probably not yet execute anyway.

Adding it to `copyfile_state_set` (the previous p/invoke) does not change anything (as that call returned success/`0` anyway).

Comment (spouliot) [reply tools/common/FileCopier.cs]: > so SetLastError is probably not yet execute anyway.

but asking for the error after `copyfile` (not in the callback) returns `17` / `File exists`
which is true... but I expected **overwrite** was default (and it does not it was for other files)

Comment (spouliot) [reply tools/common/FileCopier.cs]: still that might not be fully accurate since the callback still report an error... and the last operation happened on a file that existed :|
