### PR TITLE
[src] Fix generic Contacts API. Fixes #6561.

### LINKED ISSUE #6561: [xcode11] b1 Contacts.cs non-generic type errors for enumeratorForContactFetchRequest, enumeratorForChangeHistoryFetchRequest
### Steps to Reproduce

1. Open src/Contacts.cs

2. Inside of `interface CNContactStore` uncomment or add:

		[Unavailable (PlatformName.Swift)]
		[Export ("enumeratorForContactFetchRequest:error:")]
		[return: NullAllowed]
		CNFetchResult<NSEnumerator<CNContact>> GetEnumeratorForContact (CNContactFetchRequest request, [NullAllowed] out NSError error);

		[Unavailable (PlatformName.Swift)]
		[Export ("enumeratorForChangeHistoryFetchRequest:error:")]
		[return: NullAllowed]
		CNFetchResult<NSEnumerator<CNChangeHistoryEvent>> GetEnumeratorForChangeHistory (CNChangeHistoryFetchRequest request, [NullAllowed] out NSError error);

3. make all -j8 yields the following errors:

```
GEN      [ios] generated_sources
GEN      [mac/mobile] generated-sources
GEN      [mac/full] generated-sources
GEN      [watch] generated_sources
CSC      [tvos] Xamarin.TVOS.dll
contacts.cs(1477,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1477,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1482,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1482,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1474,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
contacts.cs(1479,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
bgen: API binding contains errors.
make: *** [build/watch/watch/generated_sources] Error 1
make: *** Waiting for unfinished jobs....
contacts.cs(1477,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1477,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1482,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1482,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1474,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
contacts.cs(1479,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
contacts.cs(1477,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1477,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1482,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1482,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1474,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
contacts.cs(1479,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
bgen: API binding contains errors.
make: *** [build/mac/full/generated-sources] Error 1
contacts.cs(1477,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1477,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1482,3): error CS0308: The non-generic type 'CNFetchResult' cannot be used with type arguments
contacts.cs(1482,17): error CS0308: The non-generic type 'NSEnumerator' cannot be used with type arguments
contacts.cs(1474,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
contacts.cs(1479,30): error CS0117: 'PlatformName' does not contain a definition for 'Swift'
bgen: API binding contains errors.
make: *** [build/ios/native/generated_sources] Error 1
bgen: API binding contains errors.
make: *** [build/mac/mobile/generated-sources] Error 1
rm build/tvos/reference/OpenTK-1.0.dll.config build/ios/reference/OpenTK-1.0.dll.config
```

### PR DESCRIPTION
**Pull request by rolfbjarne**
Make CNFetchResult generic (which it is in Objective-C), and add a generic
version of NSEnumerator (which Objective-C also has), so that we can bind two
API in CNContactStore that uses generic versions of those types.

Fixes https://github.com/xamarin/xamarin-macios/issues/6561.

### CODE REVIEW

File: src/Foundation/NSEnumerator_1.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+		}
+
+		internal NSEnumerator (IntPtr handle)
+			: base (handle)
+		{
+		}
+
+		// Strongly typed versions of API from NSEnumerator
+
+		public new TKey NextObject ()
```
Comment (Therzok) [inline src/Foundation/NSEnumerator_1.cs]: Maybe call this `Next`?

**Comment by rolfbjarne** [comment]
Test failure is unrelated

* introspection/tvOS 10.2: https://github.com/xamarin/maccore/issues/940
