### PR TITLE
[CoreTelephony] Fix multiple issues. Fixes #13931.

### LINKED ISSUE #13931: [net6.0-maccatalyst] `CoreTelephony` is missing
### Description

The following namespace is present in `xamarinios10` and `net6.0-ios` but is not present in `net6.0-maccatalyst`:

`CoreTelephony`

If I'm reading [this](https://developer.apple.com/documentation/coretelephony) properly, this namespaces is supposed to be available in Catalyst.

### Environment

VS 17.1 preview 4

### PR DESCRIPTION
**Pull request by rolfbjarne**
* Add to Mac Catalyst. Fixes #13931.
* Manually include CoreTelephony headers in xtro. There's no umbrella header
  in CoreTelephony 😡 😞
* Fix availability attributes
	* Only CTCall and CTCallCenter are deprecated in the CoreTelephony API.
	* None of these APIs are obsolete, just deprecated.
	* Add Mac Catalyst attributes.

One curious fact is that the PCSC framework interferes with compiling CTCarrer.h:

    In file included from /private/var/folders/43/h027tm1n101cdrq2_b6n9n2m0000gn/T/n0b0byrt.h:163:
    /Applications/Xcode_13.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTCarrier.h:62:41: error: reference to 'BOOL' is ambiguous
    @property (nonatomic, readonly, assign) BOOL allowsVOIP __OSX_AVAILABLE_STARTING(__MAC_NA,__IPHONE_4_0);
                                            ^
    /Applications/Xcode_13.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/PCSC.framework/Headers/wintypes.h:59:18: note: candidate found by name lookup is 'BOOL'
            typedef int16_t BOOL;
                            ^
    /Applications/Xcode_13.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/objc/./objc.h:78:18: note: candidate found by name lookup is 'BOOL'
        typedef bool BOOL;
                     ^
    1 error generated.

but since we don't bind the PCSC framework, we can just ask ObjectiveSharpie
to exclude it.

Fixes https://github.com/xamarin/xamarin-macios/issues/13931.

### CODE REVIEW

**Review by tj-devel709 — APPROVED** [review]

File: src/CoreTelephony/CTEnums.cs [hunk 1]
```diff
@@ -11,7 +11,7 @@ public enum CTErrorDomain {
 		Mach = 2,
 	}
 
-	[Obsoleted (PlatformName.iOS, 14,0, message: Constants.UseCallKitInstead)]
```
Comment (chamons) [inline src/CoreTelephony/CTEnums.cs:14]: Did iOS not really obsolete this? I'm a bit confused by this.

Comment (rolfbjarne) [reply src/CoreTelephony/CTEnums.cs:14]: It's not: https://developer.apple.com/documentation/coretelephony/ctcellulardatarestrictedstate?language=objc

Some types say that you should use CallKit instead, but it looks like that's only limited to certain types: https://developer.apple.com/documentation/coretelephony/ctcallcenter?language=objc
