### PR TITLE
[Network] Add currentPath property to NWPathMonitor. Fixes #5603.

### LINKED ISSUE #5603: NWPathMonitor missing CurrentPath property
### Steps to Reproduce

1. Create a new `NWPathMonitor` as a local variable e.g. 
```
 var _monitor = new NWPathMonitor();
```
2. Look for the [currentPath property ](https://developer.apple.com/documentation/network/nwpathmonitor?changes=l_3)
3. Its not there 😟

### Expected Behavior
The currentPath property is there.

### Actual Behavior
It is not there.

### Environment

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.8 Preview (7.8 build 1547)
Installation UUID: 8c7fef3a-fdce-4bea-9095-7a0a505e98fc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.6
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.0
	1.0.1
	1.0.0-rc2-3002702
SDK: /usr/local/share/dotnet/sdk/2.1.500/Sdks
SDK Versions:
	2.1.500
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.0-preview2-1-003177
	1.0.0-preview1-002702
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

=== Xamarin.iOS ===

Version: 12.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

=== Xamarin.Android ===

Version: 9.1.5.1 (Visual Studio Enterprise)
Android SDK: /Users/b099l3/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/b099l3/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 708001547
Git revision: ac9638e6096d900f180fc470f148ea8fa059ee42
Build date: 2019-01-15 12:26:48+00
Build branch: release-7.8
Xamarin extensions: becb77097be5b754a310dbfe39dc9a326e73620e

=== Operating System ===

Mac OS X 10.14.3
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Thu Dec 20 20:46:53 PST 2018
    root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Code Coverage 1.0
Default Designer 1.3
AddinMaker 1.4.3
FileNesting 0.1.1
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.14
Template Creator 0.4
Mutatio 1.0.2
Prism Template Studio and Developer Toolkit 2.2.0.434
Redth's Addins 1.0.9
Screenmedia Visual studio for Mac Extension 1.0
```

### Build Logs

None.

### Example Project (If Possible)

Any project

### PR DESCRIPTION
**Pull request by wachaudh**
Adds currentPath property to NWPathMonitor. 
Fixes https://github.com/xamarin/xamarin-macios/issues/5603

### CODE REVIEW

File: src/Network/NWPathMonitor.cs [hunk 1]
```diff
@@ -22,9 +22,17 @@ public class NWPathMonitor : NativeObject {
 		[DllImport (Constants.NetworkLibrary)]
 		extern static IntPtr nw_path_monitor_create ();
 
+		public NWPath currentPath;
```
Comment (spouliot) [inline src/Network/NWPathMonitor.cs]: That should be a property (not a field) and named `CurrentPath` (casing is incorrect for .net)

Comment (mandel-macaque) [inline src/Network/NWPathMonitor.cs]: Use a get only property with a private var.
```suggestion
		private NWPath currentPath;
		public NWPath CurrentPath => currentPath;
```

File: src/Network/NWPathMonitor.cs [hunk 2]
```diff
@@ -22,9 +22,17 @@ public class NWPathMonitor : NativeObject {
...
 		public NWPathMonitor ()
 		{
+			currentPath = null;
```
Comment (mandel-macaque) [inline src/Network/NWPathMonitor.cs]: Not needed. Will be null by default.

File: src/Network/NWPathMonitor.cs [hunk 3]
```diff
@@ -22,9 +22,17 @@ public class NWPathMonitor : NativeObject {
...
 			InitializeHandle (nw_path_monitor_create ());
+			InternalSetUpdatedSnapshotHandler ((path) => {
+				currentPath = path;
+				if (userSnapshotHandler != null) {
+					userSnapshotHandler(currentPath);
```
Comment (spouliot) [inline src/Network/NWPathMonitor.cs]: minor (style): need a ` ` (space) before the `(`

Comment (mandel-macaque) [inline src/Network/NWPathMonitor.cs]: Space after (
```suggestion
					userSnapshotHandler (currentPath);
```

File: src/Network/NWPathMonitor.cs [hunk 4]
```diff
@@ -33,6 +41,12 @@ public NWPathMonitor ()
 		public NWPathMonitor (NWInterfaceType interfaceType)
 		{
 			InitializeHandle (nw_path_monitor_create_with_type (interfaceType));
+			InternalSetUpdatedSnapshotHandler ((path) => {
+				currentPath = path;
+				if (userSnapshotHandler != null) {
+					userSnapshotHandler(currentPath);
```
Comment (spouliot) [inline src/Network/NWPathMonitor.cs]: same (style)

also this might be better added in a separate method (DRY - don't repeat yourself)

File: src/Network/NWPathMonitor.cs [hunk 5]
```diff
@@ -33,6 +41,12 @@ public NWPathMonitor ()
 		public NWPathMonitor (NWInterfaceType interfaceType)
 		{
 			InitializeHandle (nw_path_monitor_create_with_type (interfaceType));
+			InternalSetUpdatedSnapshotHandler ((path) => {
```
Comment (mandel-macaque) [inline src/Network/NWPathMonitor.cs]: Could we move the lambda to a method, that way we don't need to write the same code twice.

File: src/Network/NWPathMonitor.cs [hunk 6]
```diff
@@ -91,6 +105,12 @@ public void SetUpdatedSnapshotHandler (Action<NWPath> callback)
 				}
 			}
 		}
+		Action<NWPath> userSnapshotHandler;
+
+		public void SetUpdatedSnapshotHandler (Action<NWPath> callback)
```
Comment (mandel-macaque) [inline src/Network/NWPathMonitor.cs]: I would Obsolete the method and add a Property as the new API.
```suggestion
		Action<NWPath> SnapshotHandler { 
			get => userSnapshotHandler; 
			set => userSnapshotHandler = value; 
		}
		
		[Obsolete ("Use the 'SnapshotHandler' property instead.")]
		public void SetUpdatedSnapshotHandler (Action<NWPath> callback)
```

File: tests/monotouch-test/Network/NWPathMonitorTest.cs [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+                });
+
+                var q = new DispatchQueue (label: "monitor");
+                monitor.SetQueue (q);
+                monitor.Start ();
+
+            }, () => isPathUpdated);
+
+            Assert.That (finalPath, Is.Not.Null);
```
Comment (spouliot) [inline tests/monotouch-test/Network/NWPathMonitorTest.cs]: when a test has more than one `Assert` call then use a label/message. It can be any string (e.g. "1", "2") as long as it's unique.

The reason is that, sometimes, the debugging symbols are missing and/or the stack trace is off - and it can be hard to determine what failed from logs. Adding a label solves this :)

File: src/Network/NWPathMonitor.cs (hunk 4 above)
Comment (mandel-macaque) [reply src/Network/NWPathMonitor.cs]: Yep, I have the same point of view.

File: src/Network/NWPathMonitor.cs (hunk 1 above)
Comment (dalexsoto) [reply src/Network/NWPathMonitor.cs]: You can find more about our coding guidelines here https://www.mono-project.com/community/contributing/coding-guidelines/

File: src/Network/NWPathMonitor.cs [hunk 8]
```diff
@@ -72,7 +86,7 @@ static void TrampolineUpdatedSnapshot (IntPtr block, IntPtr path)
 		static extern unsafe void nw_path_monitor_set_update_handler (IntPtr handle, void *callback);
 
 		[BindingImpl (BindingImplOptions.Optimizable)]
-		public void SetUpdatedSnapshotHandler (Action<NWPath> callback)
+		void InternalSetUpdatedSnapshotHandler (Action<NWPath> callback)
```
Comment (VincentDondain) [inline src/Network/NWPathMonitor.cs]: Minor but I think we usually go `_SetUpdatedSnapshotHandler` for internal stuff.

File: tests/monotouch-test/Network/NWPathMonitorTest.cs (hunk 7 above)
Comment (prmallic) [reply tests/monotouch-test/Network/NWPathMonitorTest.cs]: I'm not familiar with testing, but what do the `[TestFixture]` and `[Test]` attributes do/how do they work?

File: src/Network/NWPathMonitor.cs [hunk 9]
```diff
@@ -91,6 +105,12 @@ public void SetUpdatedSnapshotHandler (Action<NWPath> callback)
 				}
 			}
 		}
+		Action<NWPath> userSnapshotHandler;
```
Comment (VincentDondain) [inline src/Network/NWPathMonitor.cs]: Please add a new line before this `Action`.

File: src/Network/NWPathMonitor.cs (hunk 1 above)
Comment (prmallic) [reply src/Network/NWPathMonitor.cs]: i think it is private by default, so they private keyword isn't required

File: tests/monotouch-test/Network/NWPathMonitorTest.cs (hunk 7 above)
Comment (spouliot) [reply tests/monotouch-test/Network/NWPathMonitorTest.cs]: https://github.com/nunit/docs/wiki/Attributes :)

File: src/Network/NWPathMonitor.cs (hunk 6 above)
Comment (mandel-macaque) [reply src/Network/NWPathMonitor.cs]: my code is missing ```public```

File: src/Network/NWPathMonitor.cs (hunk 1 above)
Comment (wachaudh) [reply src/Network/NWPathMonitor.cs]: fixed

File: tests/monotouch-test/Network/NWPathMonitorTest.cs [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+
+        [TearDown]
+        public void TearDown ()
+        {
+            monitor?.Dispose ();
+        }
+
+    }
+}
+#endif
```
Comment (spouliot) [inline tests/monotouch-test/Network/NWPathMonitorTest.cs]: the file indentation is incorrect, it's all spaces while it should be using tabs. Please check your editor settings :)

**Comment by wachaudh** [comment]
> It's not clear how the swift implementation behave. Right now if you set a custom action then `CurrentPath` won't be updated (which might not be obvious to the developer)

CurrentPath actually does get updated because of `SetUpdatedSnapshotHandlerWrapper`. I've added a new test `PathIsAlwaysUpdatedWithNewHandlerTest` to check for this.

File: tests/monotouch-test/Network/NWPathMonitorTest.cs [hunk 11]
```diff
@@ -0,0 +1,117 @@
...
+using CoreFoundation;
+using Foundation;
+
+using NUnit.Framework;
+
+
+namespace monotouchtest.Network
+{
+	[TestFixture]
+	[Preserve(AllMembers = true)]
```
Comment (spouliot) [inline tests/monotouch-test/Network/NWPathMonitorTest.cs]: Looks like you're spaces->tabs conversion broke the coding style, e.g. space before `(`, across all the file.
Double check your VSfM settings - that _should_ not happen
