### PR TITLE
[CoreText] Implement CTFontDescriptor.MatchFontDescriptors. Fixes #19397.

### LINKED ISSUE #19397: Binding request: CTFontDescriptor.MatchFontDescriptors
Would it be possible to bind/fix the `CoreText.CTFontDescriptor.MatchFontDescriptors` method?
https://github.com/xamarin/xamarin-macios/blob/6f45caa84db8e45df6866d564603930f1cac9d64/src/CoreText/CTFontDescriptor.cs#L756-L766

My goal is to download fonts dynamically
- https://developer.apple.com/library/archive/samplecode/DownloadFont/Listings/DownloadFont_ViewController_m.html
- https://medium.com/@chunkyguy/downloading-fonts-on-ios-ad97977308b5

### Steps to Reproduce
`var success = CoreText.CTFontDescriptor.MatchFontDescriptors(new CoreText.CTFontDescriptor[0], null, null);
`

### Expected Behavior
no crash, API works

### Actual Behavior
`NotImplementedException`

### Environment
.NET 8 RC2.1

### PR DESCRIPTION
**Pull request by rolfbjarne**
Fixes https://github.com/xamarin/xamarin-macios/issues/19397.

### CODE REVIEW

File: src/CoreText/CTFontDescriptor.cs [hunk 1]
```diff
@@ -738,34 +739,67 @@ public CTFontDescriptor (CTFontDescriptorAttributes attributes)
...
+		[UnmanagedCallersOnly]
 #endif
+		static byte MatchFontDescriptorsHandler (IntPtr block, CTFontDescriptorMatchingState state, IntPtr progress)
+		{
+			var del = BlockLiteral.GetTarget<CTFontDescriptorProgressHandler> (block);
+			if (del is not null) {
+				var progressDictionary = Runtime.GetNSObject<NSDictionary> (progress)!;
+				var strongDictionary = new CTFontDescriptorMatchingProgress (progressDictionary);
+				var rv = del (state, strongDictionary);
+				return rv ? (byte) 1 : (byte) 0;
```
Comment (mandel-macaque) [inline src/CoreText/CTFontDescriptor.cs:762]: We like to cast too much hehe
```suggestion
				return (byte) (rv ? 1 : 0);
```
Of course this is meant as a joke, no need to change a thing ;)

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by haritha-mohan — APPROVED** [review]
