### PR TITLE
[AVFoundation] Fix callback signature for the AVAudioSinkNode constructor. Fixes #17575.

### LINKED ISSUE #17575: [Bug] Xamarin.iOS delegate  AVAudioSinkNodeReceiverHandler gives strange reference to AudioBuffers
---
**Issue moved from xamarin/Xamarin.Forms#15694**
- Please respond to @Grubleren.

---

_From @Grubleren on Thursday, February 16, 2023 11:05:32 AM_

I am trying to use the iOS sink node as in the following example
Visual Studio 2022 17.4.4
Remote connection to Mac
```C#

using System;
using System.Runtime.InteropServices;
using System.Threading;
using Foundation;
using AudioToolbox;
using AVFoundation;
using UIKit;

void SomeFunc()
        {
           var  engine = new AVAudioEngine();
            var inputNode = engine.InputNode;
            var inputFormat = inputNode.GetBusOutputFormat(0);
            var handler = new AVAudioSinkNodeReceiverHandler(SinkHandler);   
            var sinkNode = new AVAudioSinkNode(handler); 
            engine.AttachNode(sinkNode);
            engine.Connect(inputNode, sinkNode, inputFormat);
            NSError error;
            engine.StartAndReturnError(out error);
        }

 int SinkHandler(AudioTimeStamp ts, uint n, ref AudioBuffers buffers)
        {
                    int nCh = buffers.Count;
                    for (int i = 0; i < nCh; i++)
                    {
                        var f = buffers[i].Data;
                        Marshal.Copy(f, data, 0, (int)n);
                    }

            return 0;
        }

```
The program crash since buffers is not a valid reference to AudioBuffers. Also it is strange to use a ref parameter in the delegate
AVAudioSinkNodeReceiverHandler.  I cannot find a way to make it work

### LINKED ISSUE #17755: [Bug] Xamarin.iOS delegate AVAudioSinkNodeReceiverHandler gives strange reference to AudioBuffers
Link to #17575 the original issue.
I have made the repository https://github.com/Grubleren/TestSinkHandler, that clearly demonstrate the problem. Just run the solution.

### PR DESCRIPTION
**Pull request by rolfbjarne**
The callback to the AVAudioSinkNode constructor was declared incorrectly, and
if used, the app would crash at runtime.

This fix does a few things:

* Creates an overload with callback signature that matches the native API
  (using IntPtrs).
* Writes a custom version for the broken callback signature to make it work
  (and this overload is obsoleted, and removed in XAMCORE_5_0).
* Adds a third overload with the ideal signature.
* Adds tests.

Fixes https://github.com/xamarin/xamarin-macios/issues/17575.

### CODE REVIEW

File: src/avfoundation.cs [hunk 1]
```diff
@@ -16327,7 +16327,7 @@ interface AVAudioSourceNode : AVAudioMixing {
 #endif
 	}
 
-	delegate int AVAudioSinkNodeReceiverHandler (AudioTimeStamp timestamp, uint frameCount, ref AudioBuffers inputData);
+	delegate int AVAudioSinkNodeReceiverHandlerRaw (IntPtr timestamp, uint frameCoun, IntPtr inputData);
```
Comment (tj-devel709) [inline src/avfoundation.cs:16330]:
```suggestion
	delegate int AVAudioSinkNodeReceiverHandlerRaw (IntPtr timestamp, uint frameCount, IntPtr inputData);
```

**Review by tj-devel709 — COMMENTED** [review]
Small typo in param name, but otherwise LGTM

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Review by haritha-mohan — APPROVED** [review]
