### PR TITLE
[msbuild] Set 'CopyNuGetImplementations' to true for app extensions. Fixes #4235 and #4237.

### LINKED ISSUE #4235: error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks.
### Description
Not all apps are affected, I'm not sure what is special about this one in particular. Unfortunately we did not catch this sooner because of a mixup with the SeeingAI teams app repo (it moved and we didn't know so we were still testing their old source). Not sure if it's relevant but it seems a similar issue has cropped up (but resolved) in the community: https://github.com/xamarin/xamarin-macios/issues/4101 

### Steps to Reproduce

1. Install XI 11.10.1.177 or later (15.7 RTW)
2. Clone the SeeingAI app (internal)
3. Build it in Release config

### Expected Behavior

Successful build 

### Actual Behavior

```
2018-06-04T20:16:28.9530910Z (_CompileToNative target) -> 
2018-06-04T20:16:28.9553430Z   error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks. Please file a bug report with a test case (http://bugzilla.xamarin.com). [/Users/vsts/agent/2.134.2/work/1/s/iOS/App/SeeingAI.iOS.csproj]
2018-06-04T20:16:28.9562760Z 
```

### Environment

```
Xcode | 9.4.0 | Xcode_9.4.xip
Xamarin.iOS | 11.10.1.177 | xamarin.ios-11.10.1.177.pkg
Xamarin.Mac | 4.4.1.176 | xamarin.mac-4.4.1.176.pkg
Visual Studio for Mac | 7.5.0.1254 | VisualStudioForMac-7.5.0.1254.dmg
Mono | 5.10.1.47 | MonoFramework-MDK-5.10.1.47.macos10.xamarin.universal.pkg
```

### Build Logs

Failed 15.7 RTW (11.10.1.177): http://build.devdiv.io/1745621

This is also reproducible with 15.7 SR3 and Master. (Master -> build.devdiv.io/1764931 - see Release config).

Successful 15.6 (11.9.1.24) : http://build.devdiv.io/1746181 - please ignore the failed Windows build (it's failed due to this bug, only the Mac build in this job is truly using 15.6)

### Example Project (If Possible)
 
Contact me on Slack and we can work out getting you access to SeeingAI app.

### PR DESCRIPTION
**Pull request by rolfbjarne**
In Xamarin.iOS.Common.targets, just before the _CompileToNative target, we
modify the mtouch references to ensure that we get the lib assemblies for
nugets, and not the ref references:

https://github.com/xamarin/xamarin-macios/blob/9e31d07ecc08a64372dd562e843c3d8950d24985/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets#L784-L791

This logic removes nuget references, and then re-adds any copy-local dll
references.

This works fine in executable projects, but not in library projects (aka
extensions), because nugets aren't copied for library projects:

https://github.com/NuGet/NuGet.BuildTasks/blob/cf4b0a12cf1f75e0654f28c2a9020251c41d126a/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.targets#L86

So we need to set the CopyNuGetImplementations variable to 'true' for our
library projects.

Fixes https://github.com/xamarin/xamarin-macios/issues/4235.
Fixes https://github.com/xamarin/xamarin-macios/issues/4237.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
Is there anybody else knowledgable about nugets who can verify that this fix makes sense?

**Comment by spouliot** [comment]
@VincentDondain please have a look since you did the original fix.
@mrward your input wrt nuget would be appreciated too

**Comment by rolfbjarne** [comment]
The new test fails because it requires MSBuild, and MSBuild picks up some assemblies from the system XI, not the locally built one.

IOW the new tests in this PR requires PR #4111, so let's wait a bit to see if we can get that completed.

**Comment by chamons** [comment]
@radical might be a good set of eyes here.

Do we need this hack for Xamarin.Mac?

**Comment by rolfbjarne** [comment]
> Do we need this hack for Xamarin.Mac?

Yeah, probably, I'll test it.

**Comment by chamons** [comment]
I've hopefully un-failed at reading comprehension and added a test that actually uses XM extensions, which still doesn't need a fix (?)

File: tests/mmptest/src/ExtensionTests.cs [hunk 1]
```diff
@@ -20,8 +20,10 @@ public void TodayExtension_SmokeTest ()
 
 			MMPTests.RunMMPTest (tmpDir =>
 			{
-				string testPath = Path.Combine (TI.FindSourceDirectory (), @"Today/TodayExtensionTest.csproj");
-				TI.BuildProject (testPath, isUnified: true);
+				TI.CopyDirectory (Path.Combine (TI.FindSourceDirectory (), @"Today"), tmpDir);
```
Comment (chamons) [inline tests/mmptest/src/ExtensionTests.cs]: The extension tests were building in place, which was lazy and wrong of me. Let's copy them to temp.

We also need this since we added a variable to substitute in today.

**Comment by chamons** [comment]
It looks like we're failing on nuget restore, (due to not having a way to redirect msbuild?).

In any case, I'll disable the tests for now :(

**Comment by chamons** [comment]
build

**Comment by chamons** [comment]
We already have https://github.com/xamarin/xamarin-macios/issues/4110 open which I refer'ed to in each comment out. When we fix that, we'll have to search for that (along with the original bugzilla number) and comment in a bunch of tests.

I also merged master to fix the merge conflict.

**Comment by spouliot** [comment]
failure due to disk space
```
18:20:26 System.IO.IOException: Disk full. Path /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/jenkins-results/tests/MSBuild tests_268/execute-20180815_140058.txt
```

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
Test failure is unrelated (https://github.com/xamarin/maccore/issues/827, test actually succeeded, the reporting of it failed).

**Comment by spouliot** [comment]
@monojenkins backport to xcode10
