### PR TITLE
[bgen] Fix assembly comparison. Fixes #19612.

### LINKED ISSUE #19612: [iOS] [.NET 8] Binding library source generator does not use interface for protocols
Hello,

I'm trying to update my iOS binding library from .NET 7.0 to 8.0, but I believe the code behind source generator is not generating the correct code. When I define a protocol, it's not using the generated interface causing the object to try to inherit from both the NSObject and the protocol class. This results in compiler error CS1721 (cannot have multiple base classes).

This was working correctly in .NET 7.0, could I be missing a breaking change?

### Steps to Reproduce

Create a new binding library and add the following code to the ApiDefinition.cs in a namespace of your choosing.

```cs
using System;
using ObjCRuntime;
using Foundation;
using UIKit;

[Protocol]
[BaseType(typeof(NSObject))]
public interface ReaderProtocol
{
    // @required -(NSString *)firstName;
    [Abstract]
    [Export("firstName")]
    string FirstName { get; }
}

// @interface Reader : NSObject <ReaderProtocol>
[BaseType(typeof(NSObject))]
public interface Reader : ReaderProtocol
{
    // -(id)initWithPreferredReader:(NSString *)name;
    [Export("initWithPreferredReader:")]
    IntPtr Constructor(string name);
}
```
### Expected Behavior

The generated Reader.g.cs file should have a ```Reader``` class with the following signature (net7.0-ios behavior):

```cs
[Register("Reader", true)]
public unsafe partial class Reader : NSObject, IReaderProtocol {
...
}
```

### Actual Behavior

The generated Reader.g.cs file contains a ```Reader``` class with the following signature (net8.0-ios behavior):

```cs
[Register("Reader", true)]
public unsafe partial class Reader : NSObject, ReaderProtocol {
...
}
```

This causes the compiler to throw error CS1721 "Class 'Reader' cannot have multiple base classes: 'NSObject' and 'ReaderProtocol'.

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

### PR DESCRIPTION
**Pull request by rolfbjarne**
This fixes a regression in .NET 8, where we changed the temporary assembly name when
building using a project file / MSBuild - we started compiling the temporary binding
code in MSBuild instead of in the generator, and in the process we changed the name
of the temporary assembly. This broke logic in bgen that compared the assembly name
to check if a given type is from the temporary assembly or not.

Fix this by checking the actual temporary assembly instead of the name of the assembly
instead.

Fixes https://github.com/xamarin/xamarin-macios/issues/19612.

### CODE REVIEW

File: src/bgen/BindingTouch.cs [hunk 1]
```diff
@@ -372,6 +373,11 @@ int Main3 (string [] args)
 		return 0;
 	}
 
+	public bool IsApiAssembly (Assembly assembly)
+	{
+		return assembly == apiAssembly;
+	}
+
```
Comment (mandel-macaque) [inline src/bgen/BindingTouch.cs:380]: Can we move this to the Generator class? That way we do not need to call it as BindingTouch.IsApiAssembly, just call the method. Ideally would be nice to be able to have the generator be self-contained and that way be able to unit test things like this.

Would be nice to have the integration tests we have atm + unit tests for this kind of logic.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/bgen/BindingTouch.cs (hunk 1 above)
Comment (rolfbjarne) [reply src/bgen/BindingTouch.cs]: @mandel-macaque fixed
