### PR TITLE
[mtouch/mmp] Rework how we find developer tools. Partial fix for #4634 and fixes #8005.

### LINKED ISSUE #8005: Application with multiple architectures (ARMv7 and ARM64) successfully builds by using real Xcode, but it is failed by using symlink to real Xcode on macOS Catalina.
### Steps to Reproduce

1. Create symlink to Xcode: `ln -s "path/to/xcode" "/Applications/Xcode.app"`
2. Switch Xcode to symlink: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"`
3. Create an iOS project, makes sure it has multiple architectures selected (and device-specific builds disabled), and build it.

### Expected Behavior
Successfully build.

### Actual Behavior
Build is failed:
```
lipo : error : sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find lipo 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory) 
xcode-select: Failed to locate 'lipo', requesting installation of command line developer tools.

MTOUCH : error MT5306: Failed to create the a fat library. Please review the build log.
```

The command line tools is installed: `sudo xcode-select --install`
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

### Environment
```
macOS 10.15.3 Catalina
Xamarin.iOS 13.10
Mono 6.6
Visual Studio for Mac 8.4.5.19
```
 
### Workarounds:
- set environment variable `export SDKROOT=macosx`
or 
- once run lipo before build `/usr/bin/lipo 2>null>`

### PR DESCRIPTION
**Pull request by rolfbjarne**
Partial fix for https://github.com/xamarin/xamarin-macios/issues/4634.
Fixes https://github.com/xamarin/xamarin-macios/issues/8005.

### CODE REVIEW

File: tools/common/Driver.cs [hunk 1]
```diff
@@ -809,5 +787,162 @@ internal static bool ParseBool (string value, string name, bool show_error = tru
...
+		{
+			var env = new List<string> ();
+			// Unset XCODE_DEVELOPER_DIR_PATH. See https://github.com/xamarin/xamarin-macios/issues/3931.
+			env.Add ("XCODE_DEVELOPER_DIR_PATH");
+			env.Add (null);
+			// Set DEVELOPER_DIR if we have it
+			if (!string.IsNullOrEmpty (DeveloperDirectory)) {
+				env.Add ("DEVELOPER_DIR");
+				env.Add (DeveloperDirectory);
+			}
```
Comment (spouliot) [inline tools/common/Driver.cs]: ^ does the above change ? or can it be cached and reused

Comment (rolfbjarne) [reply tools/common/Driver.cs]: You mean cache the list of environment values? Not sure if that's necessary, because we cache the result from this function.

Comment (spouliot) [reply tools/common/Driver.cs]: It's more for consistency across invocations than time savings. If we believe it can change then the caching is not really correct. If it can't change then it does not need to be repeated for every tool being queried. Current code makes it ambiguous (but it's not a big thing)

**Comment by rolfbjarne** [comment]
build

**Comment by rolfbjarne** [comment]
Test failure is due to https://github.com/xamarin/maccore/issues/2177.
