### PR TITLE
[AppKit] Add missing setter for generateMipmaps in NSView

### LINKED ISSUE #17383: MTKTextureLoaderOptions.GenerateMipMaps property lacks a setter
### Steps to Reproduce

1.  Create a new Mac project.
2. Create an instance of `MTKTextureLoaderOptions` from the `MetalKit` namespace.
3. Observe that the `GenerateMipMaps` property has no setter.

### Expected Behavior
Expect to be able to set this property to have MetalKit automatically create mipmaps for me per [Metal docs](https://developer.apple.com/documentation/metalkit/mtktextureloader/option/1645867-generatemipmaps).

### Actual Behavior
Cannot set the property.

### Environment

IDE: Rider 2023.3.1
.NET SDK: 7.0.102

### PR DESCRIPTION
**Pull request by haritha-mohan**
Fixes #17383

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

File: src/metalkit.cs [hunk 1]
```diff
@@ -256,7 +256,7 @@ interface MTKTextureLoaderOptions {
 		[iOS (10, 0)]
 		[Mac (10, 12)]
 		[MacCatalyst (13, 1)]
-		bool GenerateMipmaps { get; }
+		bool GenerateMipmaps { get; set; }
```
Comment (dalexsoto) [inline src/metalkit.cs:259]: Will xtro be happy?

Comment (rolfbjarne) [reply src/metalkit.cs:259]: Yep, it ran just fine on the bots.

**Review by rolfbjarne — APPROVED** [review]

**Review by tj-devel709 — APPROVED** [review]
