### PR TITLE
[Foundation] Fix validate for insert for NSMutableArray<T>. Fixes #6876.

### LINKED ISSUE #6876: Inserting to end of NSMutableArray<T> raises an IndexOutOfRangeException
### Steps to Reproduce

1. Create a new NSMutableArray`<T>` object where T implements NSObject.
2. Insert an object of type T with the index as the size of the array, which in this case, will be 0.

### Expected Behavior
The object should be inserted into the end of the array(Note: the expected behavior does occur for a non-generic NSMutableArray, this issue only occurs for the generic NSMutableArray)

### Actual Behavior
A System.IndexOutOfRangeException is raised.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.4 (build 17)
Installation UUID: fab8a8b1-02f0-4583-b591-000d9a758734
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/richardahn/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/richardahn/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64


```

### PR DESCRIPTION
**Pull request by wachaudh**
Fix `IndexOutOfRangeException` when trying to insert into any empty NSMutableArray\<T\>. Fixes https://github.com/xamarin/xamarin-macios/issues/6876.

### CODE REVIEW

File: src/Foundation/NSMutableArray_1.cs [hunk 1]
```diff
@@ -166,7 +166,7 @@ void ValidateIndex (nint index)
 			if (index < 0)
 				throw new IndexOutOfRangeException (nameof (index));
 
-			if ((nuint) index >= Count)
+			if ((nuint) index > Count)
```
Comment (Therzok) [inline src/Foundation/NSMutableArray_1.cs]: This check makes the < 0 check redundant btw.

File: tests/monotouch-test/Foundation/NSMutableArray1Test.cs [hunk 2]
```diff
@@ -88,6 +88,10 @@ public void InsertTest ()
 				Assert.AreSame (v2, arr [1], "[1]");
 				Assert.AreSame (v3, arr [2], "[2]");
 			}
+
+			using (var arr = new NSMutableArray<NSString>()) {
+				Assert.DoesNotThrow (() => arr.Insert (v1, 0), "Insert into empty array");
```
Comment (Therzok) [inline tests/monotouch-test/Foundation/NSMutableArray1Test.cs]: Can we add an assert for -1?

Comment (Therzok) [reply tests/monotouch-test/Foundation/NSMutableArray1Test.cs]: Nevermind, done above.

File: src/Foundation/NSMutableArray_1.cs (hunk 1 above)
Comment (Therzok) [reply src/Foundation/NSMutableArray_1.cs]: It's used in a lot of places in corefx: [1](https://source.dot.net/#System.Collections/System/Collections/BitArray.cs,0ed1a118969f6946,references) [2](https://source.dot.net/#System.Memory/System/Buffers/ArrayMemoryPool.cs,fabbb5d9ac585197,references) [3](https://source.dot.net/#System.Memory/System/Buffers/SequenceReader.cs,327) [4](https://source.dot.net/#System.Memory/System/Buffers/Text/Base64Encoder.cs,722f85d379c418d5,references) [5 List<T>](https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Generic/List.cs,0c65bec4d3fac21e,references) [6 List<T>.InsertRange](https://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Generic/List.cs,79de3e39e69a4811,references)
